### ISSUE TITLE
Trim leading zeros of hex strings in graphql responses

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#1008]
**Background:**
In our SQLite database, the indexer saves some cairo primitive types (u128, u256, felt252) as hex strings. To enable lexicographical sorting, we pad these values with up to 64 leading zeros.

**Issue:**
When querying these values, we currently return them with the leading zeros, which is not ideal.

**Proposed Solution:**
Trim the leading zeros from the hex strings in the query responses. For instance:
```"0x00000000000000000000000000000000000000000000005468652042726f6e78" -> "0x5468652042726f6e78".```

**Comment by akhercha** [comment]
Hi! Can I take this one?
