### ISSUE TITLE
Support sozo execute by name

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1012]
Currently, it is required to pass the contract address when calling `sozo execute`. We would like to support executing by contract name.

Currently:

```
sozo execute --manifest-path examples/ecs/Scarb.toml 0x19cbafa838c97f28b2392c1b77acf131d8b915f3c892379d7dff501aa4695fc move --calldata 0x314d21c89db29f82669c54f62e291b8b90effc5725fb12291566635b54b8614 --calldata 0x1
```

Where `0x19cbafa838c97f28b2392c1b77acf131d8b915f3c892379d7dff501aa4695fc` is the contract name.

Future:

```
sozo execute --manifest-path examples/ecs/Scarb.toml player_actions move --calldata 0x314d21c89db29f82669c54f62e291b8b90effc5725fb12291566635b54b8614 --calldata 0x1
```

To do so, we need to compute the contract address based on the contract name, which can be done by:

Fetch the base contract class hash from here: https://github.com/dojoengine/dojo/blob/e2082ec8dea2fa58e0dcbca72ca438b8fc6412fe/crates/dojo-core/src/world.cairo#L35
The contract address is calculated like this: https://github.com/dojoengine/dojo/blob/fc2d3aa3e671cd7b7de3c63e585d2865a2340569/crates/dojo-world/src/migration/mod.rs#L177
Where the salt is calculated like this https://github.com/dojoengine/dojo/blob/fc2d3aa3e671cd7b7de3c63e585d2865a2340569/crates/dojo-world/src/migration/strategy.rs#L191
So we only need one call to the world contract to get the base class hash then can compute any contracts address based on its name

This address computation already exists in the code base but can potentially be better abstracted for reuse.

**Comment by azurwastaken** [comment]
Hello, I would try this one if possible :)

**Comment by tarrencev** [comment]
> Hello, I would try this one if possible :)

Awesome! Go for it!

**Comment by ponderingdemocritus** [comment]
@Dl-Vv are you still able to take this?

**Comment by ponderingdemocritus** [comment]
self assigning
