### ISSUE TITLE
[BUG] Torii graphql type name collision

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#1032]
**Describe the bug**
In graphql, we have several types that are predefined like Entity, SystemCall, Model, Event, MetaData, Query, and Subscription. And apart from Query/Subscription, each type has further variation of {name}Edge, {name}Connection, for relay connection types. 

For each Model in a dojo project we create a corresponding type. This is also true for nested/custom cairo types. 

For example
```
#[derive(Model, Copy, Drop, Serde)]
struct Position {
  #[key]
  player: ContractAddress
  vec: Vec2
}

#[derive(Copy, Drop, Serde, Print, Introspect)]
struct Vec2 {
  x: u32,
  y: u32
}
```

Creates the corresponding graphql types
```
type Position {
  player: ContractAddress
  vec: Vec2
}

type Vec2 {
  x: u32
  y: u32
}
```

The issue is we run into name collisions if there are any models or custom cairo types with the same name as the predefined types (for example if `Position` have a nested struct called `MetaData`).  

**Proposed solution**
When building the schema for [model objects](https://github.com/dojoengine/dojo/blob/d148f333dcf08d8f41a919a48c34093b3f3fe938/crates/torii/graphql/src/schema.rs#L38) we check its types against predefined types, if collision then perhaps exit and alert user to rename their Model or custom cairo type

**Comment by tarrencev** [comment]
Hmm I think we might need to namespace all types using the Model they are defined in. Otherwise, anyone could break torii but deploying a conflicting type

**Comment by broody** [comment]
Oh right... Wanted to avoid namespacing to keep it clean, but looks like unavoidable. 

How about using `_` since models are pascal case? `{Model}_{CustomType}`

```
type Position {
  player: ContractAddress
  vec: Position_Vec2
}

type Position_Vec2 {
  x: u32
  y: u32
}
```

And we could also namespace the predefined objects like `World_MetaData` or `World_Query` to free up those names

**Comment by tarrencev** [comment]
Seems like a reasonable approach

**Comment by gianalarcon** [comment]
I would like to take this one. I have a draft working like this 
```
type Position {
  player: ContractAddress
  vec: Position_Vec2
}

type Position_Vec2 {
  x: u32
  y: u32
}
``` 
need to update the tests and add more rules
