### ISSUE TITLE
[torii] indexing performance issues

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1052]
indexing has become really slow. (on RYO it take close to 2s to index ~40 events) 

the store_set_record processor should be optimized : (parallelization? /  multicall? )
https://github.com/dojoengine/dojo/blob/main/crates/torii/core/src/processors/store_set_record.rs#L38-L40

a simple repo to test/emit events :
https://github.com/notV4l/torii_bench

**Comment by ponderingdemocritus** [comment]
I'm not having this issue - it seems to be syncing very fast for me

**Comment by notV4l** [comment]
maybe its less noticeable on a better machine.

there is a lot of room for improvement, actually for each event : 
- call world to retrieve class_hash -->should use db
- call world to retrieve schema -->should use db
- call world to retrieve layout -->should use db
- then 1 call for each storage to read --> must call world

**Comment by notV4l** [comment]
actually, with RYO on slot, it takes 4s to index ~40 events

**Comment by ponderingdemocritus** [comment]
closing
