### ISSUE TITLE
[katana] add a predeployed multicall contract

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1059]
- could be used by torii to solve #1052 

argent multicall : https://github.com/argentlabs/argent-contracts-starknet/blob/main/contracts/multicall/src/multicall.cairo

**Comment by kariy** [comment]
i think instead of relying on an external contract for multicalls, having it supported natively in the World itself would be nice.

cc @tarrencev

**Comment by ponderingdemocritus** [comment]
I don't understand why this needs to exist. Can't we just use a multicall from an account?

**Comment by ponderingdemocritus** [comment]
Still relevant? If not closing

**Comment by glihm** [comment]
pre-deployed accounts are now supporting multicall.
