### ISSUE TITLE
Report contract statistics after sozo build

### ISSUE THREAD

**Issue by rsodre** [dojoengine/dojo#1081]
**Is your feature request related to a problem? Please describe.**
Cairo has some limitations to contract size, gas consumption, and steps
If a developer reaches those limits, will need to know how 

[https://docs.starknet.io/documentation/tools/limits_and_triggers/](https://docs.starknet.io/documentation/tools/limits_and_triggers/)

**Describe the solution you'd like**
Display a report of all the deployed contract statistics after sozo build.
Can be an option like `--stats`

Maybe issue a warning if any parameter reaches 80% of its limits
But definitely if it reaches 100%+

**Describe alternatives you've considered**
I don't know how to get this data with the current stack

**Comment by fabrobles92** [comment]
Hello, can you provide more info about this enhancement pls?

**Comment by rsodre** [comment]
Some ideas:

* program size per system
* contract class size (the whole file)
* transaction steps used by each system
* Model storage size (how many felt slots each model occupies)
* deployment cost in gas and (maybe) ETH/STRK

**Comment by fabrobles92** [comment]
@glihm Sorry to keep bothering, It's been a couple of days I've been researching on how to achieve this. 

I feel like the sierra.json file in target/dev/ after compiling a contract may be the key here to get the program size(how many felts are) and class contract size(actual bytes in size of sierra.contract.json, or maybe the size of the casm file)

Am I looking into the right direction?

**Comment by fabrobles92** [comment]
@rsodre  I'd like to take this one.
