### ISSUE TITLE
Support deriving Print for enums

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1084]
Currently, we only support deriving `Print` for structs. 

The implementation should be updated here: https://github.com/dojoengine/dojo/blob/main/crates/dojo-lang/src/print.rs

As a reference, we support deriving `Introspect` for enums here: https://github.com/dojoengine/dojo/blob/61b4f89c0ce31c159f18eef69f9c3f506a503044/crates/dojo-lang/src/introspect.rs#L105

**Comment by 0xicosahedron** [comment]
i would like to give this a try

**Comment by tarrencev** [comment]
awesome please do!
