### ISSUE TITLE
Change model members in graphql from snake_case to camelCase

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#1096]
Currently, the name format of the model members in graphql schema matches exactly to its cairo model, which is snake_case. However, graphql convention prefers camelCase. To keep things consistent, this is a proposal to make that change. 

Since this is a bigger breaking change, perhaps we can punt to 0.4.0 if there are no heartburns... 

```
type MyModel {
  my_key: u32,
  my_member: u128
}
```

changes to

```
type MyModel {
  myKey: u32,
  myMember: u128
}
```

**Comment by gianalarcon** [comment]
I would like to take this one.

**Comment by broody** [comment]
Thinking more bout this, since case format can't be enforced on contract side, someone could break torii by deploying following Model. 

```
#[derive(Model, Copy, Drop, Serde)]
struct MyModel{
    mixed_case: u8,
    mixedCase: u8,
}
```

Maybe we leave case formatting as-is for model members only.
