### ISSUE TITLE
[Torii] Remove spawn-and-move dependency from graphql subscription test

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#1103]
Remove graphql test dependency on spawn-and-move and use types-test like models/entities. 

Also since we support this now, would be good to add test case for entityUpdate with models data
```
entityUpdate {
  models {
    ... on Record {
      ...
    }
  }
}
```

cc @gianalarcon

**Comment by gianalarcon** [comment]
Great. Gonna work on it
