### ISSUE TITLE
contract: lifecycle hooks

### ISSUE THREAD

**Issue by shramee** [dojoengine/dojo#1111]
**Is your feature request related to a problem? Please describe.**
dojo::contract removes the ability to add constructor.

**Describe the solution you'd like**
We add 2 **magic**/**lifecycle** functions, These are special functions with special functionality in dojo contracts.
1. `setup()`
    * takes no parameters
    * called by world in system deploy function
2. `upgraded()`
    * takes no parameters
    * called by world on deploy and on every contract class hash update

**Describe alternatives you've considered**
Adding a raw `starknet::contract` but that misses out on upgradable systems 😭

**Comment by ponderingdemocritus** [comment]
So we cannot upgrade contracts at the moment?

**Comment by shramee** [comment]
We can, but we can't run do stuff on init (like a constructor). And upgraded is to add stuff to run after system is updated.

**Comment by ponderingdemocritus** [comment]
closing
