### ISSUE TITLE
sozo: add writer for contract writes

### ISSUE THREAD

**Issue by shramee** [dojoengine/dojo#1114]
Manifest now has `writes` for a contract, containing model structs the contract writes to.
Let's use this to add writer for those contracts 🥳

**Comment by aymericdelab** [comment]
can i take this one ? 🖐️

**Comment by shramee** [comment]
Hi @aymericdelab,

I need to have a discussion on this. It's seems nice, but I think we might want to make this more declarative.
You might think only the owner can update a component and add it to a writer contract. But with this the contract will get the permission. So it's need some design discussion.

**Comment by aymericdelab** [comment]
maybe i'm thinking about this the wrong way but i was thinking of having :
```sozo auth writer --all --world $SOZO_WORLD $contract_address```
only callable by the owner of the world. (if account-address and private-key is in Scarb.toml)

**Comment by aymericdelab** [comment]
maybe i'm thinking about this the wrong way but i was thinking of having :
```sozo auth writer --all --world $SOZO_WORLD $contract_address```
only callable by the owner of the world. (if account-address and private-key is in Scarb.toml)

**Comment by shramee** [comment]
It is only callable by owner atm :)

**Comment by shramee** [comment]
Nice idea, right now adding writer can only called by the owner of components (or the whole world).
But this needs to be more explicit, I'm thinking a decorator to have the dev spec this. Then it automatically gets applied on migrate.

**Comment by aymericdelab** [comment]
I think i'm getting confused. Do you want to add a way to give special permission to certain addresses in model decorator ? Or do you want a way to use the manifest.json to easily grant permission for all systems ?

**Comment by ponderingdemocritus** [comment]
have assigned @aymericdelab
