### ISSUE TITLE
Store contract abi and source in contract metadata

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1121]
Dojo world have a metadata registry that supports assigning a metadata_uri to the world and contract addresses.

Update `sozo migrate` to create an ipfs artifact for the world contract and user defined contracts, storing their abi and code, so the source and abi can be easily verified offchain

First, open a PR for the world metadata, it is defined here: https://github.com/dojoengine/dojo/blob/f1e33f798e3ae333dadb85a42bc0ded915561a64/crates/dojo-world/src/metadata.rs#L71

We will want to add an `abi` and `source` field to it.

The `upload` method should be updated to upload the serialized `abi` json and the contract source to ipfs and set the ipfs uri into the `WorldMetadata` before upload.

The `WorldMetadata` migration logic starts here: https://github.com/dojoengine/dojo/blob/f1e33f798e3ae333dadb85a42bc0ded915561a64/crates/sozo/src/ops/migration/mod.rs#L344

It should be modified to always create a `WorldMetadata` with the `abi` and `source` fields and merge in the user defined metadata from the manifest.

The `abi` artifacts are generated by the compiler here: https://github.com/dojoengine/dojo/blob/f1e33f798e3ae333dadb85a42bc0ded915561a64/crates/dojo-lang/src/compiler.rs#L108

We will need to update the compiler to output the flattened source representation too.

Future extension will be to extract and store docs too.

**Comment by Bal7hazar** [comment]
I can give a try ☝️

**Comment by ponderingdemocritus** [comment]
Is this still active?

**Comment by Bal7hazar** [comment]
> Is this still active?

I dropped the PR a month ago I think, I leave someone with a better understanding of the workflow and the expectations to work on this. The PR is still there is someone wants to start from where I stop or just restart from scratch.

**Comment by ponderingdemocritus** [comment]
@tarrencev let's bounty this

**Comment by swetshaw** [comment]
Hey is this issue still open? I would like to take this up @tarrencev @ponderingdemocritus

**Comment by glihm** [comment]
> Hey is this issue still open? I would like to take this up @tarrencev @ponderingdemocritus

Hey @swetshaw, thank you for the interest in contributing! Are the explanations ok for you to start? Don't hesitate if you have any more questions.

**Comment by remybar** [comment]
Hi @swetshaw ! Are you working on this issue or can I work on it this week ?

**Comment by swetshaw** [comment]
Hey @remybar please feel free to take this up.  I am working on another issue.

**Comment by remybar** [comment]
Hi @tarrencev and @glihm !

I've added ABI and source files for the world contract in `WorldMetadata` (PR https://github.com/dojoengine/dojo/pull/1682) but I understand that we also want to store ABI and source files of other contracts (models and systems I guess ?).

I see that we have a `ResourceMetadata` model to store some metadata identified by a `resource_id`. So, the idea is to store the ABI and the source file of every contracts in this model, using the contract address as `resource_id` ?

**Comment by glihm** [comment]
> I see that we have a ResourceMetadata model to store some metadata identified by a resource_id. So, the idea is to store the ABI and the source file of every contracts in this model, using the contract address as resource_id ?

Yes, and ideally we want to build a metadata content for each of the model and contract to upload them. I don't think this metadata is suitable though: https://github.com/dojoengine/dojo/blob/4af8b033a796db9554506dc9e0e6d97d113aadcc/crates/dojo-world/src/metadata.rs#L21

We may want to create a `MetadataModel/Contract` or rework this `Metadata` into an enum that can contains them. Because in the world explorer, as we have the models and contracts being defined, we could imagine the world explorer fetching the metadata for each of them, which will automatically display a ton of information and customization from the world.

And yes, then, we use the resource id (model name and contract address) to bind the IPFS artifact to the resource on-chain.
