### ISSUE TITLE
Support call view functions in deployed contracts

### ISSUE THREAD

**Issue by shramee** [dojoengine/dojo#1123]
Takes the writer contract name/address.
Calldata as a vec of felts
Returns a vec of felts

**Comment by ponderingdemocritus** [comment]
@shramee is this being completed in #714 ? Can I close this?

**Comment by shramee** [comment]
This is done in #1219

**Comment by glihm** [comment]
I guess it was on the computed context. Will close and re-open if we have some new things around this on Torii. 👍
