### ISSUE TITLE
[Primitives] Enhance primitive library

### ISSUE THREAD

**Issue by Bal7hazar** [dojoengine/dojo#1130]
After developing several games, I've identified certain features that I frequently reuse across different games. It would be beneficial to house these features in a shared place like `dojo-primitives`.

Below is an initial list of features I propose for a first set of feature requests (subsequent features can be discussed in a separate issue):

- Dice: Capability to configure a dice by specifying the number of sides. When rolled, each face should have an equal probability of landing face-up.
- Deck: Capability to set a specific number of cards in a deck. Cards can be drawn until the deck is depleted, with each card having an equal chance of being drawn. There's no predetermined order, and cards can be discarded.

**Comment by Bal7hazar** [comment]
I can take this if relevant to work on 🤚

**Comment by ponderingdemocritus** [comment]
this is a great initiative! 

We have quite a few of these style libraries right now, maybe we should nest all these within `dojo-primitives` crate, or call it something more generic like how Alexandria is set up.

All these are primitives, it's a nice UX if we nest them all then it is only one dependency.
- defi
- grid
- random (dice etc)
- noise

Maybe we call it `origami` ?
