### ISSUE TITLE
[Core]: Potential contract address conflicts

### ISSUE THREAD

**Issue by shramee** [dojoengine/dojo#1142]
Contract addresses for a deployed contracts are differentiated by a salt, class hash and constructor args.
This is normally works fine when we deploy different code (class hash) or have a different owner/init config (constructor args) or a distinct salt.

But in our `deploy_contract` on world we,
1. use **contract name** as a salt
2. use the same **base** class hash for all contract deployments across all worlds (which is later updated)
3. Pass no constructor args

This means if two worlds have contracts with the name `player_actions` the second world won't be able to deploy it's contract even if the code is entirely different.

**Comment by tarrencev** [comment]
This shouldn't be an issue since we set `deploy_from_zero` to false in the world contract: https://github.com/dojoengine/dojo/blob/bbdd5f22a8238cfa17212df217b339712e4e714c/crates/dojo-core/src/world.cairo#L406

**Comment by shramee** [comment]
Not sure the contract deployed from is used for calculation of the contract address.

**Comment by shramee** [comment]
I think if we deployed contracts from two worlds with the same name (salt). It would fail.
```rs
deploy_syscall(
    self.contract_base.read(), salt, array![].span(), false
)
```
`contract_base` class hash would be the same for all contract deployed by all worlds. Coz it's same code.
`salt` will be same coz that's just system name.
`array![]` Empty calldata

So contracts with same name can't be deployed even if they have different code from different worlds.
