### ISSUE TITLE
Tracking world state

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#12]
So far we've planned to use a similar pattern to mud for tracking world state externally, emitting events from the world contract for indexers. I'm wondering if we could instead use the state diff directly, since we can constrain the storage address of the component state in the generated code, for example, the storage location for an entity's position state below would be:

`pedersen(keccak('state'), entity_id)`

```rust
#[contract]
mod PositionComponent {
    struct Position { x: felt, y: felt }

    struct Storage {
        world_address: felt,
        state: Map::<felt, Position>,
    }
}
```

Given the indexer knows about the components / systems that exist in the world, it could compute the entity the state update corresponds to. The tricky part is the storage address is not reversible, so the indexer would need to track entity id's that have been provisioned and compute/store the component state address.

The upside is the state diff is part of consensus state, so if we do this, clients can verifiably pull world state off rpc nodes using storage proofs, which would allow for light clients ect that don't need to replay all events to reconstruct the world state.

Tagging @fracek @ponderingdemocritus @milancermak for feedback.

**Comment by ponderingdemocritus** [comment]
This is a huge unlock/

To be clear so I fully understand:

- The indexer would keep track of `entity_ids` created only. Instead of all the state that has been emitted from the world.
- The indexer from the entity ID and a component ID would be able to reconstruct the state of that entity
- This allows us to compute not only in the indexer but also in a lite client running in the browser (that would need to know the IDS)

**Comment by tarrencev** [comment]
yeah! the client would need to know the id's it cares about (which could come from an indexer or from doing a lookup on the world contract). given a particular entity id and component id, the client it can compute the entities component state storage slot and query it from an rpc node along with an associated storage proof

**Comment by ponderingdemocritus** [comment]
is an indexer even needed in this scenario? If we only need to know what entities exist, then a query to the contract of the last entity created (assuming they are all sequential) is all that is needed.

This function could just be wrapped up in the RPC node and perhaps just a plugin to @fracek apibara. 

So tx flow is:

`client -> proxy -> network `

an emit happens but it doesn't need to be indexed (unless I am missing something)

View flow is:

`client <-> proxy <-> apibara` (no more indexer)

**Comment by fracek** [comment]
I think in some way the client needs to know an old entity was updated with new values. (That won't result in a new entity id).

**Comment by milancermak** [comment]
Not dismissing the idea at all, but I think we'll still need the stream of indexed events to create gameplay progress - for example, how a battle developed (A inflicts 65 hitpoints on B, B inflicts 94 hitpoints on A, A dies ...) or how a ship traveled (moves to grid (321, 90), moves to grid (321, 95), ...).

**Comment by tarrencev** [comment]
> I think in some way the client needs to know an old entity was updated with new values. (That won't result in a new entity id).

If the client has a set of entities and components it is interested in, it can call `starknet_getStateUpdate` for each block and detect if their values have changed from there.

> Not dismissing the idea at all, but I think we'll still need the stream of indexed events to create gameplay progress - for example, how a battle developed (A inflicts 65 hitpoints on B, B inflicts 94 hitpoints on A, A dies ...) or how a ship traveled (moves to grid (321, 90), moves to grid (321, 95), ...).

Yeah 100% agree most compelling experiences would still need an indexer (particularly for historical state). This property on enables a trustless sync of the current world state and reduces the complexity of the core implementation

**Comment by fracek** [comment]
It should be possible to stream evens + state changes to compute the state of the game and then request a state proof to verify the node/indexer was honest? I also wonder how it plays out in games like Dark Forest where keeping the entire game state stored is infeasible, so players only need a subset of it.

**Comment by ponderingdemocritus** [comment]
should we close this?
