### ISSUE TITLE
[BUG] rpc_url in config defaults to localhost

### ISSUE THREAD

**Issue by robertkodra** [dojoengine/dojo#1200]
**Describe the bug**
I've tried to change the rpc_url in the `Scarb.toml` file to a new URL, however it default to the localhost one. 

**To Reproduce**
1. Go to `Scarb.toml` and change the `rpc_url` to a different one. 
2. Run `sozo build` and then `sozo migrate --name test`
3. Get error

**Expected behavior**
_Caused by:
    error sending request for url (http://localhost:5050/): error trying to connect: tcp connect error: Connection refused (os error 61)_

**Comment by kariy** [comment]
this should already be fixed in #1188
