### ISSUE TITLE
[katana] add support for JSON rpc `v0.5.1`

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1229]
**Is your feature request related to a problem? Please describe.**
Some new methods in the [JSON RPC spec](https://github.com/starkware-libs/starknet-specs) are causing trouble with SDKs like Starknetjs. 

**Describe the solution you'd like**
Starknet-rs has now support for `v0.5.1`, Katana should be updated to support that. @kariy what's the expected time for #1214? Should we wait this before submitting a PR, or is it better to first add support for `v0.5.1`?

This is [the diff](https://github.com/starkware-libs/starknet-specs/compare/v0.4.0...v0.5.1) from `v0.4.0` to `v0.5.1`.

**Comment by glihm** [comment]
Update on that:

- [x] : refacto Katana crates
- [x] : update blockifier and cairo to 2.4.0
- [ ] : implement the new RPC spec support

**Comment by glihm** [comment]
I'll close this one in favor of #1251.

**Comment by kariy** [comment]
ah my bad i forgot this issue exist
