### ISSUE TITLE
Support running Katana in secure enclave

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1232]
Add support for the fortanix target for Katana, enabling it to run inside a secure enclave, supporting e2e encryption to provide more robust centralized sequencing security guarantees. The operator will run an attested binary, preventing it from manipulating transaction ordering or other sequencer functionality

https://github.com/fortanix/rust-sgx

**Comment by ponderingdemocritus** [comment]
Lets bounty this @tarrencev
