### ISSUE TITLE
[sozo] invalid manifest `writes` values in some case

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1233]
**Describe the bug**
If `set!` is used in a loop, manifest `writes` field do not includes used models.
If `set!` is used in a function called by contract, manifest `writes` field do not includes used models.
`get!` looks ok

**To Reproduce**
loop [https://github.com/notV4l/dojo-starter/blob/bad_writes_gen/src/actions.cairo#L43](https://github.com/notV4l/dojo-starter/blob/bad_writes_gen/src/actions.cairo#L43)
function [https://github.com/notV4l/dojo-starter/blob/9d938d9be97c0b9266bf4c9dd57affe59b41e660/src/actions_2.cairo#L28](https://github.com/notV4l/dojo-starter/blob/9d938d9be97c0b9266bf4c9dd57affe59b41e660/src/actions_2.cairo#L28)

```
     "reads": [
        "Moves",
        "Position"
      ],
      "writes": [],
      "computed": []
```

**Comment by glihm** [comment]
This needs to be investigated again with the new procedural macro design from scarb. Will consider it to be blocked right now as I'm not sure if the new manifest system is computing the `write`. @lambda-0x any insight on that?

**Comment by lambda-0x** [comment]
in the new manifest system i didn't change any logic related to how this values are calculated

**Comment by tarrencev** [comment]
i don't think we will be able to do this automatically with the new macro system unfortunately

**Comment by glihm** [comment]
> i don't think we will be able to do this automatically with the new macro system unfortunately

Same here. Let’s move on for now and consider this to be a manual input from the user into the overlay if you agree guys.
I will add the overlay concept in the todo list of the sozo documentation issue. 👍
