### ISSUE TITLE
[core] implement a `delete!` macro

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#1241]
We need to implement a `delete!` macro which will allow simple deleting of entities 

This macro should be shorthand for this world function:

world.cairo
```rust
fn delete_entity(ref self: T, model: felt252, keys: Span<felt252>, layout: Span<u8>);
```

Proposal would be a macro that interprets layout so that users can simply:

```rust
delete!(world, model, keys);
```

**Comment by dubzn** [comment]
Hey Loaf, I would like to try to solve this over the weekend. Can you assign it to me? thanks sir

**Comment by ponderingdemocritus** [comment]
great!

**Comment by ponderingdemocritus** [comment]
@dubzn realised I made a mistake in OP. It should really just mirror 'set!(world, model)' no need for keys since they exist within the model ofc

**Comment by dubzn** [comment]
ok sir, i have some questions. Ill send dm for telegram, its that ok?
