### ISSUE TITLE
ERC* System + Components

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#125]
In order to make the properties of existing standards available in a dojo world, we need to implement them with components and systems.

For example, an ERC20 implementation could consist of:

`FungibleMetadata` + `Balance` components
`Transfer`, `Mint` system

That would allow the world to easily interact with a users token balance.

In addition, we would provide a `ERC20` wrapper that implements the ERC20 interface and makes calls to the world contract / transfer system in order to perform transfer, return user balances, ect

**Comment by Cheelax** [comment]
I will try to implement a first version of ERC20, some questions to begin:
- can you confirm it will be put in /dojo/lib/src ?
- not so sure about the "Mint" system, don't we just specify a supply at the creation of the contract?

**Comment by tarrencev** [comment]
amazing looking forward to it!

> * can you confirm it will be put in /dojo/lib/src ?
yes I think it can live in the lib folder

> * not so sure about the "Mint" system, don't we just specify a supply at the creation of the contract?
yeah for now lets keep it simple and not worry about `mint`
