### ISSUE TITLE
Expose order params for World__ModelConnection 

### ISSUE THREAD

**Issue by JunichiSugiura** [dojoengine/dojo#1255]
**Is your feature request related to a problem? Please describe.**
I'd like to order models by name in alphabetical order.

**Describe the solution you'd like**

```graphql
query Models {
  models(order: { field: NAME }) {
    edges {
      node {
        name
      }
    }
  }
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by gianalarcon** [comment]
I would like to take this one
