### ISSUE TITLE
Add subscription query to monitor Torii indexing/migration progress

### ISSUE THREAD

**Issue by JunichiSugiura** [dojoengine/dojo#1256]
**Is your feature request related to a problem? Please describe.**
To provide a way to rebuild world explorer's once migration is done.

**Describe the solution you'd like**
Expose subscription based on model changed events

**Describe alternatives you've considered**

**Additional context**

**Comment by broody** [comment]
Ah sorry @JunichiSugiura, I just realized @gianalarcon already implemented the subscription for model registered. This is fired any time a model is registered/updated. Can you see if this works for your usecase?

![image](https://github.com/dojoengine/dojo/assets/610224/22814d8c-4213-4dd4-89c0-fd4e06d08cea)

**Comment by ponderingdemocritus** [comment]
Still relevant @broody @JunichiSugiura ?

**Comment by broody** [comment]
Closing, I believe we're rebuilding world explorer periodically now.
