### ISSUE TITLE
World Sync

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#126]
World Sync is a feature of the Dojo toolchain which queries the world contract on starknet, retrieves the current components of the world, and reconstructs them locally in Cairo. The goal is to improve the developer experience for systems / mods.

**Comment by ponderingdemocritus** [comment]
Are you thinking we reconstruct from bytecode?

**Comment by tarrencev** [comment]
For components, we can include enough info in the implementation to allow the client to reconstruct it. I think components are the most useful to reconstruct.

https://github.com/dojoengine/dojo/blob/main/crates/dojo-lang/src/plugin_test_data/component#L84

For systems, we could store the system interface onchain, or create a implementation registry that is easy to pull from. 

For now I think handling components is a good enough first step
