### ISSUE TITLE
[BUG] updating model via register_model doesn't update db

### ISSUE THREAD

**Issue by loothero** [dojoengine/dojo#1268]
**Describe the bug**
Updating an existing model via sql.rs -> register_model does not update the model in the database.

**To Reproduce**
I have tested three variants of updating a model:
1. Overwriting an existing model with an empty set of children
    Result: The model is unchanged in the db.

2. Updating the type of an existing child of a model:
    Result: The child type is not updated in the db

3. Adding a new child to an existing model:
   Result: database error "(code: 1) no such column: external_new_children"

**Additional context**
I will push up test cases that demonstrate this bug soon

**Comment by glihm** [comment]
Hey @loothero, any update on this? Is the behavior still observed?
