### ISSUE TITLE
[sozo] migrate doesn't use profile

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1270]
**Describe the bug**
Using `sozo -P myprofile migrate` should use configuration defined under `[profile.myprofile.tool.dojo.env]` section

**To Reproduce**
Create a custom profile & sozo migrate

**Additional context**
`sozo execute` uses profile env

**Comment by lambda-0x** [comment]
looking into this

**Comment by lambda-0x** [comment]
i think `execute` don't yet support profile specific configuration, but it reads from `[tool.dojo.env]`, is that what we want to do for `migrate`?

**Comment by lambda-0x** [comment]
nvm i got confused because of this TODO: 

https://github.com/dojoengine/dojo/blob/f5d6ea0f94c39b5b8aaa4eba6fbef7e02e98118e/crates/sozo/src/commands/execute.rs#L43

I checked we don't need to do anything specific and the format you mentioned works directly with scarb.
