### ISSUE TITLE
[torii] incomplete transactions processing (missing events)

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1321]
**Is your feature request related to a problem? Please describe.**
https://github.com/dojoengine/dojo/blob/792194c1333226bbd1cec2d0aec7012d6f3a81fd/crates/torii/core/src/engine.rs#L150-L161

atm only events from Transaction(InvokeTransaction::V1 are indexed.

it should index L1HandlerTransaction) ,  other InvokeTransaction version & probably DeployTransaction too

**Comment by glihm** [comment]
Closed in favor of #1422 and will open issue for missing one once we upgrade the network version where more transaction types are available.
