### ISSUE TITLE
Add Argent & Braavos account declarations

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1328]
**Is your feature request related to a problem? Please describe.**
This could allow using katana with Argent & Braavos browser extensions

**Describe the solution you'd like**
Add Argent & Braavos contracts account declaration and check if its enough to make it work. 

## Checklist

- [x] Argent scripts (version `0.3.0` and `0.3.1`) #1579 
- [ ] Braavos

**Comment by cpp-phoenix** [comment]
Hey @notV4l, Please assign it to me

**Comment by ponderingdemocritus** [comment]
after talking with @kariy we are going to now provide script to easily deploy the hashes if the developer decides
