### ISSUE TITLE
[sozo] migrate params priority

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1336]
**Describe the bug**
sozo (migrate at least) gives priority to Scarb.toml `[tool.dojo.env]` config vs command line params (ex: `--rpc-url`)

**Expected behavior**
I think command line params should have priority over Scarb.toml `[tool.dojo.env]`

**Comment by lambda-0x** [comment]
will take this up

to be consistent with what we did for torii: https://github.com/dojoengine/dojo/pull/800, i think we should follow this priority:

```
passed cli argument
Environment variable
Scarb.toml 's dojo.tool.env
```
