### ISSUE TITLE
[Katana] Define generic trait for the execution engine

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#1342]
Define a generic trait for being generic over the execution engine implementations. This trait would be used for performing block/transaction execution during the block production stage.

Having a trait for this would allow us to implement different execution engines (ie `starknet_in_rust`, `blockifier`) that can be used in Katana. Opening up some interesting customizations as well as experimentations.

**Comment by glihm** [comment]
@kariy I will close this one as I think it was done in #1368 and it looks well integrated into `/dev/katana`. Feel free to re-open if something is missing.
