### ISSUE TITLE
[Torii-core] Handle entity deletion events properly

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#1349]
Currently, Torii is not deleting entities from internal db when a corresponding deletion event takes place onchain. 

- [ ] Implement processor to handle `StoreDelRecord` events that are generated from the world. 
https://github.com/dojoengine/dojo/tree/main/crates/torii/core/src/processors

- [ ] Delete db records from entities tables and all related model data from tables
https://github.com/dojoengine/dojo/blob/e599968f85f75e879346a789ae4d33ca8f590987/crates/torii/core/src/sql.rs#L152

**Comment by gianalarcon** [comment]
I would like to try this one
