### ISSUE TITLE
[Sozo] Better testing

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#1355]
According to [codecov](https://app.codecov.io/gh/dojoengine/dojo/tree/main/crates), the `sozo` crate seems to be one with the least amount of test coverage (a mere 30%). As we are committing into making Dojo more stable and reliable, it is important that we implement an extensive test suite for `sozo` in order to maintain compatibility and ensure it is working as expected every time changes are made in the codebase

**Comment by glihm** [comment]
@lambda-0x it's related to the issue you're on #1383.

I'll close this one to not have duplicate, I just wanted to ensure that you had the time to read @kariy message. :+1:
