### ISSUE TITLE
[Katana] Adjust account addresses for Starkli

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1357]
**Is your feature request related to a problem? Please describe.**
Starkli has some pre-defined accounts registered for Katana. This allow the user to easily work with katana by mentioning the account index (`katana-0`, `katana-1`, ...).

As we now the Katana accounts are V1 accounts, the addresses have changed (even with the seed = 0).

**Describe the solution you'd like**
Submit a PR in starkli to adjust the [built-in](https://github.com/xJonathanLEI/starkli/blob/1eb6d5d1205445416828c66a179d95fedb09d072/src/account.rs#L56) accounts for Katana once a new version of Dojo is published with the new accounts.

**Comment by coburn24** [comment]
whats brudda @glihm, hope you're doing well, thought I'd start with this one [starkli PR] (https://github.com/xJonathanLEI/starkli/pull/61)

**Comment by glihm** [comment]
Hello @coburn24 nice to see you around!

How did you get those addresses in the PR? They don't look familiar to me.

Would you mind changing your PR on starkli as a draft, as the `v0.4.4` is still using the same addresses. We should wait the `v0.4.5` in order to conclude this.

If you want to have the new addresses, please compile on main `cargo build -p katana` to have them.

Appreciate the contribution on this.

**Comment by coburn24** [comment]
@glihm I ran `dojoup` and then `katana` and got them from v4.4. thought that was it. must've overlooked something

**Comment by kariy** [comment]
Hey, @coburn24. First of all thanks for spending time contributing on this. 

A bug is found in `katana` #1404 and a fix for it results in a new set of account addresses. Do you mind updating your PR on `starkli` to reflect this new changes.

Thank you.
