### ISSUE TITLE
katana: raise the invoke steps cap `--invoke-max-steps`

### ISSUE THREAD

**Issue by moodysalem** [dojoengine/dojo#1361]
i have test transactions that need more than 2**32 steps to execute

**Comment by moodysalem** [comment]
i'm not sure if it actually takes more than 4b steps, but i am getting `RunResources has no remaining steps.` on every one of my swap integration tests. the mint/burn is working

**Comment by glihm** [comment]
@moodysalem are you still experiencing that? Sorry for the delay.
It should be not be capped on the current version, let us know if you still encounter the problem.

**Comment by glihm** [comment]
Will close for now, the max value shouldn't be capped. @moodysalem please feel free to re-open if you experience it again. :+1:
