### ISSUE TITLE
Shared state for bevy-dojo indexer game

### ISSUE THREAD

**Issue by shramee** [dojoengine/dojo#137]
- [ ] Spawn a Apibara (or mock).
- [ ] Add the plugin (#143 ) to the game.
- [ ] Get the components update from Apibara state changes.
- [ ] Write starknet-rs transaction to update state from system.

Needs #136

**Comment by ponderingdemocritus** [comment]
closing because the tasks are stale. Dojo no longer using Apibara. Open new issue for new tasks if needed
