### ISSUE TITLE
Integrate SHARP as a proof generator backend

### ISSUE THREAD

**Issue by gabe-ashe** [dojoengine/dojo#1387]
In the first version of Saya, the SHARP service from Starkware will be used to generate the proof and settle the proof on Sepolia.

This can be achieved using the `SHARP` client from [SNOS](https://github.com/keep-starknet-strange/snos) if it's enough. Or a new service may be written.

**Comment by glihm** [comment]
@neotheprogramist as mentioned, as SHARP should allow to retrieve the proof now without settling, we should add this as a backend.

1. Check with Starkware about Herodotus verifier compatibility.
2. Your work on `proof_hex` may be directly used here as SHARP may not return annotations.

**Comment by glihm** [comment]
Will close this as it's not the path we're currently taking by the lack of access to the resource.
