### ISSUE TITLE
Graphql n+1 query normalization on the server

### ISSUE THREAD

**Issue by grudich** [dojoengine/dojo#1394]

**Comment by glihm** [comment]
@Larkooo @broody I would appreciate some context on this one. To be honest I don't remember when this was added. Thanks guys.

**Comment by broody** [comment]
I believe this was something @JunichiSugiura had fixed as part of the PageInfo work, reducing the number of queries from 2 -> 1. Think we're good to close.

**Comment by glihm** [comment]
Awesome, thanks @broody!
