### ISSUE TITLE
[dev] Update Rust to the latest stable version to prevent failures in CI operations

### ISSUE THREAD

**Issue by fishseabowl** [dojoengine/dojo#1407]
Because the Rust version is outdated, there are failures in some CI operations (issue #1364). Perhaps updating Rust to the latest stable version could resolve this.

**Comment by glihm** [comment]
Hello @fishseabowl, thank you for the issue.

Here the decision to make is do we want to maintain the lowest rust stable version to ensure most compatibility or bumping to the latest stable for latest features.

I would tend to opt for maintaining the lowest rust stable rust version, which seems to be in this case `1.73.0`.

@fishseabowl @kariy @tarrencev @kariy what's your take on this?

**Comment by tarrencev** [comment]
@glihm I believe we bumped rust in the past and run into some issues. i don't recall exactly what they were. but i agree we should define the rust version explicitly and not depend on a tag like `stable` that can change unexpectedly

**Comment by fishseabowl** [comment]
@glihm @tarrencev At the moment, it seems that  `1.73.0` would ensure highest compatibility. I agree with @glihm's suggestion; we should consider upgrading to`1.73.0`. Thanks

**Comment by tarrencev** [comment]
Let's do it. Theres a few places we will need to update: https://github.com/search?q=repo:dojoengine/dojo%201.70&type=code

**Comment by kariy** [comment]
> @glihm I believe we bumped rust in the past and run into some issues. i don't recall exactly what they were.

I believe the version that we had an issue with before was 1.73.0

**Comment by glihm** [comment]
@fishseabowl are you willing to update your PR by bumping rust toolchain version and adjusting name of it?

If we update dependencies using `cargo update` the cairo dependencies may guide us to `1.74.0` from what I've seen.

**Comment by fishseabowl** [comment]
@glihm Sure.I'll update my PR by bumping rust toolchain version to `1.74.0`

**Comment by fishseabowl** [comment]
> > @glihm I believe we bumped rust in the past and run into some issues. i don't recall exactly what they were.
> 
> I believe the version that we had an issue with before was 1.73.0
> 
> Something related to the CI, though i don't exactly recall what it was.

@tarrencev @kariy I found out that commit [354eebd](https://github.com/dojoengine/dojo/commit/354eebd38525785ad670a9f08d601ed3722c00db) may be related to this issue. But I didn't find the details.

**Comment by kariy** [comment]
> @tarrencev @kariy I found out that commit [354eebd](https://github.com/dojoengine/dojo/commit/354eebd38525785ad670a9f08d601ed3722c00db) may be related to this issue. But I didn't find the details.

The issue was related to the release CI, but because we wanted to be quick, we didn't figure out exactly what caused it and just reverted back to `1.70.0`. But I believe it was just some misconfigurations.

**Comment by glihm** [comment]
Fixed by #1412.
