### ISSUE TITLE
[SOZO] e2e testing should make use of `Scarb.toml` of `spawn-and-move` example

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1414]
**Is your feature request related to a problem? Please describe.**
Currently, one can update the `Scarb.toml` of `spawn-and-move` example without impacting the `sozo` test suite. Which may then contain invalid Katana accounts for instance.

**Describe the solution you'd like**
Add a test in `sozo` that uses the scarb manifest from `spawn-and-move` example.

**Comment by stevencartavia** [comment]
Hi, is this issue still opened and is there a telegram group where I can ask questions?

**Comment by glihm** [comment]
> Hi, is this issue still opened and is there a telegram group where I can ask questions?

@stevencartavia thanks for the interest here!
We're currently revamping the tested, sorry I didn't update the status of this one, which is still pending but we're not sure of the direction to take here.

Please don't hesitate to pick an other issue you may be interested in, and thank you again for your interest into contributing. 🙏 
We should open new issues in the coming week, with more good first issues.

**Comment by stevencartavia** [comment]
No problem, thank you for the update! I will be waiting for the issues next week, thanks a lot!
