### ISSUE TITLE
[SOZO] Add a flag to support legacy encoding

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1418]
**Is your feature request related to a problem? Please describe.**
Currently, there were a lot's a requests to switch to cairo 1 accounts. However, this change is fine when `sozo` works with `katana`. But when one is working with starknet chains, some accounts are still using cairo 0. 

**Describe the solution you'd like**
Add a flag to sozo to enable legacy encoding, only when specified by the user. Default should be the new encoding.

Something like:
```
sozo migrate --legacy
```

**Comment by glihm** [comment]
@lambda-0x can I assign it to you?

**Comment by lambda-0x** [comment]
yes sir!
