### ISSUE TITLE
[Torii] Debug output of all indexed Events

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#1421]
Currently, the indexer is only console logging world events like `StoreSetRecord`, `ModelRegistered`, etc. 
![image](https://github.com/dojoengine/dojo/assets/610224/4046e5d9-8f1d-49e3-9436-4e0207390051)

During development phase, it's helpful to output all events (including custom events). May be pretty verbose so perhaps make sense to be `debug` output only.

**Comment by dubzn** [comment]
hey broody, can i try this one?
