### ISSUE TITLE
[Torii] Index more transaction types

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#1422]
As @notV4l pointed out, we're only indexing V1 invoke transactions currently. We should extend support to other transaction types like `L1HandlerTransaction` which may also contain world specific events. 

https://github.com/dojoengine/dojo/blob/3fd7f3cbe98179641bfe2eb6b4b4e0b9e23757fd/crates/torii/core/src/engine.rs#L152C20-L152C20

**Comment by jelilat** [comment]
Please assign this to me @broody
