### ISSUE TITLE
[Torii] gRPC `RetrieveEntities` endpoint to also return total count

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#1423]
The current implementation of the `RetrieveEntities` endpoint in gRPC returns only a subset of entities based on the provided `clause` query, with limit/offset pagination. This lacks an overview of the total number of entities matching the query.

Let's introduce a `total_count` field in `RetrieveEntitiesResponse`. This field should represent the total number of entities matching the clause query only.

The protobuff message definition is here:
https://github.com/dojoengine/dojo/blob/3fd7f3cbe98179641bfe2eb6b4b4e0b9e23757fd/crates/torii/grpc/proto/world.proto#L55

We would just need to implement a count query for all clause types:
https://github.com/dojoengine/dojo/blob/3fd7f3cbe98179641bfe2eb6b4b4e0b9e23757fd/crates/torii/grpc/src/server/mod.rs#L372

**Comment by gianalarcon** [comment]
Hi team, I would like to take this issue
