### ISSUE TITLE
[core] new macro to fetch by hashed value

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#1431]
There are situations when building a game where you want to keep a reference of an entity_id in another model. This entity_id is the hashed value of a model which could contain 3 or so Keys. Right now it is not possible to query by a hashed entity_id

Example:

I have a model like this:

```rust
#[derive(Model, Copy, Drop, Serde, Print)]
struct Position {
    #[key]
    game_id: u32,
    #[key]
    player: ContractAddress,
    #[key]
    squad_id: u32,
    x: u32,
    y: u32,
}
```

I want to store a reference of the hashed keys in another model like this:

```
// fetches squad id by index on hex
#[derive(Model, Copy, Drop, Serde, Print)]
struct PositionSquadEntityIdByIndex {
    #[key]
    game_id: u32,
    #[key]
    x: u32,
    #[key]
    y: u32,
    #[key]
    squad_position_index: u8,
    squad_entity_id: felt252,
}
```

This `squad_entity_id` is the hashed value saved.

I want to be able to query the `Position` model by the `squad_entity_id` NOT only by the `Position` keys. Right now this is not possible

This doesn't work:
`get!(world, (squad_entity_id), Position)`

But this works obviously:
`get!(world, (game_id, player, squad_id), Position)`

It doesn't work because the `get!` macro hashes the value again and it throws an error is the number in the tuple doesn't match the keys of the model.

## Potential solution

Introduce a new macro that does not has the value allowing this functionality. This would then allow the ability to fetch a model by the hashed value rather than the keys.

`getByHash!(world, (squad_entity_id), Position)`

**Comment by glihm** [comment]
Can see the great benefit of having the hash (`key`/`id`) of the entity being saved in other models, without having to always keep all the fields that compose a key, decoupling the key computation from the querying.

As Val mentioned in the discord, the `get!` macro uses `entity` entry point from the world which hashes the values with poseidon to re-compute the key before doing a database query. So using the database interface directly works.

For a better devex and to not rely on the user knowing poseidon, I would suggest the following:
```rust
// A first macro hides the hashing mechanism, which can evolve without breaking existing stuff.
let complex_struct = MyStruct {
    // ...
    other_entity_id: key!(game_id, player, squad_id),
}

// New macro for explicitly retrieving the entity by it's key.
let other_entity = get_by_key!(world, complex_struct.other_entity_id, Position);
```
Can this be confusing users between `key`/`id` vocabulary? Or it should be fine we consider them interchangeable? `key` sounds more `dojo` stuff, and `id` ECS related.

Doing so may have some considerations/options:
1. Directly expanding the `database::get` is no longer using the world at all.
2. Adding a new entry point to the world (`entity_by_id`?) and then expanding this instead of `entity` for the new macro.
3. The computation of the key is no longer internal to the world, which may be something intended at the beginning.

**Comment by ponderingdemocritus** [comment]
Great suggestion Sensei

Keeping everything `key` based makes logical sense in our context. 

That being said `get_by_key` doesn't quite make sense if there are multiple keys, so maybe we pluralise it to `get_by_keys` which maybe is clearer.

Perhaps the cleanest way is adding `entity_by_id` to the world interface. I'm not sure it matters where the computation happens does it?

**Comment by Doozers** [comment]
Hi, will work on this, can you assign me ? 😁

**Comment by glihm** [comment]
> Hi, will work on this, can you assign me ? 😁

Hey! Thank you for the interest in contributing. Do not hesitate if you have question on that. :+1:

**Comment by glihm** [comment]
any update on this work @Doozers?

**Comment by Doozers** [comment]
Hi @glihm ,

Sorry for the delay I'm getting familiar with the codebase,

created new get macro without the serialization here: https://github.com/dojoengine/dojo/blob/640e94d8aeadaabcb51b26704b136908a575e866/crates/dojo-lang/src/inline_macros/get.rs#L83

I'm still figuring out how I can write some semantics tests as it is done for `get` & `set`

**Comment by Doozers** [comment]
@glihm yes tbh I'm struggling to add new semantics tests

**Comment by glihm** [comment]
> @glihm yes tbh I'm struggling to add new semantics tests

So, in your case, you've a new macro to define, right?
You can take an example on how `get` and `set` are tested:

1. Add a new test file in the test data for you macro: https://github.com/dojoengine/dojo/tree/0bced71faeddebdca280cb5a95cbc9c66d9158de/crates/dojo-lang/src/semantics/test_data
2. To setup your test, you've to define some lines at the top of your new file. In those test files, you have some sections you have to write yourself, and others that are generated by the cairo runner.
    * //! > Test name
    * //! > test_runner_name
    * //! > setup_code
    * //! > expression
    In your case, the `expression` is the one you want to use with your own macro. Check inside the `get` test, you've several tests, they are separated by:
```
//! > ==========================================================================
```
3. Once you've that, you can run the command in the README:
```
CAIRO_FIX_TESTS=1 cargo test --package dojo-lang
```
This will automatically fill the expected values and diagnostics from your test data.

Do not hesitate if it's not clear with that, we can have a call on the discord if you want to. :+1:

**Comment by Doozers** [comment]
Thanks a lot for your help @glihm, to your your comment I was able to writes tests, pushed it but still draft I would like to try it with real contract, is there any documentation to how I can replace the Dojo version in a Scrab.toml so I can also try it in a local contract.

tried this but it doesn't seems to be the way.

```
[dependencies]
# dojo = { git = "https://github.com/dojoengine/dojo", version = "0.5.1" }
dojo = { path = "../dojo" }
```

**Comment by glihm** [comment]
> Thanks a lot for your help @glihm, to your your comment I was able to writes tests, pushed it but still draft I would like to try it with real contract, is there any documentation to how I can replace the Dojo version in a Scrab.toml so I can also try it in a local contract.
> 
> tried this but it doesn't seems to be the way.
> 
> ```
> [dependencies]
> # dojo = { git = "https://github.com/dojoengine/dojo", version = "0.5.1" }
> dojo = { path = "../dojo" }
> ```

Awesome!

> I would like to try it with real contract

You should directly try on the `spawn-and-move` example, where you can also add a test actually to check the macro is working at expected at a contract level.

> tried this but it doesn't seems to be the way.

You've to point to the crate `dojo-core`. So something like this should work:
```toml
dojo = { path = "../dojo/crates/dojo-core" }
``

**Comment by glihm** [comment]
This issue requires more design, as mentioned in #1662 [comment](https://github.com/dojoengine/dojo/pull/1662#pullrequestreview-1935678861).
