### ISSUE TITLE
dojo version compatible

### ISSUE THREAD

**Issue by a807966224** [dojoengine/dojo#1447]
the question is i am a newers with use dojo, and i find a project to study, but the project use dojo version is 0.3.10, when i try to use latest dojo 0.5.0 version build project, it is failed

and i have no idea to upgrade vesion with this demo project（https://github.com/cartridge-gg/beer-baron/deployments/Production%20%E2%80%93%20beer-baron）because when i change version, the project appear a lot of errors

we expect the latest version can forward compatible， if can not do this, please supply Upgrade manual , thank you ~~~

**Comment by lambda-0x** [comment]
its probably not straight forward to update the version of dojo used, but you can install an older version of dojo using `dojoup`

> dojoup --version 0.3.10

**Comment by glihm** [comment]
@a807966224 thanks for reporting this. The project were updated, and once #1533 is merged, there will be some documentation on how to update from old version to the new one.
