### ISSUE TITLE
Install Dojoup failed[BUG]

### ISSUE THREAD

**Issue by qiaopengjun5162** [dojoengine/dojo#1449]
curl -L https://install.dojoengine.org | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   104    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1497  100  1497    0     0   1175      0  0:00:01  0:00:01 --:--:--  4892
Installing dojoup...
######################################################################## 100.0%

Detected your preferred shell is zsh and added dojoup to PATH. Run 'source /Users/qiaopengjun/.zshenv' or start a new terminal session to use dojoup.
Then, simply run 'dojoup' to install Dojo.

~ via 🅒 base took 2.2s
➜
source /Users/qiaopengjun/.zshenv

dojoup

═════════════════════════════════════════════════════════════════════════

                  ██████╗  ██████╗      ██╗ ██████╗
                  ██╔══██╗██╔═══██╗     ██║██╔═══██╗
                  ██║  ██║██║   ██║     ██║██║   ██║
                  ██║  ██║██║   ██║██   ██║██║   ██║
                  ██████╔╝╚██████╔╝╚█████╔╝╚██████╔╝
                  ╚═════╝  ╚═════╝  ╚════╝  ╚═════╝

              Repo : https://github.com/dojoengine/dojo
              Book : https://book.dojoengine.org/
              Chat : https://discord.gg/dojoengine
                     https://t.me/dojoengine

═════════════════════════════════════════════════════════════════════════

dojoup: installing dojo (version , tag )
https://github.com/dojoengine/dojo/releases/download//dojo__darwin_arm64.tar.gz
dojoup: downloading latest dojo
########################################################################################################################################################## 100.0%
tar: Error opening archive: Unrecognized archive format
dojoup: command failed: tar -xzC /Users/qiaopengjun/.dojo/bin
/Users/qiaopengjun/.dojo/bin/dojoup: line 251: /Users/qiaopengjun/.dojo/bin/katana: No such file or directory
dojoup: command failed: /Users/qiaopengjun/.dojo/bin/katana --version
dojoup: installed -
dojoup: warning:
There are multiple binaries with the name 'katana' present in your 'PATH'.
This may be the result of installing 'katana' using another method,
like Cargo or other package managers.
You may need to run 'rm ' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

/Users/qiaopengjun/.dojo/bin/dojoup: line 251: /Users/qiaopengjun/.dojo/bin/sozo: No such file or directory
dojoup: command failed: /Users/qiaopengjun/.dojo/bin/sozo --version
dojoup: installed -
dojoup: warning:
There are multiple binaries with the name 'sozo' present in your 'PATH'.
This may be the result of installing 'sozo' using another method,
like Cargo or other package managers.
You may need to run 'rm ' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

/Users/qiaopengjun/.dojo/bin/dojoup: line 251: /Users/qiaopengjun/.dojo/bin/torii: No such file or directory
dojoup: command failed: /Users/qiaopengjun/.dojo/bin/torii --version
dojoup: installed -
dojoup: warning:
There are multiple binaries with the name 'torii' present in your 'PATH'.
This may be the result of installing 'torii' using another method,
like Cargo or other package managers.
You may need to run 'rm ' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

/Users/qiaopengjun/.dojo/bin/dojoup: line 251: /Users/qiaopengjun/.dojo/bin/dojo-language-server: No such file or directory
dojoup: command failed: /Users/qiaopengjun/.dojo/bin/dojo-language-server --version
dojoup: installed -
dojoup: warning:
There are multiple binaries with the name 'dojo-language-server' present in your 'PATH'.
This may be the result of installing 'dojo-language-server' using another method,
like Cargo or other package managers.
You may need to run 'rm ' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

dojoup: done!

mac pro 16  m2

**Comment by lambda-0x** [comment]
seems like `dojoup` able to properly fetch version of dojo to install. 

please try running the below command one by one and see where its failing:
```bash
curl -s "https://api.github.com/repos/dojoengine/dojo/releases" \
        | grep -oE '"tag_name": "[^"]*"|"prerelease": (true|false)' \
        | grep -B1 '"prerelease": false' \
        | grep '"tag_name":' \
        | grep -oE '"v[0-9]*\.[0-9]*\.[0-9]*"' \
        | tr -d '"' \
        | head -n 1
```

**Comment by lambda-0x** [comment]
or alternatively run this script and show us the output.

its the same command as above but split out to make it easy for you.

```bash
#!/bin/bash

# Command 1
output1=$(curl -s "https://api.github.com/repos/dojoengine/dojo/releases")

# Print and store the output
echo "Command 1 Output:"
echo "$output1"

# Command 2
output2=$(echo "$output1" | grep -oE '"tag_name": "[^"]*"|"prerelease": (true|false)')

# Print and store the output
echo -e "\nCommand 2 Output:"
echo "$output2"

# Command 3
output3=$(echo "$output2" | grep -B1 '"prerelease": false')

# Print and store the output
echo -e "\nCommand 3 Output:"
echo "$output3"

# Command 4
output4=$(echo "$output3" | grep '"tag_name":')

# Print and store the output
echo -e "\nCommand 4 Output:"
echo "$output4"

# Command 5
output5=$(echo "$output4" | grep -oE '"v[0-9]*\.[0-9]*\.[0-9]*"')

# Print and store the output
echo -e "\nCommand 5 Output:"
echo "$output5"

# Command 6
final_output=$(echo "$output5" | tr -d '"' | head -n 1)

# Print the final output
echo -e "\nFinal Output:"
echo "$final_output"
```

**Comment by qiaopengjun5162** [comment]
![image](https://github.com/dojoengine/dojo/assets/124650229/d6637942-ba46-4c98-bd19-8b3251b349a5)

**Comment by qiaopengjun5162** [comment]
dojoup


═════════════════════════════════════════════════════════════════════════


                  ██████╗  ██████╗      ██╗ ██████╗
                  ██╔══██╗██╔═══██╗     ██║██╔═══██╗
                  ██║  ██║██║   ██║     ██║██║   ██║
                  ██║  ██║██║   ██║██   ██║██║   ██║
                  ██████╔╝╚██████╔╝╚█████╔╝╚██████╔╝
                  ╚═════╝  ╚═════╝  ╚════╝  ╚═════╝


              Repo : https://github.com/dojoengine/dojo
              Book : https://book.dojoengine.org/
              Chat : https://discord.gg/dojoengine
                     https://t.me/dojoengine

═════════════════════════════════════════════════════════════════════════

dojoup: installing dojo (version , tag )
https://github.com/dojoengine/dojo/releases/download//dojo__darwin_arm64.tar.gz
dojoup: downloading latest dojo
########################################################################################################################################################## 100.0%
tar: Error opening archive: Unrecognized archive format
dojoup: command failed: tar -xzC /Users/qiaopengjun/.dojo/bin
/Users/qiaopengjun/.dojo/bin/dojoup: line 251: /Users/qiaopengjun/.dojo/bin/katana: No such file or directory
dojoup: command failed: /Users/qiaopengjun/.dojo/bin/katana --version
dojoup: installed -
dojoup: warning:
There are multiple binaries with the name 'katana' present in your 'PATH'.
This may be the result of installing 'katana' using another method,
like Cargo or other package managers.
You may need to run 'rm ' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

/Users/qiaopengjun/.dojo/bin/dojoup: line 251: /Users/qiaopengjun/.dojo/bin/sozo: No such file or directory
dojoup: command failed: /Users/qiaopengjun/.dojo/bin/sozo --version
dojoup: installed -
dojoup: warning:
There are multiple binaries with the name 'sozo' present in your 'PATH'.
This may be the result of installing 'sozo' using another method,
like Cargo or other package managers.
You may need to run 'rm ' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

/Users/qiaopengjun/.dojo/bin/dojoup: line 251: /Users/qiaopengjun/.dojo/bin/torii: No such file or directory
dojoup: command failed: /Users/qiaopengjun/.dojo/bin/torii --version
dojoup: installed -
dojoup: warning:
There are multiple binaries with the name 'torii' present in your 'PATH'.
This may be the result of installing 'torii' using another method,
like Cargo or other package managers.
You may need to run 'rm ' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

/Users/qiaopengjun/.dojo/bin/dojoup: line 251: /Users/qiaopengjun/.dojo/bin/dojo-language-server: No such file or directory
dojoup: command failed: /Users/qiaopengjun/.dojo/bin/dojo-language-server --version
dojoup: installed -
dojoup: warning:
There are multiple binaries with the name 'dojo-language-server' present in your 'PATH'.
This may be the result of installing 'dojo-language-server' using another method,
like Cargo or other package managers.
You may need to run 'rm ' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

dojoup: done!

**Comment by lambda-0x** [comment]
> ![image](https://private-user-images.githubusercontent.com/124650229/297575532-d6637942-ba46-4c98-bd19-8b3251b349a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTAzMzgsIm5iZiI6MTcwNTU1MDAzOCwicGF0aCI6Ii8xMjQ2NTAyMjkvMjk3NTc1NTMyLWQ2NjM3OTQyLWJhNDYtNGM5OC1iZDE5LThiMzI1MWIzNDlhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwMzUzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjBhMGUwYTE2NmQyZmFlZDEyZjk2ODgyMDNlZDNhNzA3NDMwNjE3MjJkNzA0NWMzNTk5ZDA0NDUzN2Q3NTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.grtVAcj8Nkvfa006owO5ce9tNuCvtygy3FVeBTZeCqs)

yeah that is not working as expected.

Can you run this script and provide its output: https://github.com/dojoengine/dojo/issues/1449#issuecomment-1896289146

**Comment by qiaopengjun5162** [comment]
bash Code/cairo/dojo_script.sh

Command 2 Output:
"tag_name": "v0.5.1-alpha.0"
"prerelease": false
"tag_name": "v0.5.0"
"prerelease": false
"tag_name": "v0.4.4"
"prerelease": false
"tag_name": "v0.4.3"
"prerelease": false
"tag_name": "v0.4.2"
"prerelease": false
"tag_name": "v0.4.1"
"prerelease": false
"tag_name": "v0.4.0-rc2"
"prerelease": false
"tag_name": "v0.4.0"
"prerelease": false
"tag_name": "v0.4.0-rc1"
"prerelease": false
"tag_name": "v0.4.0-rc0"
"prerelease": false
"tag_name": "v0.3.15"
"prerelease": false
"tag_name": "nightly-96c6edc58cb8b48c6875c77d39f665ac14b80ef3"
"prerelease": true
"tag_name": "nightly-6dd5d12529c927ca9ad744f5979a92ef19dd0816"
"prerelease": true
"tag_name": "v0.3.14"
"prerelease": false
"tag_name": "v0.3.13"
"prerelease": false
"tag_name": "v0.3.12"
"prerelease": false
"tag_name": "v0.3.11"
"prerelease": false
"tag_name": "v0.3.10"
"prerelease": false
"tag_name": "v0.3.9"
"prerelease": false
"tag_name": "v0.3.8"
"prerelease": false
"tag_name": "v0.3.7"
"prerelease": false
"tag_name": "v0.3.6"
"prerelease": false
"tag_name": "v0.3.5"
"prerelease": false
"tag_name": "v0.3.4"
"prerelease": false
"tag_name": "v0.3.3"
"prerelease": false
"tag_name": "v0.3.2"
"prerelease": false
"tag_name": "v0.3.1"
"prerelease": false
"tag_name": "v0.3.0"
"prerelease": false
"tag_name": "v0.3.0-rc9"
"prerelease": false
"tag_name": "v0.3.0-rc8"
"prerelease": false

Command 3 Output:
"tag_name": "v0.5.1-alpha.0"
"prerelease": false
"tag_name": "v0.5.0"
"prerelease": false
"tag_name": "v0.4.4"
"prerelease": false
"tag_name": "v0.4.3"
"prerelease": false
"tag_name": "v0.4.2"
"prerelease": false
"tag_name": "v0.4.1"
"prerelease": false
"tag_name": "v0.4.0-rc2"
"prerelease": false
"tag_name": "v0.4.0"
"prerelease": false
"tag_name": "v0.4.0-rc1"
"prerelease": false
"tag_name": "v0.4.0-rc0"
"prerelease": false
"tag_name": "v0.3.15"
"prerelease": false
--
"tag_name": "v0.3.14"
"prerelease": false
"tag_name": "v0.3.13"
"prerelease": false
"tag_name": "v0.3.12"
"prerelease": false
"tag_name": "v0.3.11"
"prerelease": false
"tag_name": "v0.3.10"
"prerelease": false
"tag_name": "v0.3.9"
"prerelease": false
"tag_name": "v0.3.8"
"prerelease": false
"tag_name": "v0.3.7"
"prerelease": false
"tag_name": "v0.3.6"
"prerelease": false
"tag_name": "v0.3.5"
"prerelease": false
"tag_name": "v0.3.4"
"prerelease": false
"tag_name": "v0.3.3"
"prerelease": false
"tag_name": "v0.3.2"
"prerelease": false
"tag_name": "v0.3.1"
"prerelease": false
"tag_name": "v0.3.0"
"prerelease": false
"tag_name": "v0.3.0-rc9"
"prerelease": false
"tag_name": "v0.3.0-rc8"
"prerelease": false

Command 4 Output:
"tag_name": "v0.5.1-alpha.0"
"tag_name": "v0.5.0"
"tag_name": "v0.4.4"
"tag_name": "v0.4.3"
"tag_name": "v0.4.2"
"tag_name": "v0.4.1"
"tag_name": "v0.4.0-rc2"
"tag_name": "v0.4.0"
"tag_name": "v0.4.0-rc1"
"tag_name": "v0.4.0-rc0"
"tag_name": "v0.3.15"
"tag_name": "v0.3.14"
"tag_name": "v0.3.13"
"tag_name": "v0.3.12"
"tag_name": "v0.3.11"
"tag_name": "v0.3.10"
"tag_name": "v0.3.9"
"tag_name": "v0.3.8"
"tag_name": "v0.3.7"
"tag_name": "v0.3.6"
"tag_name": "v0.3.5"
"tag_name": "v0.3.4"
"tag_name": "v0.3.3"
"tag_name": "v0.3.2"
"tag_name": "v0.3.1"
"tag_name": "v0.3.0"
"tag_name": "v0.3.0-rc9"
"tag_name": "v0.3.0-rc8"

Command 5 Output:
"v0.5.0"
"v0.4.4"
"v0.4.3"
"v0.4.2"
"v0.4.1"
"v0.4.0"
"v0.3.15"
"v0.3.14"
"v0.3.13"
"v0.3.12"
"v0.3.11"
"v0.3.10"
"v0.3.9"
"v0.3.8"
"v0.3.7"
"v0.3.6"
"v0.3.5"
"v0.3.4"
"v0.3.3"
"v0.3.2"
"v0.3.1"
"v0.3.0"

Final Output:
v0.5.0

**Comment by lambda-0x** [comment]
weird, here its working as expected. please try doing a clean install of `dojoup` after removing everything thats in PATH as suggested in the error:

> There are multiple binaries with the name 'dojo-language-server' present in your 'PATH'.
This may be the result of installing 'dojo-language-server' using another method,
like Cargo or other package managers.
You may need to run 'rm ' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

**Comment by qiaopengjun5162** [comment]
I don't know the reason for the failure。But the problem has been solved。

First, run this command：
```shell
cargo install --git https://github.com/dojoengine/dojo --force sozo katana torii
```
Running results：
```shell
...
  Installing /Users/qiaopengjun/.cargo/bin/katana
   Installed package `katana v0.5.1-alpha.0 (https://github.com/dojoengine/dojo#cd410f99)` (executable `katana`)
     Summary Successfully installed sozo, katana! Failed to install torii (see error(s) above).
error: some crates failed to install
```

Then execute this command：
```shell
dojoup
```

Running results
```shell


═════════════════════════════════════════════════════════════════════════


                  ██████╗  ██████╗      ██╗ ██████╗
                  ██╔══██╗██╔═══██╗     ██║██╔═══██╗
                  ██║  ██║██║   ██║     ██║██║   ██║
                  ██║  ██║██║   ██║██   ██║██║   ██║
                  ██████╔╝╚██████╔╝╚█████╔╝╚██████╔╝
                  ╚═════╝  ╚═════╝  ╚════╝  ╚═════╝


              Repo : https://github.com/dojoengine/dojo
              Book : https://book.dojoengine.org/
              Chat : https://discord.gg/dojoengine
                     https://t.me/dojoengine

═════════════════════════════════════════════════════════════════════════

dojoup: installing dojo (version v0.5.0, tag v0.5.0)
https://github.com/dojoengine/dojo/releases/download/v0.5.0/dojo_v0.5.0_darwin_arm64.tar.gz
dojoup: downloading latest dojo
########################################################################################################################################################## 100.0%
dojoup: installed - katana 0.5.0
dojoup: warning:
There are multiple binaries with the name 'katana' present in your 'PATH'.
This may be the result of installing 'katana' using another method,
like Cargo or other package managers.
You may need to run 'rm /Users/qiaopengjun/.cargo/bin/katana' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

dojoup: installed - sozo 0.5.0
dojoup: warning:
There are multiple binaries with the name 'sozo' present in your 'PATH'.
This may be the result of installing 'sozo' using another method,
like Cargo or other package managers.
You may need to run 'rm /Users/qiaopengjun/.cargo/bin/sozo' or move '/Users/qiaopengjun/.dojo/bin'
in your 'PATH' to allow the newly installed version to take precedence!

dojoup: installed - torii 0.5.0
dojoup: installed - dojo-language-server 0.5.0
dojoup: done!
```

Successfully solved the problem！
```shell
sozo init


 ⛩️ ====== STARTING ====== ⛩️

Setting up project directory tree...
Cloning project template from https://github.com/dojoengine/dojo-starter...

🎉 Successfully created a new ⛩️ Dojo project!

====== SETUP COMPLETE! ======


To start using your new project, try running: `sozo build`
```

**Comment by lambda-0x** [comment]
you either need to install using `cargo install` or `dojoup`. you where probably getting that error because of using both of them.
