### ISSUE TITLE
[sozo] Migrating from 0.3.13 to 0.5 breaks retro-compatibility

### ISSUE THREAD

**Issue by wraitii** [dojoengine/dojo#1463]
**Describe the bug**
Running `sozo migrate` on an existing world (`0x1ea16366a82e211a9b9045725309a5080c0260d5caf45c58836fc61b42501f5`) does not work as expected.

**To Reproduce**
Deploy a world using Sozo 0.3.13, then update to 0.5 and run `sozo migrate`

**Expected behavior**
The world contract should upgrade in place. Instead, `sozo migrate` deploys a new world.

Contracts (& models) should upgrade in place.
However, there have been some changes that prevent this:
- Contract deployment salt uses the base contract class-hash, which has changed (not sure if that's just for me)
- Contract deployment salt uses the contract name, which has changed: it is now fully qualified (`briq_protocol::tokens::box_nft_sp::box_nft_sp`) when it wasn't before (`box_nft_sp`)
- not sure exactly for models but I would expect problems there too.

Changing `generate_salt` and manually updating the manifest.json base class hash fixes the issue.

**Comment by glihm** [comment]
Thanks for this report @wraitii and we have several level to consider to ensure smooth migration with backward compatibility.

Currently revamping the manifest format and migration process, we should be able to handle all those cases.
1. Constant base class hash for world's address computation (which will allow Sozo to upgrade the world in place).
2. As you mentioned in a conversation we had, a base class hash will be specified for each contract, to ensure correct in-place migration if desired.
3. The models are being re-worked with a versioning, in which the compiler will generate different code to handle the names / new selector of the models to ensure storage compatibility.

Will keep this issue open, once we ensure backward compatibility is handled correctly.

**Comment by glihm** [comment]
This should be addressed in #1671.
