### ISSUE TITLE
Add fork provider for non-state data

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#1466]
Currently `katana` only provides forked data for state-related info (eg storage, nonce, class hash) thru the [`SharedStateProvider`](https://github.com/dojoengine/dojo/blob/79278a62f66895cbe3bfaf822e3703309f8847b5/crates/katana/storage/provider/src/providers/fork/state.rs#L15). We should extend the forking functionality to also allow fetching non-state data as well (eg block, events, tx) from the forked network.

We can extend the [`Backend`](https://github.com/dojoengine/dojo/blob/79278a62f66895cbe3bfaf822e3703309f8847b5/crates/katana/storage/provider/src/providers/fork/backend.rs#L71) to handle more [request types](https://github.com/dojoengine/dojo/blob/79278a62f66895cbe3bfaf822e3703309f8847b5/crates/katana/storage/provider/src/providers/fork/backend.rs#L58).

## Proposed solution

We can mimic [`ForkedStateDb`](https://github.com/dojoengine/dojo/blob/118ed84f7b5cb9e4e0c1963fca88b71a222ae50d/crates/katana/storage/provider/src/providers/fork/state.rs#L15) where it uses [`SharedStateProvider`](https://github.com/dojoengine/dojo/blob/118ed84f7b5cb9e4e0c1963fca88b71a222ae50d/crates/katana/storage/provider/src/providers/fork/backend.rs#L324) as the underlying db for [`CacheStateDb`](https://github.com/dojoengine/dojo/blob/118ed84f7b5cb9e4e0c1963fca88b71a222ae50d/crates/katana/storage/provider/src/providers/in_memory/cache.rs#L35) by creating similar _forked provider type_ specifically for the [`CacheDb`](https://github.com/dojoengine/dojo/blob/118ed84f7b5cb9e4e0c1963fca88b71a222ae50d/crates/katana/storage/provider/src/providers/in_memory/cache.rs#L73) instead, that handles non-state data (ie block, tx). Unlike `SharedStateProvider`, we don't have to implement the provider traits as most of the traits are mainly for abstracting over the db layout. We only need to fetch data that can only be fetched from the RPC. So, that means we only need to implement fork handlers for data that can only be obtain from the Katana RPC.

Regarding caching (ie storing the fetch forked data into local storage), ideally we can store the fetched data directly into the main storage, but how the storage is laid out at the moment isn't very friendly to unordered insertion like this case. Maybe we can have the _forked provider type_ to include a storage to store the data fetched from the forked RPC.

**Comment by fishseabowl** [comment]
@kariy can I take this? Thanks

**Comment by kariy** [comment]
Assigned! Let me know if you have any questions or require more context on the issue.

**Comment by kariy** [comment]
@fishseabowl I've updated the issue description for more context. Thanks for the contribution 🙂

**Comment by kariy** [comment]
Hey @fishseabowl. Any updates on this?

**Comment by fishseabowl** [comment]
@kariy Thank you. I'm currently handling this. If I have any questions, I'll message you.

**Comment by fishseabowl** [comment]
@kariy Do you know where is a code example using the starknet-provider API, e.g. if I call API `get_events`, what are the parameters `filter` and `chunk_size`? Thanks
```rust
/// Returns all events matching the given filter
    async fn get_events(
        &self,
        filter: EventFilter,
        continuation_token: Option<String>,
        chunk_size: u64,
    ) -> Result<EventsPage, ProviderError>;
```

**Comment by kariy** [comment]
@fishseabowl I'm not sure about the example but you can refer to the RPC specs [here](https://github.com/starkware-libs/starknet-specs/blob/49665932a97f8fdef7ac5869755d2858c5e3a687/api/starknet_api_openrpc.json#L769) to know what each of the params are used for.

**Comment by glihm** [comment]
> @kariy Do you know where is a code example using the starknet-provider API, e.g. if I call API `get_events`, what are the parameters `filter` and `chunk_size`? Thanks
> 
> ```rust
> /// Returns all events matching the given filter
>     async fn get_events(
>         &self,
>         filter: EventFilter,
>         continuation_token: Option<String>,
>         chunk_size: u64,
>     ) -> Result<EventsPage, ProviderError>;
> ```

Some example of code from starknet-rs @fishseabowl: https://github.com/xJonathanLEI/starknet-rs/blob/400deb6f058447e8b67316a92ecd9ad3b6d4330c/starknet-providers/tests/jsonrpc.rs#L795.

The chunk size is expected to be `None` where no more data have to be fetched. You can see the fetching as paginated using this continuation token.
