### ISSUE TITLE
[SOZO] migrate plan/dry_run does nothing

### ISSUE THREAD

**Issue by lambda-0x** [dojoengine/dojo#1468]
when this is true sozo should perform a dry run of migration but currently its not being used.

https://github.com/dojoengine/dojo/blob/79278a62f66895cbe3bfaf822e3703309f8847b5/crates/sozo/src/commands/migrate.rs#L15-L17

-------------------------
#Edit

To tackle this issue, the idea is would be to introduce the `dry-run` flag in the `ops` related to migration [here in sozo](https://github.com/dojoengine/dojo/blob/68e81f65df92837cffcdd4f0b498a3b71edb55a9/bin/sozo/src/ops/migration/mod.rs#L277).

By having the `dry-run` passed as argument during the migration, `sozo` could output the operations, without actually doing them.

**Comment by faytey** [comment]
can i take this

**Comment by ameya-deshmukh** [comment]
Hey @lambda-0x can I take this up?

**Comment by glihm** [comment]
> can i take this

Hey @faytey for sure, do you have an idea how to start working on this? Don't hesitate if you have questions.

@ameya-deshmukh thank you for your will to contribute. For the sake of order I'll assign to @faytey, hopefully there's a new issue you feel comfortable with.

Except if @faytey prefer to work on something else.

Appreciate your comprehension. :+1:

**Comment by faytey** [comment]
Thank you @glihm  i'd take it up, please i'd appreciate a clearer context thanks

**Comment by glihm** [comment]
> Thank you @glihm i'd take it up, please i'd appreciate a clearer context thanks

Yup for sure. `sozo` is using `dojo-world` crate to get the migration strategy that contains everything that should be done:
https://github.com/dojoengine/dojo/blob/64992c9ce2ca941ccdde91acea222725f13ed7f7/bin/sozo/src/ops/migration/mod.rs#L132

This strategy is the one being executed:
https://github.com/dojoengine/dojo/blob/64992c9ce2ca941ccdde91acea222725f13ed7f7/bin/sozo/src/ops/migration/mod.rs#L136

In the dry mode `sozo` should output the strategy to be executed, without actually executing it.

So the task here would be you to implement a print function that pretty print the strategy that `sozo` would execute without the `--dry-run` option.

Sounds good to you?

**Comment by faytey** [comment]
@glihm hello glihm, i'm sorry i tried working on this but realized it's written in rust and sought for help from a dojo dev but my issue is that I can't meet up with the odhacks deadline, would you want to assign this to someone else more skilled or can i get extra time to solve it.

**Comment by glihm** [comment]
> @glihm hello glihm, i'm sorry i tried working on this but realized it's written in rust and sought for help from a dojo dev but my issue is that I can't meet up with the odhacks deadline, would you want to assign this to someone else more skilled or can i get extra time to solve it.

Sounds good, no problem and thank you for the feedback. Don't hesitate if in the future you see some issue you want to tackle. :+1:

**Comment by glihm** [comment]
> Hey @lambda-0x can I take this up?

@ameya-deshmukh you still available for this one?

**Comment by ameya-deshmukh** [comment]
Yep!

**Comment by glihm** [comment]
@ameya-deshmukh how are you doing with this issue? Any update?

**Comment by ameya-deshmukh** [comment]
Hey @glihm! Can you give me till this weekend to open a PR? Thanks!

**Comment by glihm** [comment]
> Hey @glihm! Can you give me till this weekend to open a PR? Thanks!

No problem at all, and no pressure. :)
Best of luck for the week and don’t hesitate is you have questions.

**Comment by glihm** [comment]
@ameya-deshmukh are you still interested with this issue, or we can take over?

**Comment by ameya-deshmukh** [comment]
@glihm wasn't able to devote a lot of time to this unfortunately :(
You can take it up! Will hopefully have many more opportunities to contribute to Dojo in the future :D

**Comment by remybar** [comment]
can I work on it ?

**Comment by glihm** [comment]
> can I work on it ?

Let's do it, thanks @remybar. :rocket:
