### ISSUE TITLE
[core]: Improve language server

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#1476]
Currently the language server is not feature complete with the current Cairo version. It works, but is not ideal.

This leads to blind programming with bugs only being found after running a build. I have noticed a trend of avoiding using dojo::contracts because of this issue. Not ideal.

The language server should be inline with the Cairo language server to give the best devx.

**Comment by glihm** [comment]
IIRC we are coupled with Scarb for this. Will put the blocked tag until we have it unlocked by a Scarb upgrade.

**Comment by glihm** [comment]
Blocked now by #1659.
