### ISSUE TITLE
[Katana] Allow dev accounts to be allocated from the JSON file

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#1496]
Currently, the initialization of Katana genesis state #1472 from the [JSON format](https://github.com/dojoengine/dojo/blob/d9ef75507b9f960aa385bc122482ceaf725eb558/crates/katana/primitives/src/genesis/json.rs#L133) is limited to only allocating [non-dev accounts](https://github.com/dojoengine/dojo/blob/d9ef75507b9f960aa385bc122482ceaf725eb558/crates/katana/primitives/src/genesis/allocation.rs#L179) (ie. accounts where the private key isn't included in the genesis config and thus not displayed in the startup title) but I think we should gives the flexibility for both types of genesis accounts to be constructed from the JSON file. The definition for dev account type is located [here](https://github.com/dojoengine/dojo/blob/d9ef75507b9f960aa385bc122482ceaf725eb558/crates/katana/primitives/src/genesis/allocation.rs#L145).

**Comment by fishseabowl** [comment]
@kariy can I take this?

**Comment by kariy** [comment]
Assigned
