### ISSUE TITLE
[Saya] Configuration file

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1504]
Saya was introduced in this #1495.

As Saya will grow, the configuration will become more complex as Saya have those components:
1. Data availability layers, where a node URL + some custom configuration may apply.
2. Prover configuration.
3. Verifier and settlement layer configuration.

This issues aims at providing an alternative solution to initialize Saya with bunch of CLI arguments.

The format for this file may be JSON, inspired from what was done for the [genesis file](https://github.com/dojoengine/dojo/blob/main/crates/katana/primitives/src/genesis/test-genesis.json) of Katana.

```json
{
  "data_availability": {
    "celestia": {
      "node_url": "https://...",
      "auth_token": "ecYk....",
      "namespace": "mynm",
    }
  },
  "prover": {
    "sharp": {
      "service_url": "https://....",
      "token": "....",
    }
  },
}
```
To enable the use of this configuration file, an option should be added in the Saya binary `bin/saya/args`.

**Comment by Jonatan-Chaverri** [comment]
@glihm please assign this issue to me. Thanks.

**Comment by Jonatan-Chaverri** [comment]
@glihm I think we can close this. Thanks for your help on the PR and feedback.
