### ISSUE TITLE
[BUG] create-components script fails to run for v0.5.1-alpha.2

### ISSUE THREAD

**Issue by 0xtechnoir** [dojoengine/dojo#1511]
**Describe the bug**
Get the following error when trying to run create-components script
`error: could not determine executable to run for package @dojoengine/core`

**To Reproduce**
upgrade dojo to v0.5.1-alpha.2
try run the create-components script from the client directory

**Expected behavior**
Should regenerate the contractComponents.ts file

**Screenshots**
<img width="827" alt="Screenshot 2024-02-02 at 10 22 45 AM" src="https://github.com/dojoengine/dojo/assets/36206067/3f1c95a2-3edf-4b45-941d-ed57b808d8af">

**Additional context**

**Comment by glihm** [comment]
@ponderingdemocritus should it be for `dojo.js` repo?
