### ISSUE TITLE
[torii] Subscribe to custom events over gRPC

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#1517]
**Is your feature request related to a problem? Please describe.**
Currently torii-client does not stream custom events. 

**Describe the solution you'd like**
When custom events are emmitted, they should stream to torii-client. This would then allow custom buisness logic on the client side to handle them.

A user should be able to subscribe using an array of event names, and then receive all these when they are emitted.

**Comment by glihm** [comment]
Similar to #1420.

**Comment by glihm** [comment]
#1420 was closed as completed, @ponderingdemocritus feel free to re-open if not fixed. :+1:
