### ISSUE TITLE
Add Crawler example to demonstrate player's movement

### ISSUE THREAD

**Issue by JunichiSugiura** [dojoengine/dojo#153]
Spawn 1 player and move around in a 2D grid.

### Resources

- [Components](https://github.com/dojoengine/dojo/blob/main/examples/src/components.cairo#L3..L12)
- [Systems](https://github.com/dojoengine/dojo/blob/main/examples/src/systems.cairo)
- [Starknet Devnet - Docker image](https://hub.docker.com/layers/shardlabs/starknet-devnet/latest-arm-seed0/images/sha256-0e5310cfd87112f630ae2c093703f6689bdb2cceeed05314f0e5802df72c70b7?context=explore)
  - `docker run -p 127.0.0.1:5050:5050 shardlabs/starknet-devnet:latest-arm-seed0`

**Comment by ponderingdemocritus** [comment]
closing for now
