### ISSUE TITLE
[katana] isolate `dev` JSON RPC API from `katana` impl

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1537]
**Is your feature request related to a problem? Please describe.**
Currently, to enable the `katana` JSON RPC namespace, the `--dev` option must be given: https://github.com/dojoengine/dojo/blob/68e81f65df92837cffcdd4f0b498a3b71edb55a9/bin/katana/src/args.rs#L218.
It is thus impossible to add useful endpoints to the `katana` namespace without using the `--dev` options.

**Describe the solution you'd like**
We wish to introduce a new `ApiKind::Dev` to support dev only endpoints that are meant for development, and at the same time reusing `ApiKind::Katana` for endpoints that should be exposed even when not in `--dev` mode.

**Additional context**
This issue aims at implementing a new `ApiKind::Dev` with all current endpoints found under `ApiKind::Katana`. Move all the endpoints under `katana` namespace (except for `predeployedAccounts`) to this new `dev` namespace.

To achieve that, you have to follow the architecture propose into `katana/rpc` where:
1. `katana/rpc/rpc-api` defines the method and it's namespace, create a new namespace called `dev`.
2. The implementation must go under `katana/rpc/rpc`. 
3. No new types should be introduced into `katana/rpc/rpc-types` for now.

You can take example on how `starknet` and `katana` are separated.

**Comment by makluganteng** [comment]
Can take this ?

**Comment by kariy** [comment]
Assigned! I've modified the issue description a lil bit. Thanks

**Comment by kariy** [comment]
Resolved in #1544
