### ISSUE TITLE
[sozo] move the `ops` module to the `sozo` crate

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1538]
**Is your feature request related to a problem? Please describe.**
A recent rework of the repository has moved the binaries to the `bin` directory. However, `sozo` remains too monolithic and should be split between `bin` and `crate`.

**Describe the solution you'd like**
Move the `ops` module from `bin/sozo/src/ops` to it's own crate under `crates/sozo/ops`.

**Comment by Jonatan-Chaverri** [comment]
@glihm can you please assign this to me, I'm working on it. Thanks.
