### ISSUE TITLE
Use felt type from `starknet-types-core` crate

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#1539]
replace the `FieldElement` type in katana with `Felt` from [starknet-types-core](https://docs.rs/starknet-types-core/0.0.9/starknet_types_core/) crate

**Comment by glihm** [comment]
Blocked until `starknet-rs` releases a version with such types. They are already integrated in `Starknet-api` though.

**Comment by glihm** [comment]
Merged already in the `1.0.0-alpha.0` release #2126.
