### ISSUE TITLE
Improvements and Error Handling in Gas Usage Parsing

### ISSUE THREAD

**Issue by g4titan** [dojoengine/dojo#1541]
### Description
I made several improvements to the gas usage parsing functionality in the `main.rs` file:
- Implemented proper error handling for file opening, line reading, and gas value parsing.
- Updated imports to use the `fs` module for file operations and improved code readability.
- Added error messages for invalid formats and continued processing subsequent lines on errors.
- Refactored code to use `entry` for better HashMap manipulation and removed unnecessary clones.

### Fixes
- Fixed error handling in gas value parsing.
- Fixed incorrect handling of gas value formats.
- Fixed file handling errors causing program termination.

**Comment by glihm** [comment]
Hey @g4titan, thank you for this. Related PR #1548 was closed for the same reason that the benchmark crate is a tool that will evolve and there's no major benefit modifying it as describe in this issue.
If you have any question don't hesitate to comment, and thank you again for considering contributing! Do not hesitate to check open issues. :+1:
