### ISSUE TITLE
[BUG] Derive `Introspect` doesn't work with enum with u64 .

### ISSUE THREAD

**Issue by zsluedem** [dojoengine/dojo#1547]
**Describe the bug**

Derive `Introspect` doesn't work with enum with u64 .

**To Reproduce**

```cairo
[derive(Drop, Introspect, Copy, Serde)]
enum BuildingId{
    a: u64,
    b: u64
}
```

```
sozo build 
```

with error
```
error: Plugin diagnostic: Trait has no implementation in context: dojo::database::introspect::Introspect::<core::integer::u64>
 --> some.cairo[BuildingId]:25:73
                        @dojo::database::introspect::Introspect::<u64>::ty()
                                                                        ^^


error: Compilation failed.

```
**Expected behavior**

build should work

**Screenshots**

**Additional context**

**Comment by glihm** [comment]
Hey @zsluedem, thank you very much for this good catch.
Revising the code, it seems to be here:
https://github.com/dojoengine/dojo/blob/ca3b018048ddbeaa3a78c8287143ba526e0f89a0/crates/dojo-lang/src/introspect.rs#L135-L144
Were we should be checking (as we do for struct members) if the type if a primitive or not.

Would you like to fix it? Feel free to ask any question.

**Comment by g4titan** [comment]
hello @glihm, assign this task to me

**Comment by glihm** [comment]
> hello @glihm, assign this task to me

Let's do it! Thank you for that.

Please consider adding also tests, it is done by adding a code to test in this section:
https://github.com/dojoengine/dojo/blob/9ea17b47f1dba8f6085cac12191fea64d5777604/crates/dojo-lang/src/plugin_test_data/introspect#L6-L51

And then, you can run `CAIRO_FIX_TESTS=1 cargo test --package dojo-lang` to ensure cairo is regenerating the tests with expected output. :+1:

Don't hesitate if you have any question.

**Comment by g4titan** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> Derive `Introspect` doesn't work with enum with u64 .
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> ```cairo
> [derive(Drop, Introspect, Copy, Serde)]
> enum BuildingId{
>     a: u64,
>     b: u64
> }
> ```
> 
> ```
> sozo build 
> ```
> 
> with error
> 
> ```
> error: Plugin diagnostic: Trait has no implementation in context: dojo::database::introspect::Introspect::<core::integer::u64>
>  --> some.cairo[BuildingId]:25:73
>                         @dojo::database::introspect::Introspect::<u64>::ty()
>                                                                         ^^
> 
> 
> error: Compilation failed.
> ```
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> build should work
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Additional context** Add any other context about the problem here.

you mean introspect does not work with type u64
the problem here is that introspect is a custom trait, that has not been implemented for u64
btw what does introspect do

**Comment by g4titan** [comment]
yes it does

**Comment by zsluedem** [comment]
@remybar Solved this one?

**Comment by remybar** [comment]
> @remybar Solved this one?

Yes ser, issue solved !
