### ISSUE TITLE
[BUG] Sozo always reregisters models

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1557]
Sozo will reregister models even if they are already registered and the class_hash hasn't changed

**Comment by kariy** [comment]
did you re-migrate with `--world` arg ?

**Comment by tarrencev** [comment]
> did you re-migrate with `--world` arg ?

no since it calculates the world address based on the name. i would expect the behavior in that case to no reregister models that already exist

**Comment by kwkr** [comment]
I will take this if it's still available.

**Comment by glihm** [comment]
> I will take this if it's still available.

For sure, feel free to reach if you have any question.
The idea would be `sozo` to first check if the model is already registered before registering it because currently the world does not make this check (and should be done by `sozo`).

**Comment by kwkr** [comment]
Thanks @glihm ! I started working on it and have a question, to begin with. I can see that the World contract has a map of models in its storage. The question is, should it be handled within sozo itself: read contract data, check which models are already registered and skip them or rather on the contract level within the `register_model` method?

**Comment by glihm** [comment]
> Thanks @glihm ! I started working on it and have a question, to begin with. I can see that the World contract has a map of models in its storage. The question is, should it be handled within sozo itself: read contract data, check which models are already registered and skip them or rather on the contract level within the `register_model` method?

Hey, good question. So for `sozo` to verify if a model is already registered, you'll have to use the `model` function from the world. This function returns information of a registered model: https://github.com/dojoengine/dojo/blob/640e94d8aeadaabcb51b26704b136908a575e866/crates/dojo-core/src/world.cairo#L10.

So you'll have to check:
1. If the two values returned are 0 -> you can consider the model is not registered and proceed.
2. If both values are not 0 -> you should not register again, the model is already there.
3. If one of the value is 0 and the other no -> this may happen with older dojo worlds, so in this case you should proceed to registration of the model.

Sounds good?

**Comment by kwkr** [comment]
Yes, this is very helpful @glihm 

I have two more questions:
First I would like to confirm the scope of the task that I have found so far. There are two places where I can see the models are registered. It's the `migrate` command and the `register` command. From what I see there is a whole strategy already in place for the `migrate` command and it doesn't seem to deploy anything new on a re-run. Please correct me if I'm wrong. The `register` command though issues a new transaction on each invocation.

 The second question is regarding the `register` command. As an input param it takes a classpath. One thing that I cannot currently figure out by myself is the connection between the classHash and the model name or in other words how could I get the name of a model from the classHash. This seems needed as the method for retrieving the information about the model accepts the model name as a param.

**Comment by kwkr** [comment]
Also is the documentation here out of data or am I mixing up some commands?
https://book.dojoengine.org/toolchain/sozo/world-commands/register

**Comment by glihm** [comment]
> Yes, this is very helpful @glihm
> 
> I have two more questions: First I would like to confirm the scope of the task that I have found so far. There are two places where I can see the models are registered. It's the `migrate` command and the `register` command. From what I see there is a whole strategy already in place for the `migrate` command and it doesn't seem to deploy anything new on a re-run. Please correct me if I'm wrong. The `register` command though issues a new transaction on each invocation.
> 
> The second question is regarding the `register` command. As an input param it takes a classpath. One thing that I cannot currently figure out by myself is the connection between the classHash and the model name or in other words how could I get the name of a model from the classHash (one way that I've found is through `Manifest::load_from_remote` but I'm not sure if that's the correct way). This seems needed as the method for retrieving the information about the model accepts the model name as a param.

Hey, sorry for the delay.
So yes, the `migrate` command uses the migration strategy, by comparing the local manifest and the remote manifest to know what must be done. So this one should be good as if the class hash didn't change, it should not do anything.

For `register` definitely the fix must be implemented. :+1:

> Also is the documentation here out of data or am I mixing up some commands?
> https://book.dojoengine.org/toolchain/sozo/world-commands/register

Would you mind submitting an issue on the book repository to ensure the tool documentation will be updated in the future? Thank you a lot.

Also, don't forget to merge the main branch into your branch.
