### ISSUE TITLE
Improve sozo migrate output

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1558]
Currently there is a final `register_model` multicall which occurs at the end of a model migration. It isn't clear that this action relates to all models. We should improve the output to disambiguate it

```
# Models (6)
dope_world::paper_bridge::paper_bridge_model
  > Already declared: 0x92388c909a31858a75c6e766b4c956612bbc22d07dd7e6b94885e753503cdf
token::components::security::initializable::initializable_model
  > Already declared: 0x6782696aebf5bf50992a9e5f06d116b2f8bb37c8892618b3a975146681c900
token::components::token::erc20::erc20_allowance::erc_20_allowance_model
  > Already declared: 0x6fc168b12a303452bce6f90c4f0fc47699d8714f43aac3ea0a9cfeb55524e74
token::components::token::erc20::erc20_balance::erc_20_balance_model
  > Already declared: 0x682b4f16fe839e94a9700f750f5448142369273db0880dc89241f3dc183a253
token::components::token::erc20::erc20_bridgeable::erc_20_bridgeable_model
  > Already declared: 0x311a622c34bacc61d159bdc9656f16799839752bfd07f788bc706ecc3f36ec0
token::components::token::erc20::erc20_metadata::erc_20_metadata_model
  > Already declared: 0x18d6ed523121dce641165ea669cd427e285c59a3e12b1625602dbe525bbcfe4
  > Registered at: 0x16363b4399c361e8817be0776c03e2bba20a99a5b49a246231021f40798cfae
  ```

**Comment by hhamud** [comment]
can I have this one?

**Comment by glihm** [comment]
> can I have this one?

Hey, for sure. If you have any question feel free to reach out. Do you have an idea how to tackle this?

**Comment by hhamud** [comment]
> > can I have this one?
> 
> Hey, for sure. If you have any question feel free to reach out. Do you have an idea how to tackle this?

I've only just cloned the repo and run the tests to make sure that it works on my system before proceeding. I'm assuming he means this specific function to make it much clearer?.

https://github.com/dojoengine/dojo/blob/64992c9ce2ca941ccdde91acea222725f13ed7f7/bin/sozo/src/ops/migration/mod.rs#L427-L492

**Comment by glihm** [comment]
The line:

```rust
ui.print_sub(format!("Registered at: {transaction_hash:#x}")); 
```
is actually a transaction for **ALL** the models. But in the UI, it looks like it only concerns the only model.
The idea is to have a line dedicated to that saying something similar to "Models registered at: <TX_HASH>", with clear line separation from the last model.

We use Scarb as it's the underlying library used to the compilation process and they have integrated UI that is very known (visually) from the ecosystem.

But we may change if other alternatives propose something good. :)
