### ISSUE TITLE
Commands:: not recognized inside if statement

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#156]
When trying to use commands:: within an if statement, I get a `error: Plugin diagnostic: Identifier not found.`

Example:
```
let drug = commands::<Drug>::get((game_id, (player_id, drug_id)).into());
if drug.is_some() {
    let _ = commands::set((game_id, (player_id, drug_id)).into(), (
        Drug { 
            id: drug_id, 
            quantity: updated_quantity
        }
    ));
}

```

**Comment by ponderingdemocritus** [comment]
I'm assuming we will need to search through the if/match/loop nodes, pluck and rewrite 

@tarrencev  ?

**Comment by tarrencev** [comment]
Yup thats correct. @broody is taking a look at this already
