### ISSUE TITLE
[sozo] Add Deploy Account functionality

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#1574]
As we move closer to production, we need to simplify the process for developers to create accounts on live networks.

Currently, Starkli offers the best developer experience for this on Starknet. However, the dojo stack is different, so we should integrate some functionality directly into Sozo.

**Account Management**
Sozo should enable a developer to create an account, store it in a keystore locally, and then deploy it after funding it through a faucet. This workflow, used by Starkli, is effective.

Since Scarb.toml is checked into repositories, we should follow Starkli's approach and store these in ciphertext. This means we would need to use this account instead of the Scarb.toml account if it exists.

**Therefore, this task involves:**

1. Enabling the deployment and management of accounts via Sozo similar to Starkli.
2. Managing accounts via Sozo using a ciphertext store locally, to avoid exposing these values in the Scarb.toml.

**Comment by JimmyFate** [comment]
Hey :)
I could give this a try

**Comment by glihm** [comment]
> Hey :) I could give this a try

Hey @JimmyFate are you already with an idea to how you will tackle this?

Don't hesitate if you have any question. The guideline here is:
1. Check how starkli handles the account and keystore files. They are two separate concerns. @ponderingdemocritus we also want to integrate all the signer logic right?
2. Then into sozo, you will find the organization of the binary with the commands (which parses the inputs) and then the ops, where the actual implementation of the behavior is.

Sounds good to you?

**Comment by ponderingdemocritus** [comment]
Yes we need signer logic too - sozo does already support some of this

**Comment by glihm** [comment]
Hey @JimmyFate, are you still working on this one?

**Comment by JimmyFate** [comment]
> Hey @JimmyFate, are you still working on this one?

Hey, there's an [open pull request](https://github.com/dojoengine/dojo/pull/1601)
