### ISSUE TITLE
[torii] Indexing optimization

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1583]
**Is your feature request related to a problem? Please describe.**
I'm curious so i ran a torii on mainnet, indexing a block could take around 10s on laptop.

The current indexing process is :
torii calls `starknet_getBlockWithTxs` to retrieve alls tx hash of a block
torii calls `starknet_getTransactionReceipt` for EACH TX

**Describe the solution you'd like**
It should be possible to do it in 1 call using `starknet_getEvents`, filtering on world address

**Comment by Larkooo** [comment]
I think it's because we need the block information on top of that (to process blocks). Which the events page doesn't contain. Should we care about blocks apart from their block number?

**Comment by Larkooo** [comment]
It also seems we need the txn information, we store each transaction and its receipt @tarrence 

torii/processors/store_transaction.rs

**Comment by tarrencev** [comment]
hmm yeah. perhaps we should parallelize things. we can do a map -> reduce, creating all the db queries in map then applying them sequentially in reduce

**Comment by tarrencev** [comment]
yeah that is a good optimization too. we will need to keep a registry of all world's contract address to filter txns by (i think we have this already in the db)

**Comment by Larkooo** [comment]
> then maybe use starknet_getEvents then query only txs we are interested in

Wouldn't it be basically the same thing? Because I think we'd sitll do the same thing for blocks. As we have a block processsor that takes in the block data
