### ISSUE TITLE
[BUG] Generic type doesn't work with model struct

### ISSUE THREAD

**Issue by zsluedem** [dojoengine/dojo#1585]
**Describe the bug**

Generic type doesn't work with model struct

**To Reproduce**
```
use starknet::ContractAddress;

#[derive(Model, Serde, Cody, Drop)]
struct A<T>{
    #[key]
    player: ContractAddress,
    a: T,
    b: u64
}
```

Build Failed 

**Expected behavior**
SHould compile without errors

**Screenshots**

**Additional context**
Not sure whether this should be feature request or not.

**Comment by remybar** [comment]
Hi @zsluedem !

Thanks for your bug report !

To me, it looks weird to define a generic model because a model is a concrete data that should be storeable. So, if you create several instances of this `A` model using different types for `T`, they belong to different models (one model per `T` type).

On a technical perspective, a model is expanded to a `starknet::interface` and `starknet::contract`, and, as far as I know, a `starknet::interface` can only contain one generic type which is the contract state type.

This is my opinion but better to wait for @tarrencev and/or @glihm opinions 👍

**Comment by zsluedem** [comment]
@remybar Thanks for the reply. The idea to make Model with generic param is to reuse some of the codes which behave similaryly.  I am thinking that I can simply define different models as long as T is `Introspect`. The T needs to be specific when it is neccessary.

Just some ideas.Maybe the issue is more like a feature request instead of bug

**Comment by remybar** [comment]
> @remybar Thanks for the reply. The idea to make Model with generic param is to reuse some of the codes which behave similaryly. I am thinking that I can simply define different models as long as T is `Introspect`. The T needs to be specific when it is neccessary.
> 
> Just some ideas.Maybe the issue is more like a feature request instead of bug

I'm new on the Dojo project, so better to have another opinion from the core team ;-)

I would say that if you want to have generic logic, you should implement it outside models and then instanciate it in your models. For example:
```
struct MyGenericStuff<T> {
   a: T
}

#[derive(Model, Serde, Cody, Drop)]
struct M1{
    #[key]
    player: ContractAddress,
    action: MyGenericStuff<Action>,
}

#[derive(Model, Serde, Cody, Drop)]
struct M2{
    #[key]
    player: ContractAddress,
    position: MyGenericStuff<Position>
}
```

@glihm any opinion for this point ?

**Comment by glihm** [comment]
@zsluedem thanks for the report and @remybar for the great explanations on that.

It is not supported, mostly for the technical limitation that @remybar mentioned, where a model is actually expanded to a contract with a very defined layout for the storage that can't change and must be known at **compile time**. Having a generic type like `T` can introduce layout changes based on the type present in `T`.

Also in the Dojo database system, a model is identified by it's name (will be the selector soon). And this name is allowing dojo database to retrieve information from the correct storage location, and the `MyModel<T>` have the same name for every `T` you would define, causing conflict here as the storage layout is fixed at compile time.
