### ISSUE TITLE
[Katana] RPC spec 0.6.0

### ISSUE THREAD

**Issue by shramee** [dojoengine/dojo#1596]
**Is your feature request related to a problem? Please describe.**
Katana is incompatible with the new starkli which supports 0.6.0.

**Describe the solution you'd like**
Serve spec 0.6.0 😎 

**Describe alternatives you've considered**
Downgrading starkli

**Additional context**
None

**Comment by broody** [comment]
Hey, 0.6.0 rpc support was just merged last week (https://github.com/dojoengine/dojo/pull/1568), you can try it out in latest alpha release https://github.com/dojoengine/dojo/releases

**Comment by shramee** [comment]
🥳 Awesome!!!
