### ISSUE TITLE
Refactor: Improve `migration` world representation

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#162]
During migration planning, we construct a local and remote representation of the world, in order to diff them and generate a migration plan.

The current code is at:

https://github.com/dojoengine/dojo/blob/c515e9e839c848e132506085be6eed67195cc758/crates/dojo-cli/src/migrate.rs#L150

It is pretty hacked together right now and can be improved by using the manifest generated by the build step. 

https://github.com/dojoengine/dojo/blob/c515e9e839c848e132506085be6eed67195cc758/crates/dojo-lang/src/manifest.rs#L67

In particular, the component hashing logic can be moved to the build step:

https://github.com/dojoengine/dojo/blob/c515e9e839c848e132506085be6eed67195cc758/crates/dojo-lang/src/compiler.rs#L70

The manifest can then be extended to include a `from_rpc` method that generates a manifest based on the remote source.

Finally, we can introduce migration planning logic which takes a local + remote manifest and generates a strategy to transition the remote state to match the local.

**Comment by kariy** [comment]
Does this imply creating another manifest file specifically for remote? or contained both in a single file? eg. :

```rust
struct Manifest {
    local: LocalManifest,
    remote: RemoteManifest
}
```

**Comment by tarrencev** [comment]
We can have a single `Manifest` struct and create a `remote` and `local` instance. The `local` is loaded by parsing the `manifest.json` outputted during the build and the `remote` one is loaded from the chain using the rpc provider.

So we should implement a method on `Manifest` like

```
fn from_remote(rpc...) -> Self {

}
```
