### ISSUE TITLE
[sozo] Issue with manifests generated with previous versions

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1625]
**Describe the bug**
I have a `staging` sozo profile 

`sozo -P staging migrate` caused this error

```
[1] 🌎 Building World state....
error: missing field `resource_metadata` at line 5187 column 1
error: script failed with exit code: 1
```

the manifest.json generated with prev dojo version (before introducing resource_metadata) caused this error
removing /target/staging solved

**Expected behavior**
idk, suggest cleaning /target/profilename ?

**Additional context**
v0.6.0-alpha.3

**Comment by glihm** [comment]
We should add a `sozo clean` then? Does running `scarb clean` also solves the issue?

**Comment by remybar** [comment]
Yes, `scarb clean` removes everything in `target`, so I would say there is no need to add a new. `sozo clean` command for that.

As far as I understand, there are 2 mains folders to store manifest/artifact files:
- in `target/<PROFILE>` for artifacts generated by `sozo build`
- in `manifest`for base/overlay/deployed manifest files generated by `sozo build` and updated by `sozo migrate`.

In both cases, in case of discrepancy/inconsistency in these files, `sozo migrate` may crash.

I would suggest to handle this to have a cleaner way to stop the migration by indicating that there is some discrepancies in some manifest/artifact files and to suggest some solutions to the user:
- in case of discrepancy in artifact files, we may suggest to run `scarb clean`.
- in case of discrepancy in manifest files, we may implement a dedicated `sozo clean` command to remove partially or the full `manifest` folder.

If we add a new `sozo clean` command, we may also call `scarb clean` under the hood to clean everything.

What do you think about that ?

**Comment by glihm** [comment]
@remybar yes, having the two cases well identified is great, and we must guide the user the most we can.

> so I would say there is no need to add a new. sozo clean command for that.

The biggest advantage of adding a command is that the user does not need to have `scarb` installed, and only rely on `dojoup` and `sozo` command.

>If we add a new sozo clean command, we may also call scarb clean under the hood to clean artifacts at the same time.

Event if `scarb clean` shouldn't impact too much, I would be more cautious in a first version, and not taking action on the behalf of the user.

WDYT about first warning the user and prompting the command to run?

**Comment by remybar** [comment]
> WDYT about first warning the user and prompting the command to run?

My previous message was not very clear but yes, I agree with you ! Inform the user about discrepancies and advice him to use a command to clean everything. Running a command on the behalf of the user is definitely not a good idea 👍 

So you would create a `sozo clean` command to handle both cases ? Kind of:
- `sozo clean --all` remove everything,
- `sozo clean --manifests` remove manifests,
- `sozo clean --artifacts` remove artifacts as `scarb clean` does.

Or just a `sozo clean` command which cleans everything ? Or a smart command which cleans corrupt files only (maybe dangerous to keep a coherency between all the files) ?

**Comment by glihm** [comment]
> So you would create a `sozo clean` command to handle both cases ? Kind of:
> 
> * `sozo clean --all` remove everything,
> * `sozo clean --manifests` remove manifests,
> * `sozo clean --artifacts` remove artifacts as `scarb clean` does.
> 

Yep! The slightly different thing I would do is by default `sozo clean` clears everything as you mentioned at the end.
And if the user passes `--manifests` or `--artifacts` we clean those specifically.
So `sozo clean` and `sozo clean --manifests --artifacts` are identical.

To be fully cleaned up, we should also remove the `abis` folder when we clean the manifests. Perhaps the option can be `--manifests-abis`, a bit verbose but more informative. Or the help must mention that.

**Comment by glihm** [comment]
Completed by #1672.
