### ISSUE TITLE
Migrate to fully qualified names for models / contracts

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1629]
Currently, we use a models struct name as its identifier. This works fine during development but in a production world, there will be many namespace conflicts. We need to instead use a fully qualified path name and hash it to generate a selector. That will enable multiple models with the same struct name but in different projects to exist simultaneously in the world.

Additionally, we should implement a `dojo::event` when derives events with a fully qualified name rather than the struct name as `starknet::event` does today.

**Comment by glihm** [comment]
Namespaces will take over on fully qualified names.
