### ISSUE TITLE
[BUG] After deleting an entity using delete!, Torii (client) returns an error.

### ISSUE THREAD

**Issue by thiscaspar** [dojoengine/dojo#1635]
**Describe the bug**
After creating, and then deleting an Entity in Dojo using the `delete!` macro, the Torii client (in React) returns the error `no rows returned by a query that expected to return at least one row`

**To Reproduce**
We created a repo, in the README are the steps to reproduce:  https://github.com/pixelaw/torii_delete_issue

**Expected behavior**
Torii (client) should not return an error, but continue working normally

**Additional context**
- We've seen this happen in Dojo 0.5.1 and 0.6.0-alpha.2 / 3
- Upon poking around in the Torii sqlite db, it seems that deleting the `entity` and `entity_model` records that are missing their corresponding records in the [Model] table resolves the error and Torii returns non-error results. Not sure if this is correct though.

**Comment by noyyyy** [comment]
Same problem for me, So I add a more variable to mark entity as deleted.

**Comment by edisontim** [comment]
Just had the same issue in a similar context

**Comment by glihm** [comment]
This should have been fixed by #2071.
