### ISSUE TITLE
Remove assignment requirement from `commands::set`

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#164]
Currently, it is required to assign `commands::set` to a variable, since he variable is used to uniquely identify the underlying calldata array that is generated.

https://github.com/dojoengine/dojo/blob/c515e9e839c848e132506085be6eed67195cc758/crates/dojo-lang/src/commands/set.rs#L29

Ideally we can remove this constraint. Ideally we could inline the creation and avoid the assignment but i dont think that is possible. One approach could be to construct an identifier using the component types and the storage key. Another option is to namespace the operation with a nested module.

**Comment by ponderingdemocritus** [comment]
So from the contract side:

From:

`commands::set(owner_sk, (Owner { token_id: to, balance: owner.balance + 1 }));`

To:

`commands::set(owner_sk, ({ token_id: to, balance: owner.balance + 1 }));`

?
