### ISSUE TITLE
Inconsistent names in unity codegen plugin files

### ISSUE THREAD

**Issue by cristianFleita** [dojoengine/dojo#1641]
The generated file name produced by the codegen should share the same name as the corresponding class.
Otherwise, this inconsistency leads to an error in Unity.

<img width="770" alt="Screenshot 2024-03-09 at 14 42 36" src="https://github.com/dojoengine/dojo/assets/87950451/353101e2-44c0-4da7-b30d-e1b2ad6e26b4">

**Comment by glihm** [comment]
@cristianFleita is this something fixed by some new released of Unity plugin with new types being reworked?

**Comment by glihm** [comment]
Will close since unity plugin has been updated for `1.0.0`, and please @cristianFleita re-open if the exact same behavior is observed. 👍
