### ISSUE TITLE
Use nonce for off chain messages in Torii relay

### ISSUE THREAD

**Issue by Larkooo** [dojoengine/dojo#1655]
validate models for offchain messages for them to include a nonce which will prevent potential replay attacks that would use past signatures to rollback the state of message entity

**Comment by andresmayorca** [comment]
can i work in this?

**Comment by Larkooo** [comment]
> can i work in this?

you can refer to #1656 if you wanna contribute. we should ensure that models that are going to be used by offchain messages include a nonce field that is going to be signed with the new state of the off-chain message (included in the signed model typed data) and incremented whenever the state is updated
