### ISSUE TITLE
[katana] [sozo] Cairo v2.6.2

### ISSUE THREAD

**Issue by shramee** [dojoengine/dojo#1659]
**Is your feature request related to a problem? Please describe.**

Cairo v2.6.2

**Describe the solution you'd like**
Cairo v2.6.2

**Describe alternatives you've considered**
Using old Cairo with no complex consts, more gas spent and unnecessary Nonzero tryintos.

**Comment by shramee** [comment]
@glihm This might also require `katana` tag, coz `v2.6` has updates to Sierra coz your's truly requested some complicated constants to do some computation at compile time for a leaner and cheaper run.

**Comment by kariy** [comment]
This might be blocked until [starknet_in_rust](https://github.com/lambdaclass/starknet_in_rust) is bumped to `cairo 2.6`, and they said it might take them ~1 month for this as they have to update it on `cairo-native` side as well.

We could just update `sir` to `2.6.*` and disable the `cairo-native` feature for now (considering it's still not 100% usable), but it's not gonna be a straight forward bump I think.

**Comment by kariy** [comment]
dojo now supports cairo 2.6.3 since #1865
