### ISSUE TITLE
Transaction signer

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#166]
Implement a transaction signer interface and provide a base implementation which reads a private key from the local system.

The signer should be used during`migration` to sign and submit transactions.

**Comment by ponderingdemocritus** [comment]
Do we just want a crate like this - https://github.com/xJonathanLEI/starknet-rs/tree/master/starknet-signers ?

**Comment by tarrencev** [comment]
> Do we just want a crate like this - https://github.com/xJonathanLEI/starknet-rs/tree/master/starknet-signers ?

Yup a set of signers that implement the starknet-rs trait, so we can easily use them with the rpc client

**Comment by ponderingdemocritus** [comment]
i can take a swing at this today
