### ISSUE TITLE
[sozo] output manifest format for client libraries

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1665]
With the rework on the manifest, there's no one manifest, but several files that compose the manifest.

However, when `sozo migrate` is used on a specific network, a single `<CHAIN_ID>.toml` file is generated, compiling all the information of the world and associated models and contracts.

two important questions:
1. Is `toml` ok for most of the client? Should we output a `json` too?
2. The ABI inside the manifest are relative paths, so the file is not self contained. Should we have a command `sozo manifest --to-json /tmp/manifest.json` (or other format as needed) that combine the manifest data + the ABI into a single manifest file which is easier to load on the client?

@RareSecond @notV4l @ponderingdemocritus @Larkooo 

Tasks:
- [ ] Add the chain id to the manifest (in the world entry).
- [ ] Add the rpc url to the manifest (in the world entry).

**Comment by glihm** [comment]
We may have an option with `sozo build --manifest-json` to output the self contained manifest automatically (with embedded ABI)?

**Comment by ponderingdemocritus** [comment]
We need to support json for time being as many apps use that format.

**Comment by RareSecond** [comment]
Agree with the above

> into a single manifest file which is easier to load on the client?

I'd also indeed argue for keeping this. Ideally the client should only worry about a single file!
