### ISSUE TITLE
[sozo] update the world during `sozo migrate`

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1671]
**Is your feature request related to a problem? Please describe.**
Currently, the world is never updated by `sozo migrate`.
We should add this capability to ensure seamless upgrades for users.

**Describe the solution you'd like**
Ensure `sozo migrate` checks for the world's class hash to upgrade if necesarry.

**Comment by lambda-0x** [comment]
please assign this to me sensei :)

**Comment by glihm** [comment]
This update will also contain the base class hash manipulation, which ensure contracts can be upgraded in place.
