### ISSUE TITLE
[sozo] use the `offline` flag to not upload data to IPFS

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1677]
**Is your feature request related to a problem? Please describe.**
Currently, during a `sozo migrate` command, sozo is always trying to upload the metadata to IPFS.
However, in some cases working locally, we don't want to depend on network operation.

**Describe the solution you'd like**
Currently, sozo already have a flag `--offline`. If this flag is used, we should ensure that `sozo migrate` is not trying to upload data to IPFS.

**Additional context**
The upload of IPFS data starts here: https://github.com/dojoengine/dojo/blob/b9d592eb0883b3efcba309d0ec65e85290dd2258/bin/sozo/src/ops/migration/mod.rs#L458

**Comment by lambda-0x** [comment]
will take this up

**Comment by glihm** [comment]
Closed in #1678.
