### ISSUE TITLE
Migration from `ethers` to `alloy`

### ISSUE THREAD

**Issue by tcoratger** [dojoengine/dojo#1681]
**Is your feature request related to a problem? Please describe.**

In the codebase, there are several instances where `ethers` types are still being used, such as:

https://github.com/dojoengine/dojo/blob/91d8dac307e5f09b06cc47e2e5427d930b593a39/crates/katana/rpc/rpc-types/src/account.rs#L1
https://github.com/dojoengine/dojo/blob/91d8dac307e5f09b06cc47e2e5427d930b593a39/crates/katana/primitives/src/transaction.rs#L2
https://github.com/dojoengine/dojo/blob/91d8dac307e5f09b06cc47e2e5427d930b593a39/crates/katana/core/src/service/messaging/ethereum.rs#L9

**Describe the solution you'd like**

Following discussions like [this one](https://github.com/paradigmxyz/reth/issues/4715), among others, numerous repositories are transitioning from `ethers` to `alloy` as a more comprehensive, precise, and modern Rust Ethereum library. Consequently, it appears appropriate to migrate entirely to the equivalent `alloy` library here, eliminating all references to `ethers`.

**Comment by tarrencev** [comment]
Thanks for opening this. That would be great. Are you interested in making this contribution?

**Comment by tcoratger** [comment]
> Thanks for opening this. That would be great. Are you interested in making this contribution?

Yes sure I can handle this.
