### ISSUE TITLE
Update loggers to be namespace and properly use structured logging

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1683]
Currently we have logs like `info!("processed block: {}", block.block_number);` should should be updated to define a target and use structured logging, for example:

```
info!(target: "torii::indexer::engine", "Processed block.", block = %block.block_number);
```

**Comment by Jonatan-Chaverri** [comment]
I can take care of this one

**Comment by glihm** [comment]
> I can take care of this one

Awesome @Jonatan-Chaverri, this issue is ideally on the whole stack, is that ok for you?

**Comment by Jonatan-Chaverri** [comment]
Sure, no problem.
