### ISSUE TITLE
[sozo] add tests for all the `ops` related to a commands

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1684]
Sozo's commands are now using `sozo/ops` crate to run the actual code behind the command. However, only `migrate` code is tested.

All `ops` must be tested to ensure safer upgrade of Sozo in the future.
@lambda-0x could you comment to assign this one to you?

**Comment by lambda-0x** [comment]
ohayo!

**Comment by remybar** [comment]
Do you plan to move all the logic stuff from `bin/sozo` to `sozo/ops` to have a strong test suite in `sozo/ops` to validate all the sozo commands there ? For example, at the moment, the `init` and `clean` commands have their logic directly in `bin/sozo`.

I ask to apply the same method for https://github.com/dojoengine/dojo/issues/1663 and future commands :)

**Comment by glihm** [comment]
> Do you plan to move all the logic stuff from `bin/sozo` to `sozo/ops` to have a strong test suite in `sozo/ops` to validate all the sozo commands there ? For example, at the moment, the `init` and `clean` commands have their logic directly in `bin/sozo`.
> 
> I ask to apply the same method for #1663 and future commands :)

Yes the idea of having this first work on decoupling the `ops` from `commands` is to have a strong test suite on `ops`.
If during your PR you could also decouple the missing commands it could be great.

For `call` we should follow the same separation, and also `call` may do like `execute` where the contract can be called by it's name and address resolution is done under the hood for the user.

**Comment by remybar** [comment]
> > Do you plan to move all the logic stuff from `bin/sozo` to `sozo/ops` to have a strong test suite in `sozo/ops` to validate all the sozo commands there ? For example, at the moment, the `init` and `clean` commands have their logic directly in `bin/sozo`.
> > I ask to apply the same method for #1663 and future commands :)
> 
> Yes the idea of having this first work on decoupling the `ops` from `commands` is to have a strong test suite on `ops`. If during your PR you could also decouple the missing commands it could be great.
> 
> For `call` we should follow the same separation, and also `call` may do like `execute` where the contract can be called by it's name and address resolution is done under the hood for the user.

Ok ser ! 👍

**Comment by remybar** [comment]
> Yes the idea of having this first work on decoupling the `ops` from `commands` is to have a strong test suite on `ops`. If during your PR you could also decouple the missing commands it could be great.

@glihm @lambda-0x 
Finally, I've just written tests for the call command to avoid mixing things in a PR related to the `call` command. I'm not sure that I used the most efficient way to test the call command so I can modify these tests if you have some great ideas ;-)
 
About decoupling/adding unit tests for other commands, I can help for sure if needed ! If you need help, just tell me which commands to test and I will do it in another PR. Maybe the ones not decoupled yet ?

**Comment by glihm** [comment]
> @glihm @lambda-0x Finally, I've just written tests for the call command to avoid mixing things in a PR related to the `call` command. I'm not sure that I used the most efficient way to test the call command so I can modify these tests if you have some great ideas ;-)

Sounds great, thank you for this separation of concerns.

> About decoupling/adding unit tests for other commands, I can help for sure if needed ! If you need help, just tell me which commands to test and I will do it in another PR. Maybe the ones not decoupled yet ?

Let me sync with @lambda-0x to see his plans, and get back to you. :+1: Thanks man for the availability.

**Comment by glihm** [comment]
We've now a better testing for `ops`. Will add issues for individual testing for more use-cases as needed.
