### ISSUE TITLE
Consider automatically importing component dispatcher impl and trait

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#169]
With the introduction of https://github.com/dojoengine/dojo/pull/168/files#diff-1d7a7dbdbca246355d93023e3fc830cc8af760cd932c03e965fd3a77f5bf553bR28-R32, which resolves #168, developers need to manually import the library dispatcher impl and trait.

```
    use super::Position;
    use super::IPositionLibraryDispatcher;
    use super::IPositionDispatcherTrait;
    use super::Player;
    use super::IPlayerLibraryDispatcher;
    use super::IPlayerDispatcherTrait;
```

We could handle this automatically. The downside is it's an implicit behavior that might be confusing if the developer tries to import themselves. Although I'm not sure in what case they would do that.

**Comment by tarrencev** [comment]
> I agree with handling it automatically. It's inline with Dojo being a DSL and doing the boring heavy lifting.

Sounds good. Wanna take a stab at it? :D

**Comment by milancermak** [comment]
Haha, I was afraid you'll ask 😁

Ok, I'll give it a go.

**Comment by tarrencev** [comment]
We no longer need this since we aren't using the component contract serde api since #190
