### ISSUE TITLE
Enums not recognized in where clause when doing a query

### ISSUE THREAD

**Issue by alexhaloETH** [dojoengine/dojo#1690]
When using the where clause when querying an entity, if I wanted to find a certain entity based on an enum value, the database return with "Matching variant not found".

Add an Enum type variable to a model on the dojo end and query that entity via its enum value.

Should fetch the entities with that match the query.

screenshot showing database fetch failure due to enum in where clause.
![image](https://github.com/dojoengine/dojo/assets/108292891/432d1be6-12ef-4939-b6da-8387e0bfd644)

same query without the where clause, shows that the enums are set correctly.
![image](https://github.com/dojoengine/dojo/assets/108292891/bc72f2d4-7925-441f-8163-4380b287788f)

Dojo version 0.5.1
I have also tried 
reinforcement_type: "1"
reinforcement_type: 1
but also dont work

**Comment by glihm** [comment]
To be checked on `0.7.1`.

**Comment by glihm** [comment]
Checked and solved on `0.7.1`.
