### ISSUE TITLE
[sozo] support `sozo auth revoke`

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1701]
**Is your feature request related to a problem? Please describe.**
Currently, `sozo auth` only supports granting `writer` and `owner`.

**Describe the solution you'd like**
Implement the logic for `sozo auth` to also support `revoke`. The world already contains the methods, they must be called.

https://github.com/dojoengine/dojo/blob/4af8b033a796db9554506dc9e0e6d97d113aadcc/bin/sozo/src/commands/auth.rs#L118

This PR consists of adding the function to interact with the world into ops here:
https://github.com/dojoengine/dojo/blob/4af8b033a796db9554506dc9e0e6d97d113aadcc/crates/sozo/ops/src/auth.rs

And called from the command file here:
https://github.com/dojoengine/dojo/blob/4af8b033a796db9554506dc9e0e6d97d113aadcc/bin/sozo/src/commands/auth.rs

**Comment by Mohiiit** [comment]
Hi, Can I pick this up? will require some help

**Comment by glihm** [comment]
> Hi, Can I pick this up? will require some help

Hey! Nice to see you around @Mohiiit picking up issues. :)

So yes, you can check how `grant` works, but the idea is that:
1. First, you will need to update the code for the `auth` command to support revoke case.
2. In the `sozo/ops` crate, you have to also add the function for revoking the permission. The world has two functions that should be available when using the `WorldContract` type in rust:
https://github.com/dojoengine/dojo/blob/5340720d76b6643d5443475d93ae9f8e6b16d032/crates/dojo-core/src/world.cairo#L30
https://github.com/dojoengine/dojo/blob/5340720d76b6643d5443475d93ae9f8e6b16d032/crates/dojo-core/src/world.cairo#L34

Let us know if you have blockers, here or on discord. :+1:
