### ISSUE TITLE
Document the build process for contributors

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1711]
Currently, there's no explicit guide for a new contributor to what are the steps and options to build dojo and work on the code base.

This issue aims at adding a section into the `README` to explain new contributors how to:
1. Get dojo cloned
2. How to build (full workspace, how to work on a crate only, etc...)
3. How to test (same, full workspace, only some crates, etc...)
4. Which checks have to be done
5. use the scripts in [`scripts/`](https://github.com/dojoengine/dojo/tree/main/scripts)

**Comment by kariy** [comment]
adding a PR template with a checklist for doing clippy,fmt checks etc would be helpful

**Comment by ebukizy1** [comment]
assign me this task will love to work on this

**Comment by glihm** [comment]
> assign me this task will love to work on this
> 
> 

Thank you for the proposal man, I'm actually wrapping up some documentation at different level and it includes this one.

Please don't hesitate if others issues make sense to you, will also wrap up the review on the book of your PR.
