### ISSUE TITLE
yarn add @dojo

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#173]
We need to build an npm package that allows developers to easily integrate Dojo worlds.

We start with a low-level library first, from which React hooks and Vue injections, and other js libraries can use.

This library should be built with multiple providers in mind. We should maintain support for:

- RPC (first release)
- Web Sockets
- WebRTC (future)
- Beerus

Where possible, the library should expose commands that mirror the Dojo [commands](https://github.com/dojoengine/dojo/tree/main/crates/dojo-lang/src/commands) to streamline understanding between the libraries.

In Dojo, we can `get` a component by:

`let player = commands::<(Health, Name)>::get(player_id);`

Correspondingly our functions should be designed around the same `get`, `set` pattern by passing in the entity id. From these queries, the state of the entities can be created and displayed to the client. 

So at a minimum 

Once this package is done, we can craft the React SDK with it.

```
class Dojo implements IData {
  [key: string]: any;

  private rpcEndpoint: string | undefined;
  private rtcEndpoint: string | undefined;

  constructor(initialData: IData, rpcEndpoint?: string, rtcEndpoint?: string) {
    Object.assign(this, initialData);
    this.rpcEndpoint = rpcEndpoint;
    this.rtcEndpoint = rtcEndpoint;
  }

  // Generic execute function
  async execute<T>(method: string, params: any[]): Promise<T> {
    if (method.startsWith('rpc.')) {
      return this.callRPC<T>({ method, params });
    } else if (method.startsWith('rtc.')) {
      return this.establishWebRTCConnection(params[0]);
    } else {
      throw new Error('Invalid method prefix. Must be "rpc." or "rtc."');
    }
  }

  // RPC Function
  private async callRPC<T>(rpcParams: IRPCParams): Promise<T> {
    if (!this.rpcEndpoint) {
      throw new Error('RPC endpoint is not defined.');
    }

    // Implement your RPC call here
    // For now, let's mock the response with a simple Promise
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(`RPC call to ${rpcParams.method} with params: ${rpcParams.params} at ${this.rpcEndpoint}`);
      }, 1000);
    });
  }

  // WebRTC Function
  private async establishWebRTCConnection(roomId: string): Promise<void> {
    if (!this.rtcEndpoint) {
      throw new Error('RTC endpoint is not defined.');
    }

  }
}
```
Something like this?

Thoughts @tarrencev @fracek ?

**Comment by fracek** [comment]
Will the http client and websocket client have the same functionality or will be different? I'm thinking if the library should have a generic `Provider` interface with different implementations (`HttpProvider`, `WebsocketProvider`, etc).

**Comment by ponderingdemocritus** [comment]
I think the interfaces would be the same. I was thinking have the most simple implementation for each call and you just select the protocol you want to use. But I think you are right - splitting makes more sense

**Comment by fracek** [comment]
Agree. Since some of the targets will support streaming, how do you see the interface? Should get return the most recent state or it should be a subscription to receive values every time the entity is updated?

**Comment by ponderingdemocritus** [comment]
added prototype for comments in #179
