### ISSUE TITLE
Create asdf plugin

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1753]
Create a plugin similar to https://github.com/software-mansion/asdf-scarb to support installation through the version manager

I created a repo for it here: https://github.com/dojoengine/asdf-dojo

**Comment by Jonatan-Chaverri** [comment]
I will like to take care of this one!

**Comment by Jonatan-Chaverri** [comment]
Hi, sorry for the delay. The Dojo game jam last week distracted me a bit.

I have one question regarding to this, do you guys want to install dojo using the script found in here https://raw.githubusercontent.com/dojoengine/dojo/main/dojoup/install ? (Meaning that the plugin will fetch this script and install dojo from it following the same steps as a normal user will do) or should I extract the steps that are follow by this script into the asdf-dojo plugin itself? (the plugin will take care of following the same steps in the script to install dojoup).

**Comment by glihm** [comment]
> Hi, sorry for the delay. The Dojo game jam last week distracted me a bit.
> 
> 
> 
> I have one question regarding to this, do you guys want to install dojo using the script found in here https://raw.githubusercontent.com/dojoengine/dojo/main/dojoup/install ? (Meaning that the plugin will fetch this script and install dojo from it following the same steps as a normal user will do) or should I extract the steps that are follow by this script into the asdf-dojo plugin itself? (the plugin will take care of following the same steps in the script to install dojoup then install dojo).

Hey! No worries for the delay you're all good.

The easiest way seems to use dojo up inside the plugin. As this script already handle versions. However if asdf has some hard requirements that force you to modify it, you may want to extract the steps.

**Comment by Jonatan-Chaverri** [comment]
Please check my PR https://github.com/dojoengine/asdf-dojo/pull/1 I posted some few questions in there. Thanks

**Comment by Jonatan-Chaverri** [comment]
Created a new PR due to recent recomendations on previous PR. Please check https://github.com/dojoengine/asdf-dojo/pull/2
