### ISSUE TITLE
Extend component to describe schema + packing

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#176]
Generate a schema definition for components to support introspection

Something like
```
    fn schema() -> Array<(kind, len)> {
        Array::new([
            ('felt252', 252),
            ('u32', 252),
        ])
    }
```

We generate the component implementations here:

https://github.com/dojoengine/dojo/blob/fe97850a5ee6b13873b1788dbb121e97a140c486/crates/dojo-lang/src/component.rs#L15

We can iterated over a structs members like this:

https://github.com/dojoengine/dojo/blob/fe97850a5ee6b13873b1788dbb121e97a140c486/crates/dojo-lang/src/component.rs#L57

For the initial implementation, `len` should always be 252. We can implement bit packing as a follow up.

Once you've edited the codegen you can update the generated output in https://github.com/dojoengine/dojo/blob/main/crates/dojo-lang/src/plugin_test_data/component with

```
CAIRO_FIX_TESTS=1 cargo test --package dojo-lang --lib -- plugin::test::expand_contract::component --exact --nocapture 
```

**Comment by Cheelax** [comment]
Hey @tarrencev 
I am working on this right now.
Thank you for the detailed issue, I still have a little question.
Am I not supposed to pass something in the schema() function to iterate through it and output the schema?

**Comment by tarrencev** [comment]
> Hey @tarrencev I am working on this right now. Thank you for the detailed issue, I still have a little question. Am I not supposed to pass something in the schema() function to iterate through it and output the schema?

Great to hear! If I understand correctly, the `schema` file shouldn't have any inputs. The internal value should be generated by the compiler and return a static value

**Comment by Cheelax** [comment]
So you confirm I will always return an array containing the `felt252` representing the name and the `u32` representing the length? Only 2 elements then?

**Comment by tarrencev** [comment]
Ah no sorry, I was unclear. The existing `name` and `len` functions should continue to exist.

The schema function returns a description of the struct members and how they are packed. For example,

```
struct Position {
    x: felt252,
    y: u32,
    z: u64,
}
```

Should return (note i've extended the original type to also include the member name, since member ordering is important):

```
   fn schema() -> Array<(name, kind, len)> {
        Array::new([
            ('x', 'felt252', 252),
            ('y', 'u32', 252),
            ('z', 'u64', 252),
        ])
    }
```

Since there is no packing happening right now, so a u32 is stored in 252bits.

In the future, when we pack, we might have something like this:

```
   fn schema() -> Array<(name, kind, len)> {
        Array::new([
            ('x', 'felt252', 252),
            ('y', 'u32', 32),
            ('z', 'u64', 64),
        ])
    }
```

In this case, we can infer that the `y` and `z` are packed into a single felt.

cc @milancermak for feedback

**Comment by Cheelax** [comment]
So at the end I am supposed to call something.schema() right?

**Comment by tarrencev** [comment]
The generated component contract should have 'schema' as an addition view method that returns the schema definition
