### ISSUE TITLE
Integration testing for messaging

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1785]
**Is your feature request related to a problem? Please describe.**
Messaging feature is not battled testing with integration tests as it should be.

**Describe the solution you'd like**
This PR consists at writing integration testing for messaging where a Katana and an Anvil instance can communicate.

1. Use the Katana runner through the test sequencer https://github.com/dojoengine/dojo/blob/5015ea1dba0f8aee68c6913181fd1ecda7e06a6a/crates/dojo-test-utils/src/sequencer.rs#L30 to spin up a Katana.
2. Write a TestAnvil to have the same functionalities.
3. Run the messaging tutorial verifying the state on both chain to ensure messaging is working as expected.

**Additional context**
Messaging tutorial to execute: https://github.com/dojoengine/dojo/tree/5015ea1dba0f8aee68c6913181fd1ecda7e06a6a/crates/katana/primitives/contracts/messaging

**Comment by fabrobles92** [comment]
@glihm Hello, I'd love to work on this issue :)
