### ISSUE TITLE
Loop fail when using unregistered model

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1794]
**Describe the bug**
emit and event (i think StoreSetRecord) using unregistered model leads to fail loop in torii with following error
`ERROR tori_core::engine: Getting block. error=no rows returned by a query that expected to return at least one row`

**Expected behavior**
Ignore/warning for unregistered models

**Additional context**
0.6.0

**Comment by glihm** [comment]
Should be checked on `0.7.1`.

**Comment by glihm** [comment]
@notV4l for context, in which scenario this event is emitted without having the model registered?
