### ISSUE TITLE
[sozo] add raw max fee to `TransactionsOptions`

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1808]
**Is your feature request related to a problem? Please describe.**
Currently, the `TransactionOptions` struct only have a fee multiplier. Which makes the fee estimation depending on the node it relies on (which may sometimes return erroneous data). https://github.com/dojoengine/dojo/blob/64fa43c6551bc5fe4eff2676723f066ccb4e12cd/bin/sozo/src/commands/options/transaction.rs#L6-L13

**Describe the solution you'd like**
Add a new field to the `TransactionOptions` struct to allow the user to provide a raw value for the fees. The raw value should always be understood in the smaller unit (Wei for example).
In Starkli this concept of `max_fee_raw` exists, and can be taken as an example:
https://github.com/xJonathanLEI/starkli/blob/ae0d626e8fa479a7f4fcd8fe4661f59dfab50baa/src/fee.rs#L13

ref #1801

**Comment by princeibs** [comment]
Can I jump on this? @glihm

**Comment by kariy** [comment]
its yours @princeibs :)

**Comment by princeibs** [comment]
Hi @glihm, I am still working on it. Just having a hard time getting a hang of the codebase because of it's size. But I am certain I will figure it out. Will keep you posted about my progress.

**Comment by glihm** [comment]
> Hi @glihm, I am still working on it. Just having a hard time getting a hang of the codebase because of it's size. But I am certain I will figure it out. Will keep you posted about my progress.

No problem at all, feel free to reach out also on discord if you need additional help. 👍
Also referring to the #1823 you should normally have to locate your change in a limited area, which is where the `TxnConfig` has support for additional configuration.

**Comment by lambda-0x** [comment]
hi @princeibs, how is the progress on this issue? if you are facing any issues feel free to open a draft PR and let us know.
