### ISSUE TITLE
Freeze when too many connections are created through `on_enitity_updated`

### ISSUE THREAD

**Issue by RareSecond** [dojoengine/dojo#1810]
**Describe the bug**

**To Reproduce**
- Clone [this repo](https://github.com/RareSecond/torii-multiple-connections).
- `cd dojo`
- `katana --disable-fee`
- `sozo build && sozo migrate`
- `sozo execute 0x7ec42d76c6d876b8f219c20b6a152fe35fe2afc62c471b29ba689c2f6a075b3 spawn`
- `torii --world 0x446f1f19ba951b59935df72974f8ba6060e5fbb411ca21d3e3e3812e3eb8df8`
- `cd web`
- `pnpm i`
- `pnpm dev`

-------

- Open multiple tabs of the app
- See that not all tabs will load. Once you close a loaded tab, an unloaded tab might suddenly load
- Executing a query through `http://localhost:8080/graphql` will also hang

**Expected behavior**
Torii should be able to handle a couple of connections

**Screenshots**

**Additional context**
Ideally, there's also a way to close the subscription created through `on_entity_updated`

**Comment by RareSecond** [comment]
After further investigation, this seems to only happen on local `torii` instances. When deployed through Slot, everything seems to work fine.

**Comment by notV4l** [comment]
not able to reproduce with latest version 0.7.2
