### ISSUE TITLE
[katana] Display missing default values in command line --help

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1815]
**Is your feature request related to a problem? Please describe.**
The following default values are not displayed : 
```
--validate-max-steps <VALIDATE_MAX_STEPS>
The maximum number of steps available for the account validation logic.

 --invoke-max-steps <INVOKE_MAX_STEPS>
The maximum number of steps available for the account execution logic.

--eth-gas-price <L1_ETH_GAS_PRICE>
The L1 ETH gas price.

--strk-gas-price <L1_STRK_GAS_PRICE>
The L1 STRK gas price.
```

**Describe the solution you'd like**
Display default values like other params
```
-p, --port <PORT>
Port number to listen on.

[default: 5050]
```

**Comment by princeibs** [comment]
Can I work on this? @notV4l

**Comment by fabrobles92** [comment]
> @notV4l please can you help with resource where I can look up the default values?

I think you can find some values here:

https://docs.starknet.io/documentation/tools/limits_and_triggers/

**Comment by notV4l** [comment]
> @notV4l please can you help with resource where I can look up the default values?

well i started to look into it, and i did PR xd

**Comment by princeibs** [comment]
No worries @notV4l . I'll just look out for another issue
