### ISSUE TITLE
[BUG] sozo test fails with multiple systems in tests

### ISSUE THREAD

**Issue by dedushky** [dojoengine/dojo#1827]
**Describe the bug**
[testbug.zip](https://github.com/dojoengine/dojo/files/14967251/testbug.zip)

I have multiple systems described in my test case. 
It worked with dojo 0.4.4, but now it fails with dojo 0.6.0

` dojo_starter::tests::test_world::tests::test_move - Panicked with 0x454e545259504f494e545f4e4f545f464f554e44 ('ENTRYPOINT_NOT_FOUND')`

**To Reproduce**
Please see attached source code - slightly modified dojo_started project

**Expected behavior**
Test passed as ok

**Comment by lambda-0x** [comment]
hey @dedushky `actions2` is missing `#[abi(embed_v0)]` and you need to use separate salt during `deploy_contract` for both of them. Feel free to reopen if you more questions.

```cairo
#[dojo::contract]
mod actions2 {
    use super::{IActions2};

    #[abi(embed_v0) <----------- here
    impl ActionsImpl2 of IActions2<ContractState> { 
		fn spawn2(world: IWorldDispatcher) {
		}
 	}
}
```

```cairo
        // deploy systems contract
        let contract_address = world
            .deploy_contract('salt1', actions::TEST_CLASS_HASH.try_into().unwrap());
        let actions_system = IActionsDispatcher { contract_address };

		let contract_address2 = world
            .deploy_contract('salt2', actions2::TEST_CLASS_HASH.try_into().unwrap());
        let actions_system2 = IActions2Dispatcher { contract_address: contract_address2 };
```
