### ISSUE TITLE
Implement/derive `Debug` for public types

### ISSUE THREAD

**Issue by tcoratger** [dojoengine/dojo#1841]
**Is your feature request related to a problem? Please describe.**

It is convenient to expose a `Debug` method on all types that are public in order to make interaction with the outside easier. Some repository types like `TestSequencer` 

https://github.com/dojoengine/dojo/blob/89a5b9eb31a32e58a0429b7d17151361cb09f746/crates/dojo-test-utils/src/sequencer.rs#L29-L35

for example do not have this implementation provided.

**Describe the solution you'd like**

I think we should enforce the `Debug` implementation for all types made public. To facilitate this and be sure of the long-term continuation of this good practice, we could add the following lint https://doc.rust-lang.org/stable/nightly-rustc/rustc_lint/builtin/static.MISSING_DEBUG_IMPLEMENTATIONS.html to the Clippy script so that a rule violation is automatically detected by the CI.

**Comment by g4titanx** [comment]
hello @tcoratger, i would love to work  on this

**Comment by glihm** [comment]
> hello @tcoratger, i would love to work on this

Do you have any question @g4titanx before starting on this?
- [ ] add the clip check.
- [ ] derive `Debug` on public type. You may try to add a commit for each crate to ensure easier revision.

**Comment by glihm** [comment]
> yeah, can you elaborate the clip check issue

`clippy` check sorry, just reworded it. As mentioned by @tcoratger the idea is to ensure the linting step of the CI can detect a missing `Debug` on a public type.

**Comment by tcoratger** [comment]
> > yeah, can you elaborate the clip check issue
> 
> `clippy` check sorry, just reworded it. As mentioned by @tcoratger the idea is to ensure the linting step of the CI can detect a missing `Debug` on a public type.

@g4titanx Yes, this check does this job for example: https://github.com/paradigmxyz/reth/blob/bd4757b3b53022f871872790c27aa571d2ec2fdb/Cargo.toml#L96

**Comment by g4titanx** [comment]
> > yeah, can you elaborate the clip check issue
> 
> `clippy` check sorry, just reworded it. As mentioned by @tcoratger the idea is to ensure the linting step of the CI can detect a missing `Debug` on a public type.

okay, great!
i would reach out to you if I need more explanation

**Comment by g4titanx** [comment]
> > > yeah, can you elaborate the clip check issue
> > 
> > 
> > `clippy` check sorry, just reworded it. As mentioned by @tcoratger the idea is to ensure the linting step of the CI can detect a missing `Debug` on a public type.
> 
> @g4titanx Yes, this check does this job for example: https://github.com/paradigmxyz/reth/blob/bd4757b3b53022f871872790c27aa571d2ec2fdb/Cargo.toml#L96

yeah, I would used this as a reference

**Comment by g4titanx** [comment]
oh by the way, do you mean to implement #[derive(Debug)] for all pub types in the project or just in dojo/crates/dojo-test-utils/src/sequencer.rs

**Comment by tcoratger** [comment]
> > > > yeah, can you elaborate the clip check issue
> > > 
> > > 
> > > `clippy` check sorry, just reworded it. As mentioned by @tcoratger the idea is to ensure the linting step of the CI can detect a missing `Debug` on a public type.
> > 
> > 
> > @g4titanx Yes, this check does this job for example: https://github.com/paradigmxyz/reth/blob/bd4757b3b53022f871872790c27aa571d2ec2fdb/Cargo.toml#L96
> 
> yeah, I would use this as a reference

I would say, if possible, this is better to apply this rule for the entire project.

**Comment by g4titanx** [comment]
okay, great!

**Comment by g4titanx** [comment]
hey man! i have fixed this issue on my PC but I am having issue compiling as I am using a low ram computer. you can unassign me as I have tried every means to make this. i used a devcontainer too

**Comment by glihm** [comment]
> hey man! i have fixed this issue on my PC but I am having issue compiling as I am using a low ram computer. you can unassign me as I have tried every means to make this. i used a devcontainer too

Arg.. sorry to hear. You can specify a package if you want to limit ram consumption using the `-p` option while using `cargo build` or `cargo run`.

Also, do not hesitate to open the PR, this will help anyway. Appreciate your time and effort on this.

**Comment by g4titanx** [comment]
@glihm you know, i thought of writing a script to find all pub types and automatically add #[derive(Debug)].
found out that would save a lot of time but I couldn't even compile the code properly because of the size

 I created a PR tho: https://github.com/dojoengine/dojo/pull/2016
 I was having trouble making some pub types impl the debug trait
