### ISSUE TITLE
[sozo] add a repeat password step when running `sozo keystore new xxx`

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1884]
**Is your feature request related to a problem? Please describe.**
When creating a new keystore with `sozo keystore new xxx` the password is only asked once.

**Describe the solution you'd like**
Add a repeat password step & check passwords match

**Comment by mubarak23** [comment]
I will like to handle this issue

**Comment by glihm** [comment]
@mubarak23 any update on this? Let's know if you have any blocker.

**Comment by mubarak23** [comment]
@glihm please can you point me to specific part of the code that i need to work on for this issue,

i have been looking, but i was not able to find it

**Comment by glihm** [comment]
@mubarak23 this function is the one that could be modified to ensure a retry. However we only want a retry when we create a keystore with a new password:
https://github.com/dojoengine/dojo/blob/6ff5247ac16001ab59ee581ebf44c643e9cd6292/crates/sozo/ops/src/keystore.rs#L88

So we may:
1. Modify the function to have a `retry: bool` argument to be configurable by the caller, and if we retry, both password must match.
2. We can only modify the new function to actually ask the password twice and ensure they are the same: https://github.com/dojoengine/dojo/blob/6ff5247ac16001ab59ee581ebf44c643e9cd6292/crates/sozo/ops/src/keystore.rs#L13.

**Comment by mubarak23** [comment]
i see, so where we are calling `get_password(password)?; ` we have to call it twice and do a match that they are the same

**Comment by glihm** [comment]
> i see, so where we are calling `get_password(password)?; ` we have to call it twice and do a match that they are the same @glihm am i correct here

Yes but only for the case we're setting a new password. 👍
Don't hesitate to open a draft PR, they are here for that. We can guide you for the implementation and it's easier to see what's you've in mind with some code being written.

**Comment by mubarak23** [comment]
alright
