### ISSUE TITLE
[sozo] add more infos on error for `sozo account deploy`

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1886]
**Is your feature request related to a problem? Please describe.**
I tried to deploy an account on sepolia using `sozo account deploy`
it fails with `error: ValidationFailure`

starkli fails too but gives more infos
`
Error: ValidationFailure: perform_validations call failed; failure reason: TransactionFailureReason(code='native_blockifier.PyTransactionExecutionError', error_message='TransactionPreValidationError(TransactionFeeError(MaxFeeTooLow { min_fee: Fee(128528483427250), max_fee: Fee(10673017101630) }))').
`

**Describe the solution you'd like**
Add more infos on error

**Comment by mubarak23** [comment]
I will like to handle this issue

**Comment by vibenedict** [comment]
Can you assign this to me please? @notV4l

**Comment by lambda-0x** [comment]
hey @mubarak23 @vibenedict thank you for interest in this issue, but this will be addressed along with changes in #1887. Feel free to pickup any other issue.
