### ISSUE TITLE
[sozo] Merge `FeeOptions` into `TransactionOptions`

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1887]
**Is your feature request related to a problem? Please describe.**
Merge `FeeOptions` into `TransactionOptions`

`FeeOptions` was added in #1601 and to not block that PR for longer we merge it, but ideally we should use already existing option `TransactionOption` since we already use it in other places, so merge we need to merge both of them into single option `TransactionOptions` which has all features related to configuring the transaction.

**Comment by glihm** [comment]
@lambda-0x this is related to DOJ-366 right? Will assign to you.

**Comment by lambda-0x** [comment]
@notV4l updated issue description for easier understanding, merging both of them would mean we support `--fee-estimation-multiplier` as well.
