### ISSUE TITLE
[sozo] support constructor arguments during deployment

### ISSUE THREAD

**Issue by lambda-0x** [dojoengine/dojo#1888]
**Is your feature request related to a problem? Please describe.**
currently we deploy base contract and replace class hash for actual contract so we cannot use constructor directly.

**Describe the solution you'd like**
use new initializer function that will act as a constructor

**Describe alternatives you've considered**

**Additional context**
arguments of constructor will be given in overlays file and support some kind of variable for contract class hash and contract addresses

**Comment by ebukizy1** [comment]
assign me this will love to work on this

**Comment by lambda-0x** [comment]
@ebukizy1 this feature will be bit involved so will require some architecture changes, so it would be better if someone from team works on this
