### ISSUE TITLE
`get_events` on pending block is always empty

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1896]
**Describe the bug**
When using `get_events` with `to_block = Some(BlockId::Tag(BlockTag::Pending))`, the event page is always empty.

**Expected behavior**
We should return the events of the pending block's transactions.

**Screenshots**
<img width="495" alt="image" src="https://github.com/dojoengine/dojo/assets/7962849/f4256efb-2150-4f30-a798-d2ca9d11e24a">

**Additional context**
The request enters here: https://github.com/dojoengine/dojo/blob/6b6219faf0a53b781b7fd83dabefc8e8f90b5995/crates/katana/rpc/rpc/src/starknet.rs#L453.

Then processed by the sequencer here:
https://github.com/dojoengine/dojo/blob/6b6219faf0a53b781b7fd83dabefc8e8f90b5995/crates/katana/core/src/sequencer.rs#L299

Also, in the new JSON RPC spec, the block number can be `None` for the events of the pending block.

**Comment by tarrencev** [comment]
How do we handle pagination in that case? iirc the cursor schema is up to us, so we would need to include a txn index in it. not sure how we handle this today

**Comment by Larkooo** [comment]
> How do we handle pagination in that case? iirc the cursor schema is up to us, so we would need to include a txn index in it. not sure how we handle this today

I'm not sure how it works but I think it just uses the pending block number (latest block number + 1) alongside the event index?
Here's how it looks with the sepolia node.

<img width="1375" alt="image" src="https://github.com/dojoengine/dojo/assets/59736843/69b57677-4be4-4a08-9ebd-c07e4d7bf564">

**Comment by tarrencev** [comment]
> > How do we handle pagination in that case? iirc the cursor schema is up to us, so we would need to include a txn index in it. not sure how we handle this today
> 
> I'm not sure how it works but I think it just uses the pending block number (latest block number + 1) alongside the txn index + event index? Here's how it looks with the sepolia node.
> 
> As you can see, the events in the EventsPage have a None block_hash and block_number but the cursor still includes the block number.
> 
> <img alt="image" width="476" src="https://private-user-images.githubusercontent.com/59736843/326204821-e60b2464-73b1-4d87-a3bd-975aa549049b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNDc1NTksIm5iZiI6MTcxNDI0NzI1OSwicGF0aCI6Ii81OTczNjg0My8zMjYyMDQ4MjEtZTYwYjI0NjQtNzNiMS00ZDg3LWEzYmQtOTc1YWE1NDkwNDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDE5NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNzJiNDYwMThmOWYwOTFiMzkyZTk1YjkwZmI0MGU1YTg1MTVhNzVmYjJkZTIwNGUyNmRhMTVhNDU4YzBmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NnFvIeR7UhsZhKGL_gLHRxr9qdfimsavFbe_1t2x67Q"> <img alt="image" width="1375" src="https://private-user-images.githubusercontent.com/59736843/326204733-69b57677-4be4-4a08-9ebd-c07e4d7bf564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNDc1NTksIm5iZiI6MTcxNDI0NzI1OSwicGF0aCI6Ii81OTczNjg0My8zMjYyMDQ3MzMtNjliNTc2NzctNGJlNC00YTA4LTllYmQtYzA3ZTRkN2JmNTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDE5NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNGQ1NDk1MGIzNDI2ZWIxZjgzYmIzNzJmNDBhYzE4YzZmOGUyMzAyOTQwNjkyMDc0M2U1YWE3YWJmOGUxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0szuncgwP7gFTrhj2CInwEwy9LQm9yB32ankrrkxFtE">

Ok cool then I think supporting this should be pretty straight forward

**Comment by Larkooo** [comment]
To add on this, this seems to be the issue: https://github.com/dojoengine/dojo/blob/main/crates/katana/storage/provider/src/traits/block.rs#L40

The returned BlockId for the Pending block tag is none, which fallbacks to the latest block number here
https://github.com/dojoengine/dojo/blob/main/crates/katana/storage/provider/src/traits/block.rs#L32

What would be the implications of simply returning the latest_block_number + 1?

**Comment by glihm** [comment]
This is not a Katana bug, it's because the `from_block` must point to the `pending`, and the `to_block` must be `None`.

**Comment by glihm** [comment]
@Larkooo this may be interesting to check if with all the reworks + this change, this may stabilize more the Torii behavior?
