### ISSUE TITLE
[BUG] Docker image won't run on ARM64 systems with non 4KB page size

### ISSUE THREAD

**Issue by xJonathanLEI** [dojoengine/dojo#1913]
**Describe the bug**

Running the official Docker image on any ARM64 systems with non 4KB page size gives a seg fault.

**To Reproduce**

On any ARM64 Linux system (where `getconf PAGESIZE` is _not_ `4096`), run:

```bash
ctr run --rm -t ghcr.io/dojoengine/dojo:v0.7.0-alpha.0 test katana
```

(or with Docker, doesn't matter)

**Expected behavior**

`katana` runs.

**Actual behavior**

```log
<jemalloc>: Unsupported system page size
memory allocation of 16 bytes failed
```

**Additional context**

This is because the default build option in `jemalloc` uses the host page size, even when cross-compiling. See https://github.com/jemalloc/jemalloc/issues/467#issuecomment-2054282344 for details.

The `--with-lg-page` option must be set to fix this.

This affects lots of ARM64 devices like Macs with Apple Silicon and Raspberry Pi 5 running Raspberry Pi OS (Ubuntu on RPI 5 uses 4KB page size so it still works).

**Comment by kariy** [comment]
how should we support this @glihm ? should we do two linux `aarch64` builds, one with 4k and 16k pagesize ?

> This affects lots of ARM64 devices like Macs with Apple Silicon and Raspberry Pi 5 running Raspberry Pi OS (Ubuntu on RPI 5 uses 4KB page size so it still works).

havent tested yet but is it an issue on macs as well? i thought bcs we're building the macos artifacts on a macos runner, it should have the correct pagesize.

if `jemalloc` isn't a requirement, then we can consider doing separate docker build without `jemalloc`.

**Comment by xJonathanLEI** [comment]
Related: https://github.com/eqlabs/pathfinder/issues/1982

**Comment by xJonathanLEI** [comment]
Actually, you _could_ do pagesize-specific images, because while 64KB builds work for everyone and should be the default, devices would gain a small performance benefit running the binary compiled with its own page size. So it might make sense to have, say a `0.7.0` tag that contains a `linux/amd64` image and a `linux/arm64` with 64KB, and then something like `0.7.0-arm64-4kb` for people that _really_ want that little bit of performance.

I haven't benchmarked though so I can't tell what the performance difference is gonna be like. However, it should be pretty clear that the default image should work for everyone, not just a subset of ARM64 devices.

**Comment by kariy** [comment]
> > one with 4k and 16k pagesize
> 
> Please don't do that. ARM64 software builds are not supposed to be pagesize-specific. As long as you compile targeting a 64KB page size it would automatically work on 4K and 16K too. It's just not true the other way around.
> 
> > macos artifacts on a macos runner
> 
> I did say Macs but not macOS (macOS doesn't even support Docker anyways). It's about running Linux on Macs with Apple Silicon via [Asahi Linux](https://asahilinux.org/), which only supports 16KB page size. See [k3s-io/k3s#7335 (comment)](https://github.com/k3s-io/k3s/issues/7335#issuecomment-1518600436). Many other ARM64 devices are 64KB too.
> 
> > separate build for Docker without `jemalloc`
> 
> This is unnecessary though. `jemalloc` itself is not the problem. It's that its default build option targets 4KB. Since Dojo uses `jemalloc` via [`jemalloc-sys`](https://crates.io/crates/jemalloc-sys), you'd just have to set the `JEMALLOC_SYS_WITH_LG_PAGE` to `16` when (cross-)compiling and you should be good.

make sense. thanks for the pointers!

**Comment by kariy** [comment]
i wonder if the change may potentially cause this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1091515 because `katana` is using mdbx for database.

i dont know much about `mmap`/`munmap` so not sure if it could get affected.

**Comment by glihm** [comment]
> how should we support this @glihm ? should we do two linux `aarch64` builds, one with 4k and 16k pagesize ?
> 
> i think configuring the `--with-lg-page` flag should as easy as setting the [`JEMALLOC_SYS_WITH_LG_PAGE`](https://github.com/tikv/jemallocator/tree/main/jemalloc-sys) env var when building `katana`.
> 
> > This affects lots of ARM64 devices like Macs with Apple Silicon and Raspberry Pi 5 running Raspberry Pi OS (Ubuntu on RPI 5 uses 4KB page size so it still works).
> 
> havent tested yet but is it an issue on macs as well? i thought bcs we're building the macos artifacts on a macos runner, it should have the correct pagesize.
> 
> if `jemalloc` isn't a requirement, then we can consider doing separate build for Docker without `jemalloc`.

Thanks for the report @xJonathanLEI. 🙏
Agree, let's definitely go with `64KB` to have higher compatibility. And if in the future we see measurable improvement on Apple Silicon chips, we could have an other build for `16KB` specifically. `4KB` makes little sense to me nowadays.
