### ISSUE TITLE
[ASDF-DOJO] Add steps in official docs page on how to use asdf-dojo plugin

### ISSUE THREAD

**Issue by Jonatan-Chaverri** [dojoengine/dojo#1919]
**Is your feature request related to a problem? Please describe.**
Using asdf-dojo will help developers to better handle multiple versions of dojo locally.

**Describe the solution you'd like**
A step by step guide that informs developers how to use the tool to install dojo.

**Comment by Jonatan-Chaverri** [comment]
I will like to take care of this, in case you guys think we can proceed with it.

**Comment by glihm** [comment]
@Jonatan-Chaverri thanks for issue! I guess this is more something that should be put into the dojo book, no? Or what did you had in mind in the dojo repo?

**Comment by Jonatan-Chaverri** [comment]
You are right! Will create the issue in there! Thanks
