### ISSUE TITLE
Add support for SQL queries

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1920]
**Is your feature request related to a problem? Please describe.**
graphql is nice but sql would allow more complex querying

**Describe the solution you'd like**
expose a SQL endpoint with restricted permissions

**Comment by mubarak23** [comment]
@notV4l kindly assign this issue to me

**Comment by mubarak23** [comment]
can you also explain the issue further and where the implement will be done in the code

**Comment by glihm** [comment]
Done in #2714 and previous integration of sql endpoint.
