### ISSUE TITLE
[sozo] ability to skip migration for certain contracts

### ISSUE THREAD

**Issue by lambda-0x** [dojoengine/dojo#1924]
**Is your feature request related to a problem? Please describe.**
In some cases users build certain contracts for testing or other uses and those are not required to be migrated, currently sozo just checks all the compiled artificats to figure out which to deploy

**Describe the solution you'd like**
Have a configuration of list of contracts to exclusively not migrate inside `tool.dojo`

**Describe alternatives you've considered**
We can also have a flag in compiled artifact specifying if they need to be migrated or not

**Comment by glihm** [comment]
For now let's just add a `ignore_for_migration` into the `tool.dojo.env` entry of the `Scarb.toml`.
This would allow users to define ignored contracts for migration based on specific profiles.
