### ISSUE TITLE
[sozo] `sozo build --stats` Bytecode size displayed

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1952]
**Is your feature request related to a problem? Please describe.**
Bytecode size displayed by `sozo build --stats` is sierra bytecode size https://github.com/dojoengine/dojo/blob/6dca9446b3894422b559dd86a43cf53abbe723ae/crates/sozo/ops/src/statistics.rs#L24

MAX_BYTECODE_SIZE limitation is related to casm bytecode size
https://github.com/dojoengine/dojo/blob/6dca9446b3894422b559dd86a43cf53abbe723ae/crates/dojo-world/src/migration/mod.rs#L35
https://github.com/dojoengine/dojo/blob/6dca9446b3894422b559dd86a43cf53abbe723ae/crates/katana/primitives/src/utils/class.rs#L32

**Describe the solution you'd like**
Display casm bytecode size as well

Also sort the contracts alphabetically

**Comment by fishonamos** [comment]
Although a Go background, I can experiment on this?

**Comment by lambda-0x** [comment]
@fishonamos we need to also make some other changes along with this, so it will be a non-trivial issue. i will take this up.

**Comment by fishonamos** [comment]
No problem. I am available for others issues if open. Just tag me.
