### ISSUE TITLE
[sozo] add an option to generate overlay files if they don't exist

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#1992]
**Is your feature request related to a problem? Please describe.**
Overlay files are not generated by default. So the user must sometimes create folders and files manually.

**Describe the solution you'd like**
We should add a `--create-overlays` option that will create the overlays files at the right location, with the required content. Default content is only the `name` key that must match the contract's name.

**Comment by notV4l** [comment]
i think we should add all the file structure not only name field otherwise its half useless
