### ISSUE TITLE
[dojo-lang] Invalid plugin diagnostic

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1997]
**Describe the bug**
The following enums
https://github.com/dojoengine/dojo/blob/35ca97454678ab5e91aa31b53f372ddc914b88de/crates/dojo-lang/src/plugin_test_data/introspect#L228-L240

Give those errors
https://github.com/dojoengine/dojo/blob/35ca97454678ab5e91aa31b53f372ddc914b88de/crates/dojo-lang/src/plugin_test_data/introspect#L2997-L3006

**Expected behavior**
should not raise `error: To be packed, all variants must have exactly the same layout.`

**Additional context**
0.7.0-alpha.4

**Comment by remybar** [comment]
Thanks for the report !
It should be fixed now, in `0.7.0-alpha.4`.

**Comment by glihm** [comment]
@notV4l please feel free to re-open on need, but as checked together, it should be fixed and all struct down the tree must have the `IntrospectPacked` derived.
