### ISSUE TITLE
Figure out how Cairo plugins are intended to work

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#2]
Right now, the `cairo-lang-dojo` plugin follows the implementation of the [cairo-lang-starknet](https://github.com/starkware-libs/cairo/tree/main/crates/cairo-lang-starknet) plugin. It is unclear exactly how the starkware team ultimately intends for plugins to be integrated into the pipeline.

The language database at https://github.com/dojoengine/dojo-beta/blob/main/crates/cairo-lang-dojo/src/db.rs defines the compilation pipeline.

Currently, the base [`derive` plugin](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-plugins/src/derive.rs) consumes all derive macros so the full compilation pipeline doesn't work (the `#[derive(Component)]` macro is consumed before the dojo plugin). I'm not sure if there is a different plan for defining custom derive expansions?

Currently, the simplest architecture is probably to do something similar to what the existing test does and output a starknet contracts which can be passed to the starknet compiler.

**Comment by ponderingdemocritus** [comment]
Can we close this?

**Comment by tarrencev** [comment]
I think it is still an open question on what this ultimately looks like. Our current approach is kind of a hack
