### ISSUE TITLE
[BUG] [dojo-bindgen] [unity] Generated actions methods try to call `FieldElement`s in `calldata`

### ISSUE THREAD

**Issue by trevis-dev** [dojoengine/dojo#2008]
**Describe the bug**
`bindgen` will generate code trying to call `Inner` on systems `calldata` elements.

**To Reproduce**
1. clone `dojo-starter`
2. run `sozo build --unity`
3. Inspect `Actions`'s `Move` in `dojo_starter::systems::actions::actions.gen.cs` which shows
```cairo
calldata = new dojo.FieldElement[] {
    new FieldElement(direction).Inner()
}
```
Which doesn't compile.

**Expected behavior**
The resulting code should be 
```diff
-    new FieldElement(direction).Inner()
+    new FieldElement(direction).Inner
```

**Additional info**
It seems that `format_system` always formats `calldata` with `FieldElement({}).Inner()` https://github.com/dojoengine/dojo/blob/010444fa3797429a4903b3e480956e2df8ea3153/crates/dojo-bindgen/src/plugins/unity/mod.rs#L209-L234

I'm guessing it should probably just be `Inner` everywhere. If confirmed, I'd be happy to make a PR.

**Comment by jancris100** [comment]
Hi I would like to work on this
