### ISSUE TITLE
[BUG] toolchain README Documentation link is broken

### ISSUE THREAD

**Issue by taikoonwang** [dojoengine/dojo#2035]
**Describe the bug**
https://github.com/dojoengine/dojo/pull/1523  update dead links 
but dojobook toolchain part seems update

1. for every part(eg.katanta)  overview page point to https://book.dojoengine.org/toolchain/katana, not `katana/overview`
2. toolchain every part have overview, but missing general overview, so in `dojoup/README.md`   `[Documentation](https://book.dojoengine.org/toolchain/dojoup)` is missing

**To Reproduce**
just open link 

**Expected behavior**

**Screenshots**
<img width="429" alt="image" src="https://github.com/dojoengine/dojo/assets/171847349/8794a5e9-619f-4668-a44f-b6e442e043a8">

**Additional context**

**Comment by glihm** [comment]
Closed in #2036.
