### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mouseinc254** [dojoengine/dojo#2047]
# sozo build error

I have been stuck for hours building my first dojo using the `sozo build` command. With no background in Rust, I did not know that Cargo was a requirement to install some of the sozo dependencies. Include this in the documentation:

```If you are running Dojo with no cargo installed, ensure you have installed it. Use this command
>. Use the same command if you get an error message ```
```

**Comment by MariangelaNM** [comment]
Hi, i would like work in this issue.

**Comment by MariangelaNM** [comment]
Perfect, I'll work on it.

**Comment by MariangelaNM** [comment]
Hi, this is the pull request.I am waiting for your feedback.
Thanks
https://github.com/dojoengine/book/pull/299

**Comment by glihm** [comment]
> Hi, this is the pull request.I am waiting for your feedback. Thanks [dojoengine/book#299](https://github.com/dojoengine/book/pull/299)

Moved to the book.
