### ISSUE TITLE
[torii] Model named Table breaks torii

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#2057]
repost from dojo.js

### Dojo.js Version

0.7.0-alpha.2

### What happened?

A model named `Table` raises an error on `getSyncEntities()`, preventing it to successfully sync:

```
failed to get entities: status: Internal, message: "error returned from database: (code: 1) near \"Table\": syntax error", details: [], metadata: MetadataMap { headers: {"content-length": "0", "content-type": "application/grpc-web+proto"} }
```

### What is the expected behavior?

The name of a model or field should not break Torii

### Steps to reproduce

* Create a model named 'Table' on dojo-starter
* Migrate
* Open some example that syncs using `getSyncEntities()` like `react-app`
* Monitor the console as the page loads, the error should be there.

Or use [this branch](https://github.com/underware-gg/pistols/tree/84674df1ddc6a6810b1b94fbcb0ec88279f80af8)
* Build and migrate on `/dojo`
* `pnpm run dev` on `/client`
* Open `http://localhost:3000/gate`
* Monitor the console as the page loads, the error should be there.

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by rsodre** [comment]
Upgraded to Dojo `0.7.1`, renamed by model back to `Table`, and the problem persists:

<img width="975" alt="Screenshot 2024-06-18 at 15 34 39" src="https://github.com/dojoengine/dojo/assets/229161/67399fcf-1a22-4ef3-b24e-e6fe15cf05e0">
