### ISSUE TITLE
Add support for `2023_11` edition

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#2092]
Currently Dojo is not supporting this edition, meaning that none of the `pub` keyword and logic can be applied.

The migration to this new and better structured edition is important, but this will definitely break a lot's of projects that will need to update all the codebase to correctly expose functions and types.

**Comment by abdegenius** [comment]
I can look into this for you

**Comment by glihm** [comment]
> I can look into this for you

Appreciate your will to contribute man! I've this issue assigned to me as this will be tackled in an on-going refactoring.

Any other open issue you may be interested in?

**Comment by glihm** [comment]
will be done after #2159 is merged.

**Comment by glihm** [comment]
@remybar if you could comment, I'll assign to you during the rework of the world. 👍

**Comment by remybar** [comment]
yes 👍

**Comment by glihm** [comment]
Closed by #2179.
