### ISSUE TITLE
Deprecate package name for profile usage

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#2109]
**Is your feature request related to a problem? Please describe.**
Dojo is using the package name as the default seed for the world. This poses the problem that when profiles are used, the seed is not easily configurable.

**Describe the solution you'd like**
The proposal here is to move the seed to the `tool.dojo.world`, to actually have this configurable by profile. This will enable users to deploy several worlds with different name on the same network, and keeping track of the changes into their manifests system.

**Comment by Villegas2003** [comment]
Hello @glihm, I see that this issue was created recently and does not yet have an assignment. Could I collaborate on it?

**Comment by glihm** [comment]
> Hello @glihm, I see that this issue was created recently and does not yet have an assignment. Could I collaborate on it?

Hey! So this issue should be tackled in the branch `feat/namespace`. The goal here we need to discuss is the following:

1. Using an other entry to have a way to generate a seed for the world. For now we use the package name but this is not something we want to keep as mentioned in the description. I think `seed` could be a good name.
2. Then, we need an entry for the default namespace to be used, `default_namespace` should be ok.

This work must be done derived from the `feat/namespace` branch.

@remybar @lambda-0x could you both confirm this?

This will enable the devs to actually define some specificities about the world by profile, instead of being stuck by the package name being not profile specific.

This issue require a bit of Dojo knowledge, if you want to have a look until the guys confirm. Also, could you reach out to me on the Dojo discord please? :)

**Comment by lambda-0x** [comment]
yes sounds good to me.

> Then, we need an entry for the default namespace to be used, default_namespace should be ok.

maybe we can just use `namespace` here

**Comment by glihm** [comment]
@Villegas2003 if you're feeling ok with that, you can jump on a PR to dive into the code base and add a `namespace` entry to the Scarb.toml and support it. 👍

You should start this work on the `feat/namespace` branch. @lambda-0x is tackling the `seed`.

**Comment by Villegas2003** [comment]
Thank you for the detailed instructions, @glihm. 
I am excited to get started on this. I will begin working on the feat/namespace branch to add the namespace.

I have some knowledge of Dojo, but I might need some guidance as I go along. I'll also reach out to you on the Dojo Discord for any specific questions.

Thanks again for this opportunity!

**Comment by glihm** [comment]
Done in #2135.
