### ISSUE TITLE
Add contract registry to the world

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#2111]
#1956 was a first good work to get the contract registry. This should be integrated in the namespace work, which will ease this integration.

Basically, we need to enable the world to keep track of the contracts that are registered, to be callable from other contracts without knowing the address in advance.

Doing so, one can easily access a contract's address form the world without hard-coding the address.
We could also add a layer of permission here, with the `writer` permission, or adding an `executor` permission, to kind of control which contract can call which contract, which unlocks some new horizons.

**Comment by Villegas2003** [comment]
Hi @glihm ,

I'm a software developer and a student at Universidad Cenfotec, as well as a strong interest in blockchain technology.

I'd like to contribute to the project by working on this issue. Could you please assign it to me if it's still available?

**Comment by glihm** [comment]
@Villegas2003 thank you for the interest in Dojo, this issue is being worked on currently. Please don't hesitate to check other unassigned issue. :)

**Comment by Villegas2003** [comment]
Thank you very much @glihm , I will be reviewing the other issues to check their availability and to be able to collaborate with help
