### ISSUE TITLE
[BUG] [TORII]`updated_at` not updating

### ISSUE THREAD

**Issue by edisontim** [dojoengine/dojo#2117]
**Describe the bug**
Whenever an entity is updated in cairo, the `updated_at` field of the entity in the graphQL should be updated, however I'm noticing this value isn't being changed and just keeping the `created_at` value. `executed_at` is updated, however it's also slightly off from the `created_at` just after creating an entity

**To Reproduce**
- Create an entity -> different values for `executed_at` and `created_at` 
- Modify the entity -> `updated_at` stays the same timestamp as `created_at`

**Expected behavior**
As I understood it, at creation `executed_at` and `created_at` would've been the same, and `updated_at` should change whenever the entity is updated. But my understanding could be skewed 

**Screenshots**
At creation
<img width="292" alt="Screenshot 2024-06-27 at 22 53 32" src="https://github.com/dojoengine/dojo/assets/76473430/0d0641d7-2865-4680-bf70-7e6a275e7b13">
After update
<img width="293" alt="Screenshot 2024-06-27 at 22 54 32" src="https://github.com/dojoengine/dojo/assets/76473430/3059a028-e7b6-47ad-ade3-731a152cdc98">

**Comment by abdegenius** [comment]
can i be assigned this issues, let me tackle it!

**Comment by glihm** [comment]
Thanks for the issue! Fixed in #2118.

**Comment by edisontim** [comment]
Much appreciated!
