### ISSUE TITLE
try_entity() returns double wrapped option

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#212]
It looks like I have to unwrap again after `expect`. Can we just return component?
```
let maybe_game = commands::<Game>::try_entity(game_id.into());
let game = maybe_game.expect('no game found');
let game = game.unwrap();  
```

The `entity` api is really nice though

**Comment by tarrencev** [comment]
Ah good catch!

We should update this line

https://github.com/dojoengine/dojo/blob/abacf55b7c393f794815b95cc849faf64aa6f8a2/crates/dojo-lang/src/commands/entity.rs#L152

to be

```
format!("({})", part_names.join(".unwrap(), "))
```
