### ISSUE TITLE
Add support for signed integers

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#2120]
**Is your feature request related to a problem? Please describe.**
Signed integers are present in The Cairo Core lib, and should be supported by Dojo.

**Describe the solution you'd like**
This issue can be split in 3 tasks:
- [ ] Implement the `Introspect` trait on all signed integers. As Cairo is using `251` bytes to store signed values, **we must not packed them**. Hence, the layout is always `Fixed` with `251` like a `felt252`.https://github.com/dojoengine/dojo/blob/ed0c67737996d24f3cd326fd360d7aec67a18c9c/crates/dojo-core/src/database/introspect.cairo#L63
- [ ] Add the types to `dojo-types` to ensure `Primitives` are aware of those new types.https://github.com/dojoengine/dojo/blob/ed0c67737996d24f3cd326fd360d7aec67a18c9c/crates/dojo-types/src/primitive.rs#L24
- [ ] On `Sozo`, a new type must implement `CallDataDecoder` to actually decode the signed integers with the `-` prefix.

@Larkooo for Torii, I think this could be an other PR, because Protos and gRPC/GraphQL will be affected, correct? At the SQL level, it should be good.

**Comment by EjembiEmmanuel** [comment]
@glihm can I work on this?

**Comment by glihm** [comment]
> @glihm can I work on this?

Let's go, thank you for the will to contribute! If you have any question please let's know, here or you can reach out on Dojo discord channel.
If you have any blockers, also don't hesitate to comment on them.

**Comment by EjembiEmmanuel** [comment]
> > @glihm can I work on this?
> 
> Let's go, thank you for the will to contribute! If you have any question please let's know, here or you can reach out on Dojo discord channel. If you have any blockers, also don't hesitate to comment on them.

Sure will. Thanks!
