### ISSUE TITLE
[BUG] Torii wrong tx status in pending block

### ISSUE THREAD

**Issue by bal7hazar** [dojoengine/dojo#2123]
**Describe the bug**

Torii considers a successful tx within the pending block to be failed, so the tx not indexed.

**To Reproduce**

Appears randomly, didn't figure out how to reproduce it, probably something related to the Starknet sequencer.

**Expected behavior**

The latest tx status should be considered assuming it could be another status for a short period of time.

**Screenshots**

> slot deployments logs paved-sepolia-v2 torii -l 1000

[sepolia-logs.txt](https://github.com/user-attachments/files/16044910/sepolia-logs.txt)

line 970:
> [2m2024-06-30T13:50:14.876296Z[0m [33m WARN[0m [2mtori_core::engine[0m[2m:[0m Ignored failed pending transaction. [3mtransaction_hash[0m[2m=[0m0x2ff6a5a3b206c3f168b9ad1535cd3c8d72e3fe74b91c99747630044079ac52b

**Additional context**

Here the corresponding tx (success): 
https://sepolia.voyager.online/tx/0x2ff6a5a3b206c3f168b9ad1535cd3c8d72e3fe74b91c99747630044079ac52b

**Comment by zarah-s** [comment]
I'll like to hop on this
