### ISSUE TITLE
Sozo init remove git 

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#2128]
Currently sozo creates a git project when `init` is called.

**Desired effect**
Running `sozo init` should not create a git project, as the user might be using this in a mono repo. Even if the user is not, it's best practice to not include git.

**Comment by EjembiEmmanuel** [comment]
@ponderingdemocritus I'd love to work on this

**Comment by lambda-0x** [comment]
i think we can add a `--no-vcs` argument which doesn't initialize a git repository similar to cargo and scarb and by default still create a git repository, wdyt @ponderingdemocritus?

**Comment by lambda-0x** [comment]
@EjembiEmmanuel lets wait for loafs reply you can start working after we decide whats the best way to handle it.

**Comment by EjembiEmmanuel** [comment]
> @EjembiEmmanuel lets wait for loafs reply you can start working after we decide whats the best way to handle it.

Alright, thanks!

**Comment by ponderingdemocritus** [comment]
I think by default it shouldn't make a git. Maybe just me, but my dojo apps always are mono repos of client and contracts. Which means i always have to force remove the git, which is annoying.

**Comment by EjembiEmmanuel** [comment]
Alright, got it!

**Comment by glihm** [comment]
> I think by default it shouldn't make a git. Maybe just me, but my dojo apps always are mono repos of client and contracts. Which means i always have to force remove the git, which is annoying.

we could have by default without git, and we may add a `--git` option to enable it. @EjembiEmmanuel sounds good for the implementation of such behavior?
@lambda-0x @ponderingdemocritus if you both agree, let's go this way.

That's true that most of the time, in hackathons or other, people are doing mono repos with both contracts and front-end in the same one.

**Comment by lambda-0x** [comment]
okay if most people use it in monorepo then not having git enabled by default makes more sense.
