### ISSUE TITLE
Bad Cairo source file content stored in model metadata

### ISSUE THREAD

**Issue by remybar** [dojoengine/dojo#2137]
**Describe the bug**

When a Dojo project is compiled, some artifact files are produced in `target/<profile_name>/models`. Some of these artifacts are the Cairo source code used to build the corresponding model contract. These artifacts are then uploaded as model metadata during the project migration.

For example, in the `spawn-and-move` example, `target/dev/models/dojo_examples-Position-1e145e26.cairo` should contain the Cairo code of the `Position` model Starknet contract.

Unfortunately, at the moment, this source file only contains the original Cairo file. That means, the model contract is not visible at all, only the `struct` of the model is visible, which is useless.

**To Reproduce**

Just build the `spawn-and-move` project.

**Expected behavior**

Ideally, this source file should only contain the full model contract Cairo code, **after code expansion done through Dojo plugins**. But, as it might be complicated to isolate this part of code from a Cairo file containing several models, this source file should at least contain the corresponding full Cairo source file **after code expansion**.

**Additional context**

This part is done in the `save_expanded_source_file` function of `crates/dojo-lang/src/compiler.rs`. A lot of `db`/`module_id` methods are available to access to real/virtual files so it might be quite tricky to find the right way to handle this point.

Note that everything works fine for Dojo contract.

**Comment by Ppixelbro** [comment]
Hello @remybar and @glihm,

I would like to help with this issue. Please assign it to me.

Thanks!

**Comment by glihm** [comment]
@Ppixelbro thanks for the interest in contributing here! We've some check on the compiler side that needs to be realized first. This may delay this issue and @remybar will probably tackle it as it's bounded to something he is working on currently.

We should have some new good first issue coming soon.

**Comment by Ppixelbro** [comment]
Thank you for the update, @glihm  I'll keep an eye out for new issues. If there's anything else I can help with in the meantime, please let me know.

**Comment by glihm** [comment]
Done in #2175.
