### ISSUE TITLE
Update `starknet-rs` to use `starknet-types-core` `Felt` type

### ISSUE THREAD

**Issue by tcoratger** [dojoengine/dojo#2177]
With the recent merge of [starknet-rs PR #562](https://github.com/xJonathanLEI/starknet-rs/pull/562), it is now possible to update the project to the latest version of starknet-rs. 

This update is particularly beneficial as it facilitates the migration from `arkworks` `FieldElement` to `Felt` types provided by `starknet-types-core`.

## Benefits
- Improved Compatibility: by using the `Felt` type from `starknet-types-core`, the codebase will be more aligned with the latest developments in the `starknet-rs` library.

## Changes
- Dependency Update: Updated the starknet-rs dependency to the latest version.
- Type Migration: Replaced instances of arkworks `FieldElement` with `starknet-types-core` `Felt` type throughout the codebase.

**Comment by EjembiEmmanuel** [comment]
@tcoratger I'd love to work on this as I'm already working on something related  here https://github.com/dojoengine/dojo/pull/2161

**Comment by EjembiEmmanuel** [comment]
> the project is already migrated to use the new `Felt` type since #2126 but we're using a patch for `starknet-rs` while waiting for some upstream PRs to be merged. But now that [xJonathanLEI/starknet-rs#615](https://github.com/xJonathanLEI/starknet-rs/pull/615) has been merged, we may removed the patch and use rev [6a9f124](https://github.com/xJonathanLEI/starknet-rs/commit/6a9f124bf9d973f27360e72bb486576beb7b53a2) but there are some breaking changes need to be resolved possibly caused by [xJonathanLEI/starknet-rs#617](https://github.com/xJonathanLEI/starknet-rs/pull/617).

oh okay
