### ISSUE TITLE
Regroup dojo configuration in one file

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#2193]
**Is your feature request related to a problem? Please describe.**
With `1.0` alpha and introduction of namespaces and overlay in an earlier version, the configuration of Dojo is now being split over different folders/files.

This makes it harder to maintain, and not easy to overview the whole world configuration.

**Describe the solution you'd like**
Based on this observation, we're leaning toward regrouping the dojo configuration in one central file: `Dojo.???`.

This file should be put at the root of each Dojo project, alongside the `Scarb.toml` of the world to deploy.

The configuration must contains:
1. Overlays
2. Namespaces mappings
3. Dojo specific environment variables

The support for profiles must also be present.

Starknet Foundry is using a [`snfoundry.toml` file](https://foundry-rs.github.io/starknet-foundry/projects/configuration.html). We've to check how this file is integrated with `Scarb.toml`. If automatic merges are supported, we should go with way with a `Dojo.toml` file which will be alongside the `Scarb.toml` file.

Let's brainstorm on this and land this configuration file for `1.0`.

**Comment by kariy** [comment]
I think this would be a good opportunity to introduce a 'workspace' type (like Scarb's `Workspace<'_>` type) that holds all of Dojo's configurations/manifests, and can easily be passed around throughout the cli. cc @lambda-0x

**Comment by glihm** [comment]
Closed by #2201.
