### ISSUE TITLE
Homogenize the permission API

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#2221]
**Is your feature request related to a problem? Please describe.**
Currently the world has some API that are confusing like here:
https://github.com/dojoengine/dojo/blob/ea1b6a86945944ae3b1e969a29911ba17f78a7b8/crates/dojo-core/src/world/world_contract.cairo#L41-L50

**Describe the solution you'd like**
Adjust the API of the world to use the resource first and then the address that must be granted/revoked (as it is for `is_writer` for instance).

**Additional context**
Such change seems small, but it must be propagated to the whole stack, mostly `sozo` which is directly using this API.

**Comment by fishonamos** [comment]
Kindly assigned @glihm

**Comment by remybar** [comment]
I'm on it 👍

**Comment by glihm** [comment]
Done in #2224.
