### ISSUE TITLE
Sozo init should clone the correct version of starter template

### ISSUE THREAD

**Issue by lambda-0x** [dojoengine/dojo#2222]
**Describe the bug**
At the moment sozo clones the `dojo-starter` repo which the latest commit. But we should clone a specific branch according to the version of sozo being used, so user doesn't end up having the wrong template.

**To Reproduce**
Doing `sozo init` on any older version of sozo.

**Expected behavior**
It should clone a specific git tag which is the dojo (i.e. sozo) version being used. we would also need to start tagging correct versions in [dojo-starter](https://github.com/dojoengine/dojo-starter) repo moving forward.

**Comment by EjembiEmmanuel** [comment]
@lambda-0x can I work on this?

**Comment by lambda-0x** [comment]
sure, done! @EjembiEmmanuel
