### ISSUE TITLE
Torii client compile error when importing v1.0.0-alpha.3 release

### ISSUE THREAD

**Issue by elton-cs** [dojoengine/dojo#2225]
**Describe the bug**
Getting the following error:
```
error[E0432]: unresolved import `starknet::core::types::FromStrError`
 --> /Users/zkelton/.cargo/git/checkouts/dojo-10cac2e09298cf35/a6a7724/crates/dojo-types/src/packing.rs:6:35
  |
6 | use starknet::core::types::{Felt, FromStrError};
  |                                   ^^^^^^^^^^^^
  |                                   |
  |                                   no `FromStrError` in `types`
  |                                   help: a similar name exists in the module: `FromUtf8Error`
```
when tagging the torii-client crate to the v1.0.0-alpha.3 release.

**To Reproduce**
Import torii-client in a new rust project by adding the following line to `Cargo.toml` under dependencies:
```
torii-client = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.0-alpha.3" }
```

**Expected behavior**
Project should compile. This issue is not present on the 0.7.4 release.

**Additional context**
I suspect the issue comes from #2200

**Comment by elton-cs** [comment]
Hey @glihm, as you mentioned, adding the following starknet-core patch into the project's`Cargo.toml` fixes the issue:
```
[patch.crates-io]
starknet-core = { git = "https://github.com/kariy/starknet-rs", branch = "dojo-patch" }
```

**Comment by glihm** [comment]
Thanks for the feedback and will update when we bumped versions that don't need a patch. 👍
