### ISSUE TITLE
feat(world): make fields as keys in events where possible

### ISSUE THREAD

**Issue by lambda-0x** [dojoengine/dojo#2228]
Since having fields as keys can help retrieving events more granular.

In future torii might benefit from this when we add features like whitelist based models/system indexing.

**Comment by remybar** [comment]
Hi @lambda-0x !
Do you mean adding `#[key]` attribute on event struct fields in the world contract when it makes sense to do it ?

**Comment by lambda-0x** [comment]
yes, exactly!

**Comment by ScottyDavies** [comment]
Hello @lambda-0x, please can i work on this?
