### ISSUE TITLE
Events annotated by `#[dojo::event]` are not annotated as event in ABI

### ISSUE THREAD

**Issue by lambda-0x** [dojoengine/dojo#2233]
**Describe the bug**
Sozo events subcommand uses the ABI to parse the events, but since custom dojo events are not annotated sozo currently cannot parse them.

Once this issue is fixed we need to update sozo accordingly so it can parse those events. Also note in dojo events we add the system address which emitted it as the key in event ourself, that also needs to be considered.

**Comment by glihm** [comment]
To solve this, we should add a "phantom" method on models that are `dojo::event` to ensure we have a way to determine that from the ABI.

**Comment by glihm** [comment]
Events are now emitted differently than before, with their own ABI file, and they are not starknet event anymore. 👍
