### ISSUE TITLE
Update syntax to support explicit indexing

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#224]
Currently, all components are indexed which adds additional storage overhead.

The component syntax should be updated to support explicitly setting a component to be indexed. We could use an attr and expose an `is_indexed` method on the generated contract class.

For example:

```
#[derive(Component)]
#[component(indexed = True)]
struct Position {
    x: felt252,
    y: felt252
}
```

Generates:

```
#[contract]
mod PositionComponent {
   ...
    #[view]
    fn is_indexed() -> bool {
        bool::True(())
    }
}
```

**Comment by ponderingdemocritus** [comment]
This is an elegant solution - I can tackle in about 24hrs if no one else is
