### ISSUE TITLE
Expose `resources` map in world API

### ISSUE THREAD

**Issue by lambda-0x** [dojoengine/dojo#2244]
**Is your feature request related to a problem? Please describe.**

Currently given a selector we would need to call both of this methods individually to figure out if a selector belongs to a contract or a model. And also currently its not possible to figure out other kind of resources given a selector because there is no method for them.

https://github.com/dojoengine/dojo/blob/566ad6c11be19eb8b506c51008f58e212da7cd9e/crates/dojo-core/src/world/world_contract.cairo#L641-L653

**Describe the solution you'd like**

It would be better if we have access underlying `resources` map directly, so we can just have one method which can be used for all the type of resources.

**Describe alternatives you've considered**

Instead of replacing those methods we can keep one for each resource type (i.e. `fn namespace`, `fn contract`, `fn model`, etc..) along with the generic resource method (i.e. `fn resource`) but i am not sure if keeping the individual ones is really helpful since user can just use the generic method and handle the detecting of resource type themself. 

**Additional context**

Once this feature is available in world api we can use it in sozo [here](https://github.com/dojoengine/dojo/blob/566ad6c11be19eb8b506c51008f58e212da7cd9e/crates/sozo/ops/src/migration/migrate.rs#L904-L908), atm we generate the map from manifests present locally. But it would be better to just ask the world directly for this information especially since a system can have permissions of model that are defined outside of the project.

**Comment by glihm** [comment]
@remybar this is the one I evoked earlier today, @lambda-0x did an issue describing the behavior. 👍

**Comment by remybar** [comment]
Yes, good idea 👍 
I would keep `model()` and `contract()` for the moment so if you are sure that the selector is a model selector, you can just directly call `model()` and get the class_hash/address without adding a `if let` or a `match` :)

**Comment by lambda-0x** [comment]
i generally prefer to have a single way to do a thing so its less confusing for users/less code to maintain :), but not against keeping them if everyone wants them.

**Comment by remybar** [comment]
> i generally prefer to have a single way to do a thing, so its less confusing for users/less code to maintain :), but not against keeping them if everyone wants them.

Yes, I agree. I'm ok to remove them 👍

**Comment by glihm** [comment]
closed in #2266.
