### ISSUE TITLE
testing: dump state and initialize katana from dumped state for test runner

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#2270]
most of the testings that we do for sozo (and others as well), requires setting up katana with the `spawn-and-move` example project. essentially, the tests would require us to do the full world migration which entail sending bunch of txs just to initialize katana with the desired state to test against. majority of the time spent in the ci, is this initialization phase. 

we can use genesis config for this, but to use the genesis config currently would require us to hardcode all of the values. we have no way to automate this process, and doing it manually can be an error-prone process. katana doesn't provide a utility to dump its current state in the genesis config format, which would be useful to implement this approach.

another solution that we thought about is to just store the database directory (ie the directory that gets generated when you use `--db-dir`) in the repo, then we just start katana with it. which would pretty much be the ideal solution, but we had some concern on the initial db reserved size of 4Gb that might be an issue with the limited capacity of the github ci runners we're using.

**Comment by kariy** [comment]
notes on mdbx initial reserve size:

mdbx uses [`ftruncate`](https://pubs.opengroup.org/onlinepubs/007908799/xsh/ftruncate.html) to reserve the initial size, which doesn't actually takes up that amount of physical storage. when read, this uninitialized space appears as zero bytes, but it doesn't actually consume disk space until it gets written to.

the actual size of a fresh katana instance with default genesis state is only around ~3 megabytes.

**Comment by glihm** [comment]
Closed in #2271.
