### ISSUE TITLE
[BUG] `sozo init` command no longer works as documented 

### ISSUE THREAD

**Issue by princeibs** [dojoengine/dojo#2273]
**Describe the bug**
Running the command `sozo init project-name` now creates a git repository in the project by default. The expected behaviour (according to [the documentation](https://book.dojoengine.org/toolchain/sozo/project-commands/init)) is to create a git repository only when the `--git` option is passed in.

**To Reproduce**
- Run the command in your terminal:
```
sozo init project-name
```

**Expected behavior**
The command is expected to create the project without a git repository.

**Screenshot**
- Sozo version 
<img width="243" alt="image" src="https://github.com/user-attachments/assets/21dc3461-5c0e-49d9-860d-59ed4a2a578d">

**Comment by EjembiEmmanuel** [comment]
@princeibs upgrade your dojo version and try again

**Comment by lambda-0x** [comment]
it was introduced with this commit: https://github.com/dojoengine/dojo/commit/b2a4df6c7d8e9da9a07bbe4a356dfd11a2696cfb

which got released with `1.0.0-alpha.0`

**Comment by princeibs** [comment]
I think the docs needs to be updated to reflect the update because the docs version I am reading actually matches the dojo version I have installed 
<img width="601" alt="image" src="https://github.com/user-attachments/assets/54256b92-f0ba-4e7e-85f2-2c096f81f7e1">

**Comment by glihm** [comment]
Should be closed by #2262.
