### ISSUE TITLE
Support defining world deployments in manifest

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#228]
Developers should be able to easily deploy worlds to different chains, for example, devnet, testnet, mainnet etc.

Currently, we have a attribute defined in the Scarb tool manifest:

https://github.com/dojoengine/dojo/blob/8d5daf11e4b55e648d232d97d3fd0ad895f0c331/examples/Scarb.toml#L17

It's not particularly well thought out though. We probably want to namespace it by `env`:

```
[tool.dojo.env.testnet]
rpc = "https://rpc.testnet.starkware.co"
```

and allow users to configure various parameters to handle the deployment to that env, for example, `rpc`, `private_key_env`, `account_address` etc.

From the command line, the developer should be able to define an env as an arg, for example: `dojo migrate --env testnet`

**Comment by kariy** [comment]
Can the `env` name be arbitrary, or we check for reserved keywords like `testnet`, `mainnet`, `devnet` only?
