### ISSUE TITLE
Error msg potentially too long

### ISSUE THREAD

**Issue by milancermak** [dojoengine/dojo#229]
The `'Failed to deserialize $component$'` error message - part of the [entity command](https://github.com/dojoengine/dojo/blob/main/crates/dojo-lang/src/commands/entity.rs#L90) plugin - is potentially too long if an entity name is greater than 9 characters. Max short string len in Cairo is 31. The substring "Failed to deserialize " is 22 characters already. Someone, sooner or later, is going to hit this limit.

**Comment by tarrencev** [comment]
Should we just truncate?

**Comment by milancermak** [comment]
Sounds like a plan
