### ISSUE TITLE
Build cairo language server with Dojo plugin

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#23]
Currently the cairo language server doesn't support dynamic plugin configuration. In the short term, we should create a crate that wraps it and incorporates the dojo plugin.

Basically, we need to copy this file and include the dojo plugin before the starknet plugin:

https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-language-server/src/bin/language_server.rs#L18

**Comment by msaug** [comment]
I'm down to start with this one tomorrow :)

**Comment by msaug** [comment]
https://github.com/dojoengine/cairo/pull/1

**Comment by msaug** [comment]
Completed [here](https://github.com/dojoengine/cairo/pull/1)
