### ISSUE TITLE
feat: conditionaly import ArrayTrait in system

### ISSUE THREAD

**Issue by milancermak** [dojoengine/dojo#230]
It's very well possible to write a `#[system]` that does not "visibly" use an `Array` but does e.g. `commands::set_entity`. When that gets expanded, it creates a `let mut calldata = ArrayTrait::new()` and later on does `calldata.span()`. If the system does not do `use array::ArrayTrait`, we get an error:

```sh
error: Plugin diagnostic: Method `span` not found on type "core::array::Array::<core::felt252>". Did you import the correct trait and impl?
 --> ERC20Mint:46:128
                        IWorldDispatcher { contract_address: world_address }.set_entity('Supply', token.into(), 0_u8, calldata.span());
                                                                                                                               ^**^
```

It would be great if the plugin could detect if the `ArrayTrait` is already present and if not, import it in the generated code.

**Comment by tarrencev** [comment]
I think we should rather fully quality it like `array::ArrayTrait::new()`

**Comment by milancermak** [comment]
I don't think that will help with the `span` not found error, since that's coming from `ArrayTrait`.

**Comment by tarrencev** [comment]
ah yes sorry i didn't read your original issue closely

**Comment by tarrencev** [comment]
i chatted with shahar and he mentioned we can do `array::ArrayTrait::span(@a)`
