### ISSUE TITLE
Avoid `warn` logs from external dependencies 

### ISSUE THREAD

**Issue by dubzn** [dojoengine/dojo#2311]
**Is your feature request related to a problem? Please describe.**
It is a bit invasive to see several logs when you are compiling and many warnings messages appear from projects that we have as dependencies. Mainly because we can't do anything from our project to solve them :( 

**Describe the solution you'd like**
These logs could be filtered by default and displayed if the user when using higher verbose levels.

**Additional context**
Screenshot:
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/55e7ef75-1bad-4366-9dc3-cc970e7f294e">

**Comment by ScottyDavies** [comment]
please can i work on this?

**Comment by glihm** [comment]
@dubzn that could be a good thing, not sure of the feasibility though.

@ScottyDavies if you're up to look for it, go ahead!
You could check into `bin/sozo/src/commands/test.rs` for the testing part, and in the `build.rs` for the build.

**Comment by ScottyDavies** [comment]
Hi @glihm i will look into it immediately

**Comment by glihm** [comment]
Sozo has no more default compiler, hence we don't have control on this yet. If scarb one day exposes it, we should definitely use it.

Will close for now.
