### ISSUE TITLE
[BUG] sozo test high RAM usage (20GB+)

### ISSUE THREAD

**Issue by rsodre** [dojoengine/dojo#2314]
**Describe the bug**
Running any simple tet on pistols consumes 18-20GB of RAM

**To Reproduce**

* clone [pistols](https://github.com/underware-gg/pistols)
* `cd dojo`
* `sozo test -f test_initialize_table` (any test will demonstrate there problem, this is a very simple one)
* open **Activity Monitor** on macOS or a similar status monitor
* go to the *Memory* tab and filter by `sozo`
* while sozo builds, used memory goes up to 9GB, when it starts to run tests, it doubles and stays ~17-20GB

and please notice this gas consumption on simple tests ([test_initialize_table_defaults](https://github.com/underware-gg/pistols/blob/c6b6baec42e0b27336186f34b0106dc7bf03caff/dojo/src/tests/test_admin.cairo#L177-L184))...
```
$ sozo test -f test_initialize_table
testing test(pistols_unittest) pistols v0.10.0-3 (/Users/roger/Dev/Realms/pistols/dojo/Scarb.toml)
running 2 tests
test pistols::tests::test_admin::tests::test_initialize_table ... ok (gas usage est.: 52,242,666)
test pistols::tests::test_admin::tests::test_initialize_table_defaults ... ok (gas usage est.: 54,464,862)
test result: ok. 2 passed; 0 failed; 0 ignored; 233 filtered out;
```

**Expected behaviour**

**Screenshots**
<img width="1072" alt="Screenshot 2024-08-18 at 10 38 16" src="https://github.com/user-attachments/assets/567dc393-63f1-42ac-8a96-79308a96e5cf">

**Additional context**

* using Dojo 1.0.0-alpha.6 + Scarb 2.7
* The project uses the `origami_token` package ERC-20 and ERC-721, and some openzeppelin utils.
* Note that I have to include `openzeppelin_test_common` to be able to run tests, even if not using any openzeppelin in the tests

**Comment by lambda-0x** [comment]
just to add some quick context, i checked the memory usage on spawn-and-move example that is in the repo and memory usage was around 1.2GB for build and 3.5GB for running the test (it only has couple of tests).

**Comment by rsodre** [comment]
origami token package: ~4GB during build, ~8.5GB during tests
```
sozo test --package origami_token
```

**Comment by ShantelPeters** [comment]
@rsodre please can I be assigned

**Comment by glihm** [comment]
For the record, `scarb` has also notice significative increment of the compilation time. We may depend on what their bottleneck is.

@ShantelPeters do you have an idea of what could be dojo bottleneck related to compilation? Happy to assign if you have some suggestions.

**Comment by rsodre** [comment]
Is there an scarb issue for that?

The language server is also consumes around 6GB.

Btw, running the same test with Dojo alpha 9, it's around 13GB

**Comment by glihm** [comment]
Sozo now doesn't use any custom compiler, and we are purely relying on scarb and Cairo-lang for that. Will close since no more optimization can be done on our end. 👍 (at least for now)
