### ISSUE TITLE
Messages are not processed in order

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#2321]
**Describe the bug**
In the current implementation of the starknet and Ethereum message service, katana fetches logs/events from the base layer and store them into a `HashMap`. However, the order is not guaranteed later when using `.iter()` on this `HashMap`.

So multiple blocks are fetches with messages, we may process blocks in different orders.

We could also at some point rework the `fetch_event` function to return a `Vec` instead of a `HashMap` as the block number can be found inside the event itself.

**To Reproduce**
Starting anvil with a block time and sending several messages in the same block will evidence this flaw.

**Expected behavior**
https://github.com/dojoengine/dojo/blob/bb7d7dfd9f0a7589d5981de6a22da9ef86f356c2/crates/katana/core/src/service/messaging/starknet.rs#L210-L215

`block_events` must here iterate on sorted keys (or `fetch_event/log` must return an ordered `HashMap`).

**Comment by adrianvrj** [comment]
hey can I work on this one?

**Comment by ybensacq** [comment]
I can take as well if needed.

**Comment by glihm** [comment]
> hey can I work on this one?

Hey, I just updated the issue with more content. Happy to assign if you could give the strategy you wanted to propose? :)

**Comment by adrianvrj** [comment]
@glihm sure, here is what I would do:

- Reproduce the bug and see exactly how it is working.
- Study the code to understand the actual implementation and why it might be failling.
Here I would like to try two things:
1. Refactor the fetch_event  sorting the events by block number before returning them. This would involve collecting the events into a Vec, sorting by block number, and then converting them into an ordered collection, like an IndexMap, which maintains insertion order.
2. Try to modify the fetch_event function to return a Vec instead of a HashMap. This approach naturally preserves the order of the events as they are fetched.

After the code modifications are done, I would run multiple tests to ensure the changes does not affect any other functionality.

**Comment by glihm** [comment]
> @glihm sure, here is what I would do:
> 
> * Reproduce the bug and see exactly how it is working.
> * Study the code to understand the actual implementation and why it might be failling.
>   Here I would like to try two things:
> 
> 1. Refactor the fetch_event  sorting the events by block number before returning them. This would involve collecting the events into a Vec, sorting by block number, and then converting them into an ordered collection, like an IndexMap, which maintains insertion order.
> 2. Try to modify the fetch_event function to return a Vec instead of a HashMap. This approach naturally preserves the order of the events as they are fetched.
> 
> After the code modifications are done, I would run multiple tests to ensure the changes does not affect any other functionality.

Sounds great if this is your actual plan. :)
In this case, we may also consider changing to a `Vec` instead of an ordered map that make the flow easier to maintain.

**Comment by adrianvrj** [comment]
> > @glihm sure, here is what I would do:
> > 
> > * Reproduce the bug and see exactly how it is working.
> > * Study the code to understand the actual implementation and why it might be failling.
> >   Here I would like to try two things:
> > 
> > 
> > 1. Refactor the fetch_event  sorting the events by block number before returning them. This would involve collecting the events into a Vec, sorting by block number, and then converting them into an ordered collection, like an IndexMap, which maintains insertion order.
> > 2. Try to modify the fetch_event function to return a Vec instead of a HashMap. This approach naturally preserves the order of the events as they are fetched.
> > 
> > After the code modifications are done, I would run multiple tests to ensure the changes does not affect any other functionality.
> 
> Sounds great if this is your actual plan. :) In this case, we may also consider changing to a `Vec` instead of an ordered map that make the flow easier to maintain.

Sure! I can stay in contact so I can inform about any improvements or ideas that may come up while fixing this issue!

**Comment by adrianvrj** [comment]
@glihm should I start working on this?

**Comment by glihm** [comment]
> @glihm should I start working on this?

Yep it's assigned, go ahead!

**Comment by adrianvrj** [comment]
@glihm just opened a draft pr for you to see my progress, feel free to suggest any changes!

**Comment by moteeullahazmi** [comment]
can i try this

**Comment by AshokGorana** [comment]
@glihm Can i work on it ?
