### ISSUE TITLE
Add support for pending block data

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#2325]
**Is your feature request related to a problem? Please describe.**
Currently, when Katana is asked for `get_events`, the pending block is not taken in account.
The function that is ignoring the pending block is this one:
https://github.com/dojoengine/dojo/blob/54a891ee45d0f593c7d0cea28c5b72f56008412e/crates/katana/storage/provider/src/traits/block.rs#L18

**Describe the solution you'd like**
The underlying provider must be updated to support the pending block. For now we could assume pending block will ends up having the block number = `latest + 1`. But this may not always be true on the public network. However, on Katana, it should be fair to make this assumption.

**Comment by EjembiEmmanuel** [comment]
@glihm can I work on this?

**Comment by glihm** [comment]
@EjembiEmmanuel closed in favor of #2328 and @kariy will work on it, let me check which one could be tackled on your end @EjembiEmmanuel. Will try to have more good first issues.

**Comment by EjembiEmmanuel** [comment]
Alright @glihm no worries!
