### ISSUE TITLE
`starknet_getEvents` API doesn't work with pending block

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#2328]
specifying pending block as either `from` or `to` block in the `getEvents` method doesn't work because `convert_block_id` will return `None` on pending block. 

below are the main areas related to this issue:

https://github.com/dojoengine/dojo/blob/e2ed07388843c3b688190eac771dbc85e84920fd/crates/katana/rpc/rpc/src/starknet/read.rs#L357-L378

inside the call to `this.events()`, the block ids are being converted to block number using the `BlockIdReader::convert_block_id()` trait method. 

https://github.com/dojoengine/dojo/blob/e2ed07388843c3b688190eac771dbc85e84920fd/crates/katana/rpc/rpc/src/starknet/mod.rs#L336-L338

https://github.com/dojoengine/dojo/blob/54a891ee45d0f593c7d0cea28c5b72f56008412e/crates/katana/storage/provider/src/traits/block.rs#L18-L36

but because the provider traits doesn't have any context on the pending block, a placeholder was placed instead.

https://github.com/dojoengine/dojo/blob/54a891ee45d0f593c7d0cea28c5b72f56008412e/crates/katana/storage/provider/src/traits/block.rs#L38-L42

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue?

**Comment by ScottyDavies** [comment]
please can i work on this?
