### ISSUE TITLE
Scarb now outputs to `target/dev` by default

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#239]
It seems scarb introduced a breaking change and outputs to `target/dev`. We have it hard coded to `target/release`. We should also allow profile to be specified with the cli

https://docs.swmansion.com/scarb/docs/reference/profiles

**Comment by kariy** [comment]
i assume for migration, we would only deploy the `release` version? if that so, then during `migration` it would need to check for `release` version and build it if it's not available.

**Comment by tarrencev** [comment]
I think we want to support both, since you might be migrating to different chains, i.e. dev, test, mainnet (release)
