### ISSUE TITLE
World indexer

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#24]
Implement an indexer to index world events in an efficient and easily queryable manner. The database should expose both historical and the current state of the world.

Objects like:
- components
- entities
- systems
- resources

Historical events like:
- component / system / entity registration
- entity state updates
- system calls

The indexer could use the https://github.com/apibara/apibara engine to stream events from starknet and write them to a sqlite db that can be easily replicated and shared with others.

**Comment by fracek** [comment]
FYI if it's useful with apibara you can stream storage changes too so no need to make an rpc call to get the state of of components (not sure how it plays with storage verification tho).

**Comment by tarrencev** [comment]
Perfect. I think the indexer will be for developer ergonomics and doesn't need to be concerned with the state verification. That part can be implemented as part of the client. The client can basically get the current world state however they want (rpc/indexer/ect) and then verify it using storage proofs

**Comment by ponderingdemocritus** [comment]
the historical state is very important in most games.

question is - what type of DB do we use? 

Do we just add a postgres into Ryogoku and an apollo server?

**Comment by tarrencev** [comment]
I think @wraitii is taking a swing at this

We discussed using sqlite, since it can be embedded into the toolchain and would make it easy for users to spin up during development. It's also easily distributed using something like litestream. That's what pathfinder is using too

**Comment by wraitii** [comment]
My work so far was on generally using apibara with rust, which I've started here: https://github.com/wraitii/apibara-rust-sdk .
I don't really plan on working much further on this at the moment however, and there remains a fair bit of work.

Re sqlite — I think it makes sense given the objectives, and my repo above has the very basics of an integration.

**Comment by ponderingdemocritus** [comment]
yes good point

perhaps:

sqlite + prisma with some base schema developers can easily add to

**Comment by ponderingdemocritus** [comment]
i can tackle this - unless someone is already is?

**Comment by Larkooo** [comment]
> i can tackle this - unless someone already is?

Hey, I'm already on this. Will link the branch/repo soon
