### ISSUE TITLE
Support for starknet_traceBlockTransactions RPC Method in Katana

### ISSUE THREAD

**Issue by barabanovro** [dojoengine/dojo#2458]
**Is your feature request related to a problem? Please describe.**
Currently, users can't debug transactions on Katana with Walnut if Katana has multiple transactions per block because the `starknet_traceBlockTransactions` RPC method is not supported on Katana.

**Describe the solution you'd like**
Add support for the `starknet_traceBlockTransactions` RPC method to Katana.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context.

**Comment by ShantelPeters** [comment]
kindly assign please

**Comment by kariy** [comment]
@barabanovro both `starknet_traceTransaction` and `starknet_traceBlockTransactions` have been added in #2486
