### ISSUE TITLE
remove `SequencerConfig` usage

### ISSUE THREAD

**Issue by tcoratger** [dojoengine/dojo#2467]
`SequencerConfig` is marked as in the process of removal in

https://github.com/dojoengine/dojo/blob/60c1575927db63e98ababda56c5ffa9f6337fb56/crates/katana/core/src/sequencer.rs#L1-L10

There are still a few places in the code where this structure is used, for example here:

https://github.com/dojoengine/dojo/blob/60c1575927db63e98ababda56c5ffa9f6337fb56/crates/dojo-test-utils/src/sequencer.rs#L38

In order to fully deprecate this type, we need to remove uses like this.

**Comment by Jonatan-Chaverri** [comment]
I will like to work on this

**Comment by kariy** [comment]
> I will like to work on this

hey @Jonatan-Chaverri, im still figuring out that part as i refactor stuff around. so not really thinking of opening it to external contributor for now.

if you want to contribute, i'd suggest trying this one instead #2458

**Comment by ScottyDavies** [comment]
@Jonatan-Chaverri can i take up this issue

**Comment by Sagar-Puniyani** [comment]
@tcoratger want to work on this issue assign it to me

**Comment by kariy** [comment]
@ScottyDavies @Sagar-Puniyani sorry guys, we're not accepting external contributors for this issue for now.

**Comment by kariy** [comment]
the entire config management has been revamped here #2508
