### ISSUE TITLE
[sozo] make `sozo dev` great again

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#2481]
This task it to create `sozo dev <OPTIONS>` and make it great again.

**Problem**

Common full stack dev flow is.

1. Write contracts
2. Write client
3. Change contracts

If models/systems change in contracts, `sozo build --typescript` has to be run again, along with migration happening.

This is fine- but we can do better...

**Solution**

`sozo dev <OPTIONS>`

Running this command we could pass the following options:
```
--bindings OPTION (generates new bindings if systems/models change)
--migration OPTION (migrates when anything changes)
--testing OPTION (reruns tests)
```
This will then watch for file changes in the contracts directory and regenerate the bindings automatically.

**Comment by glihm** [comment]
Has been merge in `1.0.0` with binding regenerated on the fly too.
For the testing, that's something that is not done currently. Maybe having a `--watch` on the `sozo test` could make it better?
