### ISSUE TITLE
[BUG] Sozo doesn't generate overlays for mainnet 

### ISSUE THREAD

**Issue by 0xMugen** [dojoengine/dojo#2495]
**Describe the bug**
When deploying to mainnet the Overlays aren't automatically applied, so you have to manually apply write access to the system contracts

**To Reproduce**
This happend while I was following the https://github.com/rsodre/512karat readme guide to deploy on sepolia/mainnet

**Expected behavior**
A overlays/mainnet file is expected to appear. So that the mainnet deployment behaves the same way as in local testing
Re-running `sozo -P mainnet migrate apply` doesn't fix the issue. 

**Additional context**
The current work around is manually authorising read/write access to the contracts via sozo

example:
```bash
sozo auth grant writer ns:octoguns,actions --world 0x7447477a7c852c946f0b8d13ebdfe0db9e78f3de60ab799320691502b4d32a3
```

**Comment by glihm** [comment]
No more overlays in rc.
