### ISSUE TITLE
[dojo-lang] Generated `name` method conflicts with erc standards

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#2499]
**Describe the bug**
For dojo contract dojo-lang generated a `name` method. ( and other tag, namespaces etc)
`name` conflicts with erc standards and some other namings may conflict with other standards.

Prefixing all dojo-lang generated code with dojo_ would solve this

**Comment by glihm** [comment]
I changed it lately yes, to have the same everywhere, by bad on this.
We still have this situation where dojo contract are now not supposed to be an ERC though, with the new integration of the external contracts.

But at some point this may break some integrations that desire to do so. At least origami tokens will not be present in `1.0.0`.

Prefixing everything with `dojo_` might be a bit heavy. But totally doable.
But we still need a common interface for the new core implementation doing the verifications (which is actually on https://github.com/dojoengine/dojo-core now).

**Comment by glihm** [comment]
Fixed in `rc.0`.
