### ISSUE TITLE
Ensure dojo generated code doesn't interfere with ERCs

### ISSUE THREAD

**Issue by glihm** [dojoengine/dojo#2540]
Ensure the generated function for a dojo contract doesn't interfere with existing standards like ERCs.

So a contract `name()` function should be renamed `dojo_name()`.

**Comment by JoE11-y** [comment]
Hi @glihm is this issue open would love to take it on.

**Comment by glihm** [comment]
This was merged in the rework of dojo `rc` release. @akintewe @JoE11-y new issues for new comers to dojo coming soon!
