### ISSUE TITLE
feat: katana gas oracle

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#2558]
## Problem

Right now, Katana hardcoded the gas prices [value](https://github.com/dojoengine/dojo/blob/e6bab2d0066c3cf1acfc5ee41a27294b5b23697d/crates/katana/core/src/constants.rs#L5-L7). These gas prices are then used for computing the fees that transactions has to pay.

Though it works fine when using Katana just for testing/dev environment but for actual production setting we want to properly sample the L1 gas prices. Refer to the doc below for how starknet sample the l1 gas price:

https://docs.starknet.io/architecture-and-concepts/network-architecture/fee-mechanism/#calculation_of_gas_costs

Implementation for the gas oracle component should be able to (1) perform actual sampling on the underlying L1, (2) hardcoded value when katana is not run with an L1 (ie testing env).

On every new block, we'd then need to update the gas price values that have been sampled, in the block env:

https://github.com/dojoengine/dojo/blob/e6bab2d0066c3cf1acfc5ee41a27294b5b23697d/crates/katana/core/src/backend/mod.rs#L101-L117

**Comment by augustin-v** [comment]
Hi, I would love to work on this issue. I have experience with Rust and also contributing to Kakarot with Cairo. I will make sure to communicate if I encounter any issues along the way

**Comment by kariy** [comment]
@augustin-v assigned :). you can take a look at [madara's implementation](https://github.com/madara-alliance/madara/blob/a64723574cf388cbbf297e46dc8bdf5272359158/crates/client/eth/src/l1_gas_price.rs#L1-L270) for reference.

**Comment by augustin-v** [comment]
@kariy Nice, I have made a draft pull request for my progress on the gas oracle implementation in #2558. I would love to get a review to see how I could move forward.
