### ISSUE TITLE
dojo-defi: implement VRGDA/GDA 

### ISSUE THREAD

**Issue by s0lness** [dojoengine/dojo#257]
Gradual dutch auctions (GDA) and variable rate gradual dutch auctions (VRDGA) are mechanisms introduced by Paradigm that help with sales of NFTs over time

Resources:
- https://www.paradigm.xyz/2022/08/vrgda
- https://www.paradigm.xyz/2022/04/gda
- Python analysis: https://github.com/FrankieIsLost/gradual-dutch-auction/blob/master/analysis/analysis.ipynb

Cairo implementations:
- https://github.com/sambarnes/cairo-dutch
- https://github.com/cartridge-gg/cairo-gda

Check: https://github.com/dojoengine/dojo/tree/main/crates/dojo-defi

**Comment by ametel01** [comment]
Hi! happy to take this one if possible!

**Comment by s0lness** [comment]
Go for it!

**Comment by ponderingdemocritus** [comment]
how are you going on this @ametel01 ?

**Comment by ametel01** [comment]
> how are you going on this @ametel01 ?

Hi decided to use Suna for fixed point arithmetic but there no exp() func there. So i'm currently working for exp(), taking inspiration from 64x61 from influence, on Suna and keep working on Dojo-DeFi when done there. Let me know if you have any idea to speed up the work.

**Comment by ametel01** [comment]
I actully found another repo that has exp() already implemented: 
https://github.com/gizatechxyz/onnx-cairo/blob/main/src/numbers/fixed_point/core.cairo 
if ok for you i can use that instead of Suna

**Comment by ametel01** [comment]
@ponderingdemocritus i saw the Scarb dependencies update with cubit library. The compiler though can't really resolve it and cubit is not found:
```error: Identifier not found.
 --> gda.cairo:1:5
use cubit::types::fixed::{Fixed, FixedType, FixedMul, FixedSub, FixedDiv};
    ^***^```

**Comment by ponderingdemocritus** [comment]
create a draft PR of what you have done already
