### ISSUE TITLE
dojo-erc: add ERC1155

### ISSUE THREAD

**Issue by s0lness** [dojoengine/dojo#258]
Similarly to https://github.com/dojoengine/dojo/tree/main/crates/dojo-erc/src/erc20, it'd be great to have a dojo implementation of the ERC1155

**Comment by dbejarano820** [comment]
Hey, if this is stale I would love to dive into it! Would be my first contribution here

**Comment by tarrencev** [comment]
hey @dbejarano820. this one is already in development in #359. would love to have you as a contributor though! let me know if any of the other issues are of interest

**Comment by dbejarano820** [comment]
@tarrencev All good! I'll be on the look out for other good first issues 👀
