### ISSUE TITLE
[sozo] typscript bindings

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#2600]
This is currently being included in the function output.

Type `ClassHash` is not included.

We need to include the `ClassHash`

```
	const upgrade = async (account: Account, newClassHash: ClassHash) => {
		try {
			return await provider.execute(

				account,
				{
					contractName: "actions",
					entryPoint: "upgrade",
					calldata: [newClassHash],
				}
			);
		} catch (error) {
			console.error(error);
		}
	};
	```

**Comment by glihm** [comment]
@MartianGreed was this solved in your latest PR?

**Comment by MartianGreed** [comment]
Yeah we decided to not include this function, as we surely won't upgrade from frontend
