### ISSUE TITLE
dojo-bot: Discord/Telegram notification

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#266]
A one-click bot deployment with minimal config which allows you to configure notifications will be essential for worlds.

The indexer will expose this information, so maybe a rust bot that simply listens to the ws events is the easiest path.

This task is dependent on the indexer being completed.

**Comment by ponderingdemocritus** [comment]
Let's also include a LLM natural language query system

**Comment by tarrencev** [comment]
I think this is outside the scope of the dojo core project here but could make an interesting complementary project

**Comment by ponderingdemocritus** [comment]
it should be built off the back of the general notification system

**Comment by ponderingdemocritus** [comment]
yes agreed - will close here
