### ISSUE TITLE
make C++ bindings?

### ISSUE THREAD

**Issue by gogo2464** [dojoengine/dojo#267]
Hello,

In my humble opinion, it sounds better to have networking package for godot instead of reimplementing the wheel (here the game engine such as graphics and all). We might create for engine and unity in a far future.

So I suggest to make c++ bindings in order to add package to Godot in the future.

At this moment, uniffi-rs only has bindings for python, ruby, kotlin, swift: https://github.com/mozilla/uniffi-rs. no c# and no C++.

We may use rust bindgen: https://rust-lang.github.io/rust-bindgen/introduction.html

Then we could fork in Godot.

Need your opinion.

I am busy to write documentation at this moment.

**Comment by ponderingdemocritus** [comment]
Yes! This is the plan, Dojo will provide the SDKs to connect to visual engines. Its core focus is networking, contracts, and other ancillary services.

The binding path is the way! Did you want to explore this?

**Comment by gogo2464** [comment]
What a great idea!

I would like. I would like to implement C/C++ for uniffi-rs first so that we could have C# bindings as well but it will take too much time.

Python, ruby... are not necessary yet but might could be in a far future.

**Comment by ponderingdemocritus** [comment]
that would be great! The core is almost stable, we expect in a couple of weeks it will be ready, but scoping this out now would be incredibly helpful!

**Comment by gogo2464** [comment]
Even 2 weeks could not be enough for the c++ PR in uniffi-rs. 

I am stuck in my mind. it sounds so better to make a PR.

**Comment by gogo2464** [comment]
what should I do?

Quick bindgen or uniffi-rs PR?

**Comment by ponderingdemocritus** [comment]
Explore it and join the discord to discuss!

**Comment by tarrencev** [comment]
hi @gogo2464 this is a great idea and contribution would be greatly appreciated! let's go ahead with uniffi-rs. with it, we can get c# bindings for unity using https://github.com/NordSecurity/uniffi-bindgen-cs

there might be a similar crate for c++ in the wild, or maybe it isn't too hard for modify the c# one to support c++. what do you think?

**Comment by gogo2464** [comment]
@tarrencev I am personally interested in adding my own bindings for uniffi-bindgen-c++ Because I am interested in reverse engineering.

Sadly, implemenyting these seems really really hard for me.

**Comment by gogo2464** [comment]
> Explore it and join the discord to discuss!

I do not find the discord link in the readme, the official starknet discord as well as starknet telegram yet.

Do you have a link or could you accept me in telegram?

**Comment by tarrencev** [comment]
closing for now. will reopen an issue once we're ready to explore unity / unreal bindings

**Comment by gogo2464** [comment]
@tarrencev I am ready to dev c# bindings. could you reopen this issue please?
