### ISSUE TITLE
Modernzie Cairo code

### ISSUE THREAD

**Issue by milancermak** [dojoengine/dojo#269]
We can use all the latest fancy things in our code that have since been added to Cairo. Some examples:

* `true`/`false` keywords instead of `bool::True(())`/`bool::False(())`
* less type suffixes (e.g. `_u32`), the compiler now infers most of the stuff
* less turbofish
* more `loop`s 
* no more need for `withdraw_gas`
* combine imports: `use foo::{Bar, Baz}`

**Comment by sparqet** [comment]
Hi ! Can I get this issue please ?

**Comment by tarrencev** [comment]
> Hi ! Can I get this issue please ?

Sure, go for it!

**Comment by milancermak** [comment]
Resolved in #327
