### ISSUE TITLE
Compute component contracts address

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#27]
Given all components in a world are deployed by the world, we can compute a components address given it's component id:

```
let module_id = pedersen("<module_name>");
let address = deploy(
    class_hash=proxy_class_hash,
    contract_address_salt=module_id,
    constructor_calldata_size=0,
    constructor_calldata=[],
    deploy_from_zero=FALSE,
);
IProxy.set_implementation(class_hash);
IPositionComponent.initialize(address, ...);
registry.write(module_id, address);
```

Currently we don't know the proxy class hash so we can stub that. 

starknet-rs provides a helper for computing a contract address: https://github.com/xJonathanLEI/starknet-rs/blob/ab4752f2b26bbb43dec3450e4358d88fa7a496e2/starknet-core/src/utils.rs#L130

The method should be used here:
https://github.com/dojoengine/dojo/blob/c9dea00d631ec691a770b21ed00aeb1eb47e84f2/crates/cairo-lang-dojo/src/query.rs#L45

**Comment by shramee** [comment]
Had a go at this, but had some hiccups...
1. Pedersen hash (for salt) seems to take 2 args, but Cairo code seems to only use one, couldn't find an equivalent replacement and ended up setting 2nd param to `0`.
2. We need `deployer_address` too, couldn't find an easy way to find world_address so stubbed that too.
3. starknet-rs `FieldElement` is not so fun to work with in general, but also the resulting contract address is a decimal and not a hex which seems to break our tests.
4. `minor` Skipped committing `cargo-lock.json` to avoid conflicts, that cool?
