### ISSUE TITLE
make dojo to compile on Windows

### ISSUE THREAD

**Issue by gogo2464** [dojoengine/dojo#271]
I was documenting dojo for the rust book when...

```
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\USER\.cargo\registry\src\github.com-1ecc6299db9ec823\libmdbx-0.1.12\src\environment.rs:18:9
   |
18 |     os::unix::ffi::OsStrExt,
   |         ^^^^ could not find `unix` in `os`

   Compiling cairo-lang-test-runner v1.0.0-alpha.7 (https://github.com/starkware-libs/cairo?rev=2390363#23903636)
error[E0308]: mismatched types
   --> C:\Users\USER\.cargo\registry\src\github.com-1ecc6299db9ec823\libmdbx-0.1.12\src\cursor.rs:414:28
    |
414 |         IterDup::new(self, ffi::MDBX_NEXT)
    |         ------------       ^^^^^^^^^^^^^^ expected `u32`, found `i32`
    |         |
    |         arguments to this function are incorrect

...

very long long errors (around 30)

```

according to the .yml from github action cicd I suppose dojo works only on Linux.

**Comment by gogo2464** [comment]
After investigation, https://github.com/erthink/libmdbx is the failing dep and is not maintained anymore.

**Comment by gogo2464** [comment]
apibara-starknet => apibara-node => libmdbx

**Comment by tarrencev** [comment]
cc @fracek

**Comment by gogo2464** [comment]
@fracek could you provide more infos please?

**Comment by fracek** [comment]
Does this happens when compiling dojo or you're trying to run apibara starknet for testing? I will look into this later today and update apibara to avoid libmdbx unless it's compiling the node.

**Comment by fracek** [comment]
I see that the indexer starts its own instance of apibara. This requires libmdbx and there is no work around that. I believe the best option would be to always use an external instance of apibara.

**Comment by tarrencev** [comment]
> I see that the indexer starts its own instance of apibara. This requires libmdbx and there is no work around that. I believe the best option would be to always use an external instance of apibara.

Hm using an external version isn't possible for local development though

**Comment by fracek** [comment]
What do you mean? It's possible to run it locally side by side with devnet.

**Comment by gogo2464** [comment]
> Does this happens when compiling dojo or you're trying to run apibara starknet for testing? I will look into this later today and update apibara to avoid libmdbx unless it's compiling the node.

as I remember I did only:

cargo build --bin dojo-language-server --release

nothing for testing

**Comment by tarrencev** [comment]
@gogo2464 we've removed the dependency on apibara now

**Comment by gogo2464** [comment]
great! let me check
