### ISSUE TITLE
[BUG] torii might need a restart before fully indexed

### ISSUE THREAD

**Issue by steebchen** [dojoengine/dojo#2747]
```
{
  "errors": [
    {
      "message": "World does not have any indexed data yet."
    }
  ]
}
```

Sometimes torii is stuck on this even the world is indexed fully but still returns this error. When you manually restart torii using the same storage, the message disappears and returns the successfully indexed data.

**Comment by lambda-0x** [comment]
duplicate: https://github.com/dojoengine/dojo/issues/2711
