### ISSUE TITLE
use doctest

### ISSUE THREAD

**Issue by gogo2464** [dojoengine/dojo#276]
I suggest to use documentation test as well as unit test we are currently using.

Documentation is missing api and reference.

https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#documentation-tests

The project does not have doctest yet.

**Comment by tarrencev** [comment]
I dont think Cairo supports doctest right now and there isn't much need to document the rust logic since it isn't meant to be used as a library
