### ISSUE TITLE
[BUG] Torii error on getTokenBalances()

### ISSUE THREAD

**Issue by rsodre** [dojoengine/dojo#2771]
**Describe the bug**

When using the JavasScript SDK, the `getTokenBalances()` call raises a torii error

**To Reproduce**

* In a world that indexes ERC tokens, call `sdk.getTokenBalances(['0x749fdc23f997bacc1f56fc0f6e1d26264ad1b945a12c8345b74d0327595a685'], ['0x550212d3f13a373dfe9e3ef6aa41fba4124bde63fd7955393f879de19f3f47f'])`...

```
Uncaught (in promise) failed to get token balances: status: Internal, message: "status: Internal, message: \"error returned from database: (code: 1) hex literal too big: 0x749fdc23f997bacc1f56fc0f6e1d26264ad1b945a12c8345b74d0327595a685\", details: [], metadata: MetadataMap { headers: {} }", details: [], metadata: MetadataMap { headers: {"content-length": "0", "content-type": "application/grpc-web+proto"} }
```
(screenshot 1)

* If we do not provide any contract and account filters, calling `sdk.getTokenBalances([], [])`, there's a different error:

```
167fcc3484d81cdf.wasm:0x273eb5 Uncaught RuntimeError: unreachable
    at 167fcc3484d81cdf.wasm:0x273eb5
    at 167fcc3484d81cdf.wasm:0x2efb38
    at 167fcc3484d81cdf.wasm:0x22ca67
    at 167fcc3484d81cdf.wasm:0x45efd
    at 167fcc3484d81cdf.wasm:0x20de61
    at 167fcc3484d81cdf.wasm:0x2f64cd
    at __wbg_adapter_73 (dojo_c_bg.js:464:10)
    at real (dojo_c_bg.js:429:20)
```
(screenshot 2)

**Expected behavior**
No error

**Screenshots**

![Screenshot 2024-12-02 at 15 28 07](https://github.com/user-attachments/assets/ba8418d6-e296-4eb1-b64b-024933d16ad0)

![Screenshot 2024-12-02 at 15 19 16](https://github.com/user-attachments/assets/95cb74ae-75b3-46c2-a3bd-e7980730c985)

**Comment by Larkooo** [comment]
Hey, nice catch thanks! Found the issue, will make a PR to fix that.
