### ISSUE TITLE
[Torii] gRPC to support Tokens subscription

### ISSUE THREAD

**Issue by rsodre** [dojoengine/dojo#2819]
**Is your feature request related to a problem? Please describe.**

Provide a way to subscribe to new and changed token balances.

**Describe the solution you'd like**

I don't know Torii enough to design a solution.

**Describe alternatives you've considered**

Fetching all tokens periodically to apply changes, which is expensive

**Additional context**

To be used on dojo.js SDK: [dojo.js#361](https://github.com/dojoengine/dojo.js/issues/361)

**Comment by RajeshRk18** [comment]
Shall I take up this issue?
