### ISSUE TITLE
Tracking system usage in the db

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#299]
It would be ideal if we could track system usage in the db. This might be unfeasible pre-volition.

If system usage is tracked onchain then incentives can be distributed to the most used systems, creating a nice flywheel for builders within worlds.

This could be an optional setup per world.

**Comment by tarrencev** [comment]
this could be implemented as middleware in the executor and would be a cool dojo library

**Comment by ponderingdemocritus** [comment]
Revisiting this...

It would be great if a developer could just include an `executor.cairo` in their project, and at compilation, it would suck this file up rather than the cores.

This way we could create a library of custom executors, as business logic is unique to worlds 

thoughts?
