### ISSUE TITLE
feat: add entity_ids

### ISSUE THREAD

**Issue by milancermak** [dojoengine/dojo#331]
The return value of `entities` command changed in #291 from returning just an array of IDs to returning a tuple of IDs and deserialized entities. However, it's [still desired](https://github.com/dojoengine/dojo/pull/291#discussion_r1187404902) to have a command that returns only the entity IDs. 

Add an `entity_ids` command that a does just that.

**Comment by sparqet** [comment]
Hi ! Can I take this one please ?

**Comment by sparqet** [comment]
@tarrencev I implemented a new function ````entity_ids``` in cairo files that gets the ids. What should I have to change or implement in rust files ?

**Comment by ponderingdemocritus** [comment]
@milancermak do you think this is still needed since this returns IDS

https://github.com/dojoengine/dojo/blob/main/crates/dojo-core/src/world.cairo#L470

**Comment by tarrencev** [comment]
@neotheprogramist let's add a `entitiy_ids` api to world.cairo that doesn't fetch entity values

**Comment by neotheprogramist** [comment]
I'm starting to work on it

**Comment by neotheprogramist** [comment]
Fixed with https://github.com/dojoengine/dojo/pull/1039
