### ISSUE TITLE
feat: Historical Entity Events

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#336]
We currently record the state of each game entity's components, however, the ability to track and query historical events pertaining to a specific entity is lacking. This tracking will prove useful in tracing the life-cycle of an entity, enhancing our ability to understand its progression and interaction within the game world.

Proposed Solution:

To address this, we need to implement an indexing system for historical events of an entity. This will provide us with a detailed record of entity-specific events over time. 

`get_entity_history`: This function will retrieve the complete history of an entity's events.
`get_component_history`: This function will obtain the history of a specific component's updates for a given entity.

Every time a component's data is indexed, a corresponding entry should be made in the history table along with a timestamp.

**Drawbacks:**

Please note that this proposed solution will lead to a substantial increase in data storage for large game worlds. Nevertheless, this feature is critical for our goal of having a comprehensive understanding of an entity's life-cycle.

This could be an optional flag when running torii, but my assumptions are that this is key to most games.

Thoughts?

**Comment by tarrencev** [comment]
Is something like this not possible using the events rpc?

**Comment by ponderingdemocritus** [comment]
Not really

Practical examples:
Return the history of everything that has occurred on a Realm
-- Combat
-- Travel
-- Trade

These should be queryable with the graphql API in chronological order 

My thinking is that we can just extend an entities history table on every update at the same time update the component. This would actually be very useful for a world explorer.

**Comment by ponderingdemocritus** [comment]
we are already mapping events with @broody latest commit.

so after we start indexing the schema of the table we will only need to add the correct resolver for querying by entity and component(s)
