### ISSUE TITLE
feat: Generic Events

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#340]
Games will require more than just the native events Dojo provides at the component state change.

There will be a need for unique events and these will need to be indexed in the same layer as the native events.

There could be many flavours of these events, but I think it would be appropriate if we standardised their implementation to minimize custom indexer / cairo code.

**Catch all events**
Since we are emitting all events from the world, we can build a catch-all event processor and create tables of the event that follows the appropriate schema. Which could be something like:

```rust
    #[event]
    fn _EventName(event_name: u250, <value(s)>: Span<felt252>) {}
```

Then we can have a generic processor listing for any events prefixed with a '_' in `torii` to index these.

**Comment by milancermak** [comment]
To me, this doesn't feel like the right way to go. Isn't it possible to declare the events on the indexer side as well? 

Even if you have a generic catch-all event, you'd still have to implement some custom deserialization logic to get out the real values no?

**Comment by tarrencev** [comment]
I have an idea for a logging framework that I think could address this need and be a nice abstraction. I can create an issue for it. It'll make sense to add once the context work is ready

**Comment by ponderingdemocritus** [comment]
ok great please make an issue. I think it's important this feature in someway exists in the toolchain
