### ISSUE TITLE
Introduce execution context

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#345]
This proposal is to provide a `Context` to system execution, which provides the dojo execution context.

The context can provide useful information such as:

```rust
struct Context {
    world: ContractAddress,  // Address of the world
    caller_account: ContractAddress, // Address of the origin
    caller_system: ContractHash, // Address of the system that is calling this system
    caller_role: Role, // Authorization role used for this call
}
```

The `dojo-core` contracts should be updated to introduce the `Context` struct.

[Executor](https://github.com/dojoengine/dojo/blob/main/crates/dojo-core/src/executor.cairo#L14) should be updated to pass the context to systems (in place of the `world_address`)

The `systems.rs` generation logic should be updated to inject the context, so in `executor.cairo` we can naively pass the context.

For example:

```rs
#[system]
mod Foo {
    fn execute() {
        ...
   }
}
```

Should be compiled to 

```rs
#[contract]
mod Foo {
    #[external]
    fn execute(ctx: Context) {
        ...
   }
}
```

**Comment by milancermak** [comment]
Small suggestion - since World has a well define interface we know, how about having `world: IWorldDispatcher` as the type in context?

**Comment by ftupas** [comment]
> Small suggestion - since World has a well define interface we know, how about having `world: IWorldDispatcher` as the type in context?

I think it can be nice, we just have to implement or derive (if possible) Serde for `IWorldDispatcher` since in the [executor](https://github.com/dojoengine/dojo/blob/main/crates/dojo-core/src/executor.cairo#L18), we're passing the world as calldata `Span<felt252>` and doing a `library_call_syscall` on the system
