### ISSUE TITLE
[Katana] persistent state

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#370]
Feature for `katana` to dump its state to a file, which later can be loaded from on the next `katana` run. This would allow persisting the state from previous session onto the next one.

The easiest way is to just implement `Serialize` & `Deserialize` traits on [`StarknetWrapper`](https://github.com/dojoengine/dojo/blob/1e96e556c8898f682307638c9e3fdc4bc57e2637/crates/katana-core/src/starknet/mod.rs#L53) and just serialize it to a file. But the issue with doing this is, some of the underlying types which come from external deps, don't impl `Serialize`/`Deserialize`. So, might have to patch some of the deps and implement the traits on those types first if we're going with that.

**Comment by Eikix** [comment]
I could try to take this!

**Comment by tarrencev** [comment]
@Eikix i think it is worth talking a look at how foundry's anvil does this. are they dumping to json?

**Comment by Eikix** [comment]
> @Eikix i think it is worth talking a look at how foundry's anvil does this. are they dumping to json?
> 
> edit: Hmm yeah looks like they serialized it to bytes which will be a much more efficient representation than json 
> 
> https://github.com/foundry-rs/foundry/blob/master/anvil/src/eth/backend/mem/in_memory_db.rs

It definitely sounds better to do it with bytes,
Does this deserve its own issue after we do the json dump as "first implementation"?
as in staggering difficulty?

I'm guessing in any case, the difficulty might lie in ContractClass as I understand it's not just a standard object, it's a bit more complex?

Mhm will explore how easy it is to do local kv db dump as first implementation

**Comment by kariy** [comment]
i think its worth mentioning that katana is loosely based of the python devnet, so maybe worth looking into how they handle this feature https://github.com/0xSpaceShard/starknet-devnet/blob/master/starknet_devnet/dump.py

**Comment by tarrencev** [comment]
> > @Eikix i think it is worth talking a look at how foundry's anvil does this. are they dumping to json?
> > edit: Hmm yeah looks like they serialized it to bytes which will be a much more efficient representation than json
> > https://github.com/foundry-rs/foundry/blob/master/anvil/src/eth/backend/mem/in_memory_db.rs
> 
> It definitely sounds better to do it with bytes, Does this deserve its own issue after we do the json dump as "first implementation"? as in staggering difficulty?
> 
> I'm guessing in any case, the difficulty might lie in ContractClass as I understand it's not just a standard object, it's a bit more complex?
> 
> Mhm will explore how easy it is to do local kv db dump as first implementation

I think that makes sense, if the json dump is simple lets land that first

**Comment by Eikix** [comment]
Ok I'll investigate with the blockifier team for a bit and then try both approaches

**Comment by Eikix** [comment]
I guess `pickle` in Python is super powerful, as it ser/de objects into bytes, which makes it very portable,
We'd be the only ones doing JSON dumps, which is kinda bad;/

The only upside I see is readability, and chances are dumps aren't too big anyway, so i/o won't be too expensive, I may be very wrong. 

If the dump includes every tx since inception and the genesis state, it'll be way too big to kinda "run" a projection, but if it's a snapshot object, whereby you only have the latest state and not a huge list of tx, should be ok.

**Comment by kariy** [comment]
i dont think readability of the dump file is necessary.

maybe something like [`bincode`](https://crates.io/crates/bincode) might be helpful?

**Comment by Eikix** [comment]
Hi all,
I can't manage to find a satisfying solution in the time that I have for this issue, I'm going to have to drop the issue and let someone else try:), thanks a lot for your patience and help so far

Tried solutions:
- serde_json as library to dump and load state -> a lot of `Error("key must be a string")` when trying to dump state
- bincode library (1.3.3) -> dump state is fine, cannot load state due to `deserialize_any` errors -> i suspect ContractClass's dynamic deserializing to be at fault

```rust
#[derive(Clone, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
pub struct ContractClassV1Inner {
    #[serde(deserialize_with = "deserialize_program")]
    pub program: Program,
    pub entry_points_by_type: HashMap<EntryPointType, Vec<EntryPointV1>>,
    pub hints: HashMap<String, Hint>,
}
```
With:

```rust
/// Converts the program type from SN API into a Cairo VM-compatible type.
pub fn deserialize_program<'de, D: Deserializer<'de>>(
    deserializer: D,
) -> Result<Program, D::Error> {
    let deprecated_program = DeprecatedProgram::deserialize(deserializer)?;
    sn_api_to_cairo_vm_program(deprecated_program)
        .map_err(|err| DeserializationError::custom(err.to_string()))
}
```

And DeprecatedProgram located in `starknet-api`
```rust
/// A program corresponding to a [ContractClass](`crate::deprecated_contract_class::ContractClass`).
#[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
pub struct Program {
    #[serde(default)]
    pub attributes: serde_json::Value,
    pub builtins: serde_json::Value,
    #[serde(default)]
    pub compiler_version: serde_json::Value,
    pub data: serde_json::Value,
    pub debug_info: serde_json::Value,
    pub hints: serde_json::Value,
    pub identifiers: serde_json::Value,
    pub main_scope: serde_json::Value,
    pub prime: serde_json::Value,
    pub reference_manager: serde_json::Value,
}
```

**Comment by glihm** [comment]
Hello! Thanks @Eikix that gives a great start!

@tarrencev I have an idea that might work, I'll try it and get back here to post result if I can achieve it! :+1:

**Comment by glihm** [comment]
Here is some update on the work ongoing for this issue:

1. I have tried to dump the memory associated with the `StarknetWrapper` struc with a different approach that the one mentioned before, but same thing, the deserialization fails.

2. Then, trying to understand more how `cairo-vm` types work with the blockifier, it's definitely challenging (at least for my rust level) to have `serde` working for all the types. So I tried to ignore any `ContractClass` during serialization, replacing them by a serializable form stored when RPC call is coming, right before it's being converted to `ContractClass` in the `katana/rpc/src/utils/contract.rs`.

    While working on this solution, I had other troubles serializing the `TransactionExecutionInfo`, where it's once again some deep dive into `cairo-vm` types. So I switched to the next one.

3. So the last idea speaking with @jobez that I'll start to explore, is to serialize all the configuration passed to katana at startup, and then record all the transactions and their associated block number.

    Then, on startup, we replay the transactions ensuring that they are inserted in the correct block, in the same order.
    
    The part I didn't explore well yet is the minting on demand, how this exactly works? Because this kind of interaction without a transaction may also be record to make this approach valid.

My knowledge is still limited so I am not sure if there are side effects with this last approach. But as the state is altered by transactions, it may work if we can keep the correct mapping between `transaction <> block` where they are generated.


What do you guys think?

---

I wish I could be able to propose a PR quicker, but seems that my knowledge of blockifier, cairo-vm and a bit rust are below the requirements for this issue. So if my third approach is not a viable one, don't hesitate to re-assign if someone with more experience is available. :+1:

**Comment by kariy** [comment]
First of all, appreciate your help on tackling this issue. It's definitely a headache when all the types are scattered between many crates. 

Preferably, loading the state would not incur too much startup time. Replaying the transactions might become not feasible when they are too many txs that need to be re-executed and build the state from origin. But because `katana` is meant to be used a ephemeral devnet and txs may not accumulate too much ( can't really guarantee that it wouldn't ), then this solution might be worth looking into.

But, again, i think if we can just serialize and deserialize the state it would be much better and less complex.

---

Just a fyi, as you are aware there's an alternative to `blockifier` which is `starknet_in_rust`. I am in a process of researching if migrating `katana` to `starknet_in_rust` is worth it and if it can make implementing this feature much easier.

**Comment by glihm** [comment]
Thank you for this feedback @kariy.

Yes definitely agree with you, serialize/deserialize is the best to have. And as you said I've only used Katana for small stuff with not too much transactions, but we can't anticipate how much they accumulate bases on the use case.

I'll take also a look at `starknet_in_rust`, and see how it can enhance this serialization. But if the same `cairo-vm` types are used (which I expect), we may be in the same situation.

**Comment by kariy** [comment]
#756 
#700
