### ISSUE TITLE
[Katana] RPC - `starknet_getClass`

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#384]
The implementation should be written [here](https://github.com/dojoengine/dojo/blob/3e3f5d803b14762de88b97c36b5a9f60e3440733/crates/katana-rpc/src/starknet/mod.rs#L549).

Contracts stored in `katana` are defined using blockifier's [`ContractClass`](https://github.com/starkware-libs/blockifier/blob/477e8a8e4c514d006123ff8c2362c311217fb2b5/crates/blockifier/src/execution/contract_class.rs#L31) but the RPC return type should be [this](https://github.com/xJonathanLEI/starknet-rs/blob/a6cbfa3be71e9f42532c393632bdf18ccb01f88a/starknet-core/src/types/mod.rs#L137).

Need to somehow convert from `blockifier` ContractClass to `starknet-rs` ContractClass.

**Comment by tarrencev** [comment]
> can i try ?

yes please do

**Comment by notV4l** [comment]
waiting for this : https://github.com/lambdaclass/cairo-rs/issues/1183
