### ISSUE TITLE
Use StorageAccess trait for storage packing/unpacking

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#386]
Currently we use the `Serde` trait which is designed for entrypoint serialization. Now that StorageAccess is derivable, we should switch to using it and allow custom implementations.

Serde calls in the generated code for `set_entity`, `entity` and `entities` commands needs to be updated:

https://github.com/dojoengine/dojo/blob/main/crates/dojo-lang/src/commands/set.rs#L27

The component `schema` api needs to be updated to support schema introspection:

https://github.com/dojoengine/dojo/blob/main/crates/dojo-lang/src/component.rs#L105

**Comment by tarrencev** [comment]
Digging into this a bit more, it won't be possible to use the `starknet::StorageAccess` trait and derive, since it uses the read and write syscalls internally. We'll have to implemenet a `dojo::StorageAccess` trait and derive that uses the world read and write apis instead

**Comment by ponderingdemocritus** [comment]
closing as goals and ideas have shifted on this
