### ISSUE TITLE
docs: use UML for visualizing flow

### ISSUE THREAD

**Issue by ftupas** [dojoengine/dojo#393]
Currently, we have this [diagram]( https://excalidraw.com/#json=-VK5I7Pe90AOHh2OmwhhH,T0awPoFRDrYzRsPP_wEMQg) that provides an architecture overview of a Dojo world. It would be nice if it can be included in the docs (either this repo or in dojo book) so it can be version-controlled and properly documented. Perhaps we can use a UML tool like [Mermaid](https://mermaid.live) to visualize the flow

**Comment by ponderingdemocritus** [comment]
yes! Was going to add it to the book - or feel free to add it. The Auth section is blank right now
