### ISSUE TITLE
bug: instructions from dojo book "build from source" in installation section results in an error

### ISSUE THREAD

**Issue by Eikix** [dojoengine/dojo#396]
When running `cargo install --path ./crates/katana --profile local --force`, I get the error that there is no local profile

reproducing steps:

1. go to https://book.dojoengine.org/getting-started/installation.html#building-from-source

Inside the instructions:
```
# clone the repository
git clone https://github.com/dojoengine/dojo.git
cd dojo
# install Sozo
cargo install --path ./crates/sozo --profile local --force
# install Katana
cargo install --path ./crates/katana --profile local --force
# install Torii
cargo install --path ./crates/torii --profile local --force
```

Running `cargo install --path ./crates/katana --profile local --force`

Results in: 

```
error: failed to compile `katana v0.1.0 (/Users/eliastazartes/code/kkrt-labs/dojo/crates/katana)`, intermediate artifacts can be found at `/Users/eliastazartes/code/kkrt-labs/dojo/target`

Caused by:
  profile `local` is not defined
```

<img width="1331" alt="image" src="https://github.com/dojoengine/dojo/assets/66871571/88ce1da8-a653-4963-b0f4-54302f6a05fd">

**Comment by tarrencev** [comment]
Ah yeah we don't have profiles, we should remove that part

**Comment by tarrencev** [comment]
Resolved now
