### ISSUE TITLE
Ids are felt

### ISSUE THREAD

**Issue by spapinistarkware** [dojoengine/dojo#41]
May I suggest using usize instead of felt?
what kind of operations will you be making with them?
If not a lot, I think usize is better:
1. Faster sequencing, since it will run faster on x86.
2. Future proofing if we change fields in cairo

**Comment by ponderingdemocritus** [comment]
TIL 

Is there any reason to use a felt?

**Comment by tarrencev** [comment]
> May I suggest using usize instead of felt? what kind of operations will you be making with them? If not a lot, I think usize is better:
> 
> 1. Faster sequencing, since it will run faster on x86.
> 2. Future proofing if we change fields in cairo

Ah interesting. I didn't consider that. We can definitely use it instead, I don't think we would ever need more than 2^64 entities

**Comment by spapinistarkware** [comment]
I think it's dangerous using only 64bits of hashes as identities. Since u are using pedersen directly, it makes sense using felts there.

**Comment by tarrencev** [comment]
resolved in #75. thanks for the suggestion @spapinistarkware
