### ISSUE TITLE
Update dojo-lang plugin_test to output manifest

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#429]
Generate a world manifest using the plugin test data and output it to the expected output files:

It can be added here:
https://github.com/dojoengine/dojo/blob/main/crates/dojo-lang/src/plugin_test.rs#L94

That will make it much easier to test / catch changes to the manifest schema.

**Comment by tarrencev** [comment]
Sure that would be great, thank you!

**Comment by ponderingdemocritus** [comment]
@pierrot498 are you still planning on completing this?

**Comment by lambda-0x** [comment]
with some guidance, i think i can tackle this.
