### ISSUE TITLE
[Dojo] Refactor authorization system into the world directly

### ISSUE THREAD

**Issue by ftupas** [dojoengine/dojo#435]
## Current Behavior 

We are using components and systems to set authorization roles and check if systems are authorized to modify entities' components. For example, we have the following systems in [systems.cairo](https://github.com/dojoengine/dojo/blob/2058c4618903f5489000660b712c0cf114b967d4/crates/dojo-core/src/auth/systems.cairo)

- IsAccountAdmin: checks if the caller account has `Admin` role
- IsAuthorized: checks if an execution role has been set, if not, default scoped role is used and finally this role is checked if it's authorized/Admin or not

Here's an example illustration of the flow
<img width="1064" alt="image" src="https://github.com/dojoengine/dojo/assets/35031356/fa430f04-4d60-427d-be0f-d515112716bc">

## Reason

The current method of authorization verification is complex, resulting in a cumbersome process and a less-than-optimal developer experience. The world has to call the executor which then does a library call to these declared components and systems. This results in more execution steps and gas costs. It also makes it hard to debug and reason about.

## Proposed Solution

To address these issues, it would be good to simplify the authorization checking by incorporating it directly into the world. This would mean the roles would have to be stored in the contract, as well as exposing public interfaces to set/remove roles. There has been work on the execution context in this [pr](https://github.com/dojoengine/dojo/pull/392) which could serve as a starting point.

**Comment by ponderingdemocritus** [comment]
closing as this is complete
