### ISSUE TITLE
[Sozo] Events cmd to retrieve events

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#475]
I'm using [starknet-probe](https://github.com/kariy/starknet-probe/commits/main) (awesome tool btw), to retrieve world events. I think would be useful to have in sozo as well

Maybe something like:
```
sozo events --world [address] [event_names] --from-block xx --to-block xx
```

**Comment by lambda-0x** [comment]
I can work on this. @broody can you explain how do you use `starknet-probe` to retrieve world events?

**Comment by broody** [comment]
#LFG!

You could use the example project try this:
`katana --seed 0`
`sozo migrate` // executed in ecs examples folder
`probe events --chunk-size 1` // dumps all events

Current world events are defined here: https://github.com/dojoengine/dojo/blob/main/crates/dojo-core/src/world.cairo#L48

Would be cool to have something like this dump out data from specific events
`sozo events ComponentRegistered,PlayerJoined`

**Comment by lambda-0x** [comment]
@broody review please :)

**Comment by broody** [comment]
Requested @kariy as this is his domain :)
