### ISSUE TITLE
Not able to see events emitted from system

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#477]
Emitting an event in spawn, after `sozo execute` I had expected the tx receipt would log the event but it doesn't seem to. Though world events like "ComponentRegistered" or "SystemRegistered" are logged. 

Tried both starkli and starknet-probe cli with same results

```
#[system]
mod Spawn {
    #[event]
    fn SpawnedEvent(caller: u250) {}

    fn execute(ctx: Context) {
        let player = commands::set_entity(
            ctx.caller_account.into(), (Moves { remaining: 10 }, Position { x: 0, y: 0 }, )
        );
        SpawnedEvent(ctx.caller_account.into());
        return ();
    }
}
```

**Comment by jobez** [comment]
kkrt is experiencing a similar bug re: event emission. i have begun working on a small unit test to reproduce the issue for v0 contracts, but i think theres overlap here where it address the v1 case also.

**Comment by broody** [comment]
Resolved by https://github.com/dojoengine/dojo/pull/521, thx @kariy!
