### ISSUE TITLE
[Dojo] Structured logging with Context

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#485]
Currently, logs are generated through the native starknet event system. The issue is systems emitting events are actually outputted by the `executor` contract rather than the world itself.

This task is to introduce a structured logging api to the world.

1) Add a `fn log(ctx: Context, data: Span<felt252>)` api to the world. The world should validate that the call comes from an installed system. When called, it should append the `caller_account` and `caller_system` from the execution context to the keys and `execution_role` to the data.

https://github.com/starkware-libs/cairo/blob/11a028379888869282fe7ef4984e81da258b7b43/corelib/src/starknet/syscalls.cairo#L30

2) Implement a new `log` command in the compiler plugin, the command should take a struct as input and convert it to a call on the world contract:

```
#[derive(Drop, starknet::Event)]
struct Spawn {
    player: ContractAddress,
    value: u256,
}
```

```
log!(ctx.world, Spawn {
    player: ContractAddress,
    value: u256,
})
```

expands to:

```
{
  let event = Spawn {
      player: ContractAddress,
      value: u256,
  };
  
  let mut keys = Default::<array::Array>::default();
  let mut data = Default::<array::Array>::default();
  starknet::Event::append_keys_and_data(@event, ref keys, ref data);
  ctx.world.log(keys.span(), data.span());
}
```

**Comment by ponderingdemocritus** [comment]
closing as complete

**Comment by Cheelax** [comment]
will try to tackle this

**Comment by ponderingdemocritus** [comment]
have assigned @Cheelax

**Comment by tarrencev** [comment]
hey @Cheelax  this issue has already been resolved (we added the emit! macro). Sorry i forgot to close it
