### ISSUE TITLE
Implement storage proofs

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#487]
Implement a `katana_getStorageProofs` api similar to the `katana_getStorageProofs` api

https://github.com/eqlabs/pathfinder/pull/726

**Comment by tarrencev** [comment]
@rkdud007 this ones got your name on it :D

**Comment by rkdud007** [comment]
@tarrencev looks interesting ser :D I'll try look at it !

**Comment by rkdud007** [comment]
hey let me try it again haha

**Comment by kariy** [comment]
> hey let me try it again haha

currently blocked by #1027
