### ISSUE TITLE
[Katana] Implement `katana_setNextBlockTimestamp`

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#492]
Add an endpoint under the `katana_*` [namespace](https://github.com/dojoengine/dojo/blob/9c3c55b965de975d3da5f43cff748e9ec6ad986d/crates/katana-rpc/src/katana/api.rs#L16) which allow setting an exact timestamp for the next block.

It should only be able to set the timestamp when there's no pending transactions.

**Comment by aymericdelab** [comment]
would love to take this issue !
