### ISSUE TITLE
Include webrtc package

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#50]
Webrtc is a specification for real time communication.

It supports various audio/video codecs as well as datachannels.

We could use an webrtc to support state channels. It can be used to establish a p2p connection between clients or can be proxied through a sfu for scalability. In SFU mode, we could use SFrame for e2e encryption of the state channel messages. 

There is a robust implementation here:
https://github.com/webrtc-rs/webrtc

They have some examples of establishing data channels.

I've previously written a golang sfu at https://github.com/pion/ion-sfu

**Comment by ponderingdemocritus** [comment]
This is very interesting.

So to elaborate for discussion:

- p2p gameplay visuals sync for multiplayer games
- zk state channels via wasm proof + verifying
- p2p chat native to a game

@JunichiSugiura have you experimented with something like this in bevy?

**Comment by Cheelax** [comment]
What in your opinion should be a good first milestone on using webrtc in dojo?

**Comment by ponderingdemocritus** [comment]
my thinking is we structure this around the Dojo node, it should be the singular point for any dojo client to connect to

**Comment by Cheelax** [comment]
Can you be a bit more specific? not sure to catch you here

**Comment by glihm** [comment]
First phase completed in #1459. A new issue may be open for specific need on WebRTC specification that is not covered by this PR. :+1:
