### ISSUE TITLE
[Katana] Implement `is_alive` to check that the devnet is running

### ISSUE THREAD

**Issue by JorikSchellekens** [dojoengine/dojo#502]
It would be great if the devnets exposed the same endpoint to check the devnet's liveness.

https://github.com/0xSpaceShard/starknet-devnet/blob/4a8d028c5babea9616041781d21e337b55d7936d/starknet_devnet/blueprints/base.py#L72

**Comment by JorikSchellekens** [comment]
We're working on a remix plugin. We wish to communicate the devnet's liveness to the end user with a status icon. With starknet-devnet we ping the is_alive URL regularly to achieve this. We would like to have something similar for Katana!

**Comment by tarrencev** [comment]
Gotcha! For now, perhaps you could ping the `starknet_chainId` rpc endpoint?

In the future, we could add a `/healthz` rest endpoint to support health checks, but it will take a bit more effort since we don't provide a rest api right now
