### ISSUE TITLE
[Dojo] Migrate commands to Inline Macros

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#509]
Cairo now supports inline macros, as seen here: https://github.com/starkware-libs/cairo/commit/8e4e319ae8b7de5a3f32adf2e32e1c036b45104f

The current command handling is here: https://github.com/dojoengine/dojo/blob/edeb5f0bb36a425f5e540cff6b7207ea52286b7f/crates/dojo-lang/src/commands/mod.rs#L45

They are matched based on the function signature within a system here:
https://github.com/dojoengine/dojo/blob/edeb5f0bb36a425f5e540cff6b7207ea52286b7f/crates/dojo-lang/src/system.rs#L354

This task is to update the commands to use macros, which will also enable them to be used outside of components / systems.

```rs
# Current
fn commands::uuid() -> felt252;

# New
uuid!()
```

```rs
# Current
fn commands::set(storage_key: StorageKey, components: T);

# New
set!(ctx: Context, storage_key: StorageKey, components: T);
```

```rs
# Current
fn commands::<T>::get(storage_key: StorageKey) -> T;

# New
entity!(ctx: Context, storage_key: StorageKey, T) -> T;

eg:
let position = entity!(ctx, 0x0, Position);
let (position, moves) = entity!(ctx, 0x0, (Position, Moves));
```

```rs
# Current
fn commands::<T>::entities() -> Array<felt252>;

# New
entities!(ctx: Context, storage_key: StorageKey, T) -> T;

eg:
let positions = entities!(ctx, 0x0, Position);
let entities = entities!(ctx, 0x0, (Position, Moves));
for (position, moves) in entities { ... }
```

**Comment by ponderingdemocritus** [comment]
Maybe @wraitii would want to take this since he is the chad that did the Cairo PR

**Comment by wraitii** [comment]
There's two possible approaches:

- the Macros are part of the AST so you could just update the code to handle macros in `system.rs`, which would be a first step.
- The approach I took in https://github.com/starkware-libs/cairo/commit/8e4e319ae8b7de5a3f32adf2e32e1c036b45104f is to write a Cairo plugin that rewrites the macro to something else. That seems like it'd do what's wanted?
  - However, the plugins system gets the low-level AST elements, and we'd need to iterate over all expressions to find macros inside functions at the moment, which is likely rather inefficient.

**Comment by neotheprogramist** [comment]
Hi,
I am already working on that, could you guys tell me if we have any example of Cairo "inline macro"?
As I understand this task we want to take the commands from here
https://github.com/dojoengine/dojo/blob/edeb5f0bb36a425f5e540cff6b7207ea52286b7f/crates/dojo-lang/src/commands/mod.rs#L45
And rewrite them into macros, that we can put into match.
If I misunderstand anything correct me please.

**Comment by neotheprogramist** [comment]
I am already working on that, will develop 1st approach
