### ISSUE TITLE
[Sozo] Force deploying new World 

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#516]
We want to allow user to spawn a new instance of the World even if another instance of it already exists. 

Currently, if you try to migrate you might get stuck if `Contract already deployed` error if you already deployed a World with similar class hash using `sozo migrate`.

Can randomly generate a salt for deployment if user specify for this behaviour. For example, `sozo migrate --new`

**Comment by ponderingdemocritus** [comment]
came here to say the same thing :)

**Comment by tarrencev** [comment]
@kariy rather then generating a random salt, lets have the user provide a world `name` which we can hash to the salt. in some cases, the user will want to run migrate against an existing world, to install new components / systems for example

**Comment by kariy** [comment]
> @kariy rather then generating a random salt, lets have the user provide a world `name` which we can hash to the salt. 

perhaps it's better if we just have a `--salt` option for `sozo migrate`? `name` doesn't seem very intuitive

**Comment by tarrencev** [comment]
> > @kariy rather then generating a random salt, lets have the user provide a world `name` which we can hash to the salt.
> 
> perhaps it's better if we just have a `--salt` option for `sozo migrate`? `name` doesn't seem very intuitive

i like `name` since it abstracts the underlying implementation detail and is easily communicated. i think it is more intuitive, since without a pretty deep understanding of deployments, it's not clear what `salt` refers to. in the future, we can also use the `name` as world metadata

**Comment by kariy** [comment]
> i like `name` since it abstracts the underlying implementation detail and is easily communicated. i think it is more intuitive, since without a pretty deep understanding of deployments, it's not clear what salt refers to.

make sense

> in the future, we can also use the `name` as world metadata

aight

**Comment by kariy** [comment]
Resolves in #654
