### ISSUE TITLE
Create `dojo-client` crate

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#518]
We would like to expose a rust dojo client that can be used for interacting with worlds in client applications.

`dojo-client` should be light weight, with minimal dependencies, and support compilation to wasm for web. It should implement apis similar to the `commands` api for reading / writing from / to the world. It should support being backed by arbitrary storage providers. It should support synchronizing the world state from different providers too, for example, directly from rpc or by streaming updates from a backend, such as torii, and mirroring its state.

## Storage Providers

The client should be backed by a generic `State` implementation that allows for different backends.

https://github.com/dojoengine/dojo/blob/b2bb39f357bc47b811283465f4173aa33594b5bd/crates/torii/src/state/mod.rs#L28

For example, `torii` uses a sql backed state:

https://github.com/dojoengine/dojo/blob/b2bb39f357bc47b811283465f4173aa33594b5bd/crates/torii/src/state/sql.rs#L82

And `sozo` can be updated to use an in memory state.

Browsers might use a `localStorage` backed state (although I think sqlite might actually be more performant).

## Storage Synchronization

Hydrating state should be possible through different backends too.

- `torii` provides full world synchronization using an indexer and events
- `sozo` provides partial world synchronization using rpc calls
- eventually, client might subscribe to a backend, such as torii, for reactive state updates and mirror the backends state

**Comment by ponderingdemocritus** [comment]
should we consider Parquet files if these worlds will be synced in the browser? It might not make sense at the beginning when the world is small, but as they grow the syncing could become hefty. Using Parquet will give the client significant headroom as the world state grows

**Comment by ponderingdemocritus** [comment]
closing as complete as this task has evolved
