### ISSUE TITLE
Support array in command::set_entity

### ISSUE THREAD

**Issue by Cheelax** [dojoengine/dojo#520]
Problem
Currently, we have to employ workarounds to store arrays in command::set_entity. The process requires us to convert individual elements into their appropriate data types, which can be tedious and potentially error-prone. For instance, the following code snippet is less intuitive and convenient than it could be:
`commands::set_entity(tileId.into(), (game_id, tile));`

Feature Request
I propose enhancing the command::set_entity method to directly support array inputs. This change would enable us to extract an array from an id in the entities directly, simplifying the code and making it more readable.

**Comment by ponderingdemocritus** [comment]
It is not possible to set arrays in a component yet. I am assuming this is what you are looking for?

**Comment by ponderingdemocritus** [comment]
Closing for now
