### ISSUE TITLE
Support dev mode with hot reloading

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#557]
During development, it can be useful to have hot reloading of a worlds components and systems

We can add an additional flag: `sozo dev`

When running in `dev` mode, the build script should run until interrupted. The logic should implement a loop that watches the project source, when a component / system is created / updated, it should trigger a reload of the language db, similar to the language server:

https://github.com/starkware-libs/cairo/blob/d80d29b52f8972f63ceb490567b26172245e95ff/crates/cairo-lang-language-server/src/lib.rs#L495

After compilation, the component / system should be added / updated in the world using the provided rpc and account.

Eventually, we should trigger updates on the client too, but for now, lets focus on the build -> migrate loop

**Comment by ptisserand** [comment]
Can I work on this issue?

**Comment by ptisserand** [comment]
I have managed to trigger a `build` when `Scarb.toml` or a file with extension `cairo` is modified, renamed, removed.

Now I'm trying to understand which conditions are required to trigger a `migrate`: should I check for classhash differences to ensure a migration is needed?

**Comment by tarrencev** [comment]
@ptisserand how are you triggering build? do you mind sharing your implementation so far?

**Comment by ptisserand** [comment]
@tarrencev : Sure, here is my wip branch: https://github.com/ptisserand/dojo/tree/feat/dev-mode-hotloading

I'm using [notify](https://crates.io/crates/notify) to check for file modifications in `$(dirname manifest_path)` tree.

**Comment by tarrencev** [comment]
> @tarrencev : Sure, here is my wip branch: https://github.com/ptisserand/dojo/tree/feat/dev-mode-hotloading
> 
> I'm using [notify](https://crates.io/crates/notify) to check for file modifications in `$(dirname manifest_path)` tree.

Ok cool!

So we will want to compile the repo similar to how the language server does, then have an instance of the db where we can incrementally compile based on file changes. It is basically the same thing that is done here: 

https://github.com/starkware-libs/cairo/blob/d80d29b52f8972f63ceb490567b26172245e95ff/crates/cairo-lang-language-server/src/lib.rs#L495

Once we have that, when a component or system class hash changes, we should call `register_system` or `register_component`

https://github.com/dojoengine/dojo/blob/dcd1dddbe92d33540eaf33963f2fa35a669a266d/crates/dojo-client/src/contract/world.rs#L103

**Comment by kariy** [comment]
maybe it's worth adding web socket support on `katana` for this.

**Comment by tarrencev** [comment]
> maybe it's worth adding web socket support on `katana` for this.

Hmm how do you imagine that working? I think calling execute directly is probably fine for this

**Comment by kariy** [comment]
> Hmm how do you imagine that working? I think calling execute directly is probably fine for this

If there are frequent updates, then with web socket we can somewhat reduce the overhead of opening up new connections. But i guess there wouldn't be that much frequent changes like in web dev for example, so the overhead is probably not significant at all.

Anyway, i still think it'd be useful to have ws support on `katana`.

**Comment by ptisserand** [comment]
Hi, I'm still working on this issue and I'm wondering if `sozo migrate` logic should be duplicated.

`sozo migrate` logic already handle computing world diff and declaring/deploying contracts if needed.

So I feel I'm going a bit too hackish...

**Comment by ptisserand** [comment]
@tarrencev @kariy any comment on this ?

> Hi, I'm still working on this issue and I'm wondering if `sozo migrate` logic should be duplicated.
> 
> `sozo migrate` logic already handle computing world diff and declaring/deploying contracts if needed.
> 
> So I feel I'm going a bit too hackish...

**Comment by tarrencev** [comment]
> @tarrencev @kariy any comment on this ?
> 
> > Hi, I'm still working on this issue and I'm wondering if `sozo migrate` logic should be duplicated.
> > `sozo migrate` logic already handle computing world diff and declaring/deploying contracts if needed.
> > So I feel I'm going a bit too hackish...

Hey @ptisserand sorry I missed this message. I think some level of duplication is fine for a draft pr, then we can work on refactoring it down to share logic. Do you mind sharing what you have so far?
