### ISSUE TITLE
Issues with entities storage

### ISSUE THREAD

**Issue by shramee** [dojoengine/dojo#558]
It seems like when updating, sometimes the entities duplicate. And entities won't delete some times which could be these duplicated entities.

It could be an improper usage, more details on Telegram:
https://t.me/dojoengine/3011

**Comment by ponderingdemocritus** [comment]
Could you please elaborate more on this and explain how to reproduce clearly. Torii has changed quite a bit since this issue was made, so if we cannot repeat this, then we can close this issue.

**Comment by shramee** [comment]
Sorry, this is not about indexing per say, but actually about entities. The entities didn't delete when I tried deleting them and the Component seemed to return duplicate/bugged values. Even when trying to delete all entities with a loop in a system, they were still sticking around.

**Comment by shramee** [comment]
This is related to #525

**Comment by ponderingdemocritus** [comment]
going to close the same as #525
