### ISSUE TITLE
discussion: Dev container

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#56]
There is quite a bit of setup right now to get the environment of the project ready.

This includes:
- Rust 
- Nodejs 18
- vsce plugins
- build commands

I also expect this environment to evolve rapidly as we add new tools and build commands.

Dev containers come with the downside of the additional overhead of running a container. However, if developers choose to do a clean build on their machine they could.

Looking for feedback @tarrencev @fracek @milancermak

**Comment by tarrencev** [comment]
100% great idea. we could also subsidize code spaces to make contribution easy

**Comment by ponderingdemocritus** [comment]
Ok I will tackle this and write docs.
