### ISSUE TITLE
Sozo execute always returns success

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#574]
Sozo execute will never fail, always return a tx hash even on transactions that should fail

- `katana --seed 0`
- `sozo execute AnythingYouWant`

**Comment by kariy** [comment]
It's not a bug, `blockifier` now consider all transactions as valid ( as long as it pass validation i.e. account's _`_validate_`_ function ). 

Here's that part of the code where it doesn't return error if execution fail: https://github.com/starkware-libs/blockifier/blob/a3a133af7eaa07197caa90766db11edacf8f46f6/crates/blockifier/src/transaction/account_transaction.rs#L401

**Comment by kariy** [comment]
#577 should fix this issue. `estimateFee` endpoint will now return error on reverted transaction.
