### ISSUE TITLE
ERC721 implementation in ./crates/erc/

### ISSUE THREAD

**Issue by ametel01** [dojoengine/dojo#610]
#### Description
Implement ERC721 similar to ERC20 in `./crates/erc`.

**Comment by ponderingdemocritus** [comment]
are you planning on completing this @ametel01 ? If not lets open it as a good first issue

**Comment by ametel01** [comment]
Yes i will, got taken by other stuff give me a couple of days

**Comment by ametel01** [comment]
> are you planning on completing this @ametel01 ? If not lets open it as a good first issue

PR ready for rewiew
