### ISSUE TITLE
feat: Struct Packing for World State

### ISSUE THREAD

**Issue by neotheprogramist** [dojoengine/dojo#616]
We previously embarked on creating a ***Packable*** trait for struct packing for world state. The original issue included the introduction of a Packable trait as illustrated below:
```cairo
trait Packable<T> {
    fn pack(self: @T, ref packing: felt252, packing_offset: u8, ref packed: Array<felt252>);
    fn unpack(ref packed: Span<felt252>, ref unpacking: felt252, unpacking_offset: u8, ref unpacked: Array<felt252>);
    fn size() -> usize;
}
```
The aim was for Dojo core to implement native types which can then be used to derive packed representations for higher user-defined structs. The interface was designed to minimize allocations, providing a packing struct representing a partially packed/unpacked felt.

However, this approach has led to complications and we have decided to change our strategy.

**Proposed Change:**
We propose to move the packing/unpacking to a lower level - precisely, right before writing to storage. We believe the best location to incorporate this functionality would be in `database.cairo`.

The challenge with the current architecture of dojo is that any user can register a component/system with the world, making it vulnerable to potential malicious actions like writing to storage directly with a syscall.

To mitigate this risk, we propose a solution that operates on a lower level, allowing users of the world APIs to not have to manually pack/unpack. Our suggestion is to incorporate a `fn layout() -> (...)` function in each component, which would return information about the storage layout.

When calling set_entity, the function can retrieve the layout and pass it to a lower level, which will parse the information and conduct the packing/unpacking. In essence, we aim to implement a `StorageLayout` trait.

To further illustrate this, the layout approach would be similar to how we call `.len()`, we would now call `.layout()` in [database.cairo](https://github.com/dojoengine/dojo/blob/main/crates/dojo-core/src/database.cairo#L39)

**Comment by ponderingdemocritus** [comment]
I think we can close this now as the plan is to use the built-in packing impl ? @tarrencev @wraitii @milancermak

**Comment by wraitii** [comment]
I think technically the world packing could pack on top of the user-provided packing, gaining some more benefit. But it's probably good enough ?
