### ISSUE TITLE
[KATANA] Log the emitted events after transaction execution

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#640]
This feature is mainly for DX improvement. 

Display the emitted events in the CLI after successfully executing a transaction at the trace level using `trace!`. Similar with how `katana` display the execution resources as implemented [here](https://github.com/dojoengine/dojo/blob/854ae41e5d883c1912f391e7acfe95c35c0d9519/crates/katana/core/src/backend/mod.rs#L139) :

```console
[2023-07-10T18:55:43Z TRACE katana_core::starknet] Transaction resource usage: Steps: 14322 | ECDSA: 1 | L1 Gas: 9792 | Pedersen: 26 | Range Checks: 359
```

**Comment by 0xChin** [comment]
hiiii @kariy, can I take this?

**Comment by kariy** [comment]
> hiiii @kariy, can I take this?

it's yours 🫡
