### ISSUE TITLE
[KATANA] use of unstable library feature 'is_some_and'

### ISSUE THREAD

**Issue by ftupas** [dojoengine/dojo#641]
# Bug Report

Current behavior:

I'm getting this error when compiling the binaries

```bash
error[E0658]: use of unstable library feature 'is_some_and'
   --> crates/katana/core/src/sequencer.rs:127:14
    |
127 |             .is_ok_and(|c| c != ClassHash::default())
    |              ^^^^^^^^^
    |
    = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `katana-core` due to previous error
warning: build failed, waiting for other jobs to finish...
```

Expected behavior:

Should compile

Related code:
https://github.com/dojoengine/dojo/blob/854ae41e5d883c1912f391e7acfe95c35c0d9519/crates/katana/core/src/sequencer.rs#L121-L129

Other information:

N/A

**Comment by kariy** [comment]
what version of rustc are you using? because `is_ok_and` becomes stable in 1.70.0

**Comment by kariy** [comment]
i think its time to standardize the version of rustc for the project

**Comment by ftupas** [comment]
oh my bad I'm still on 1.69.0 that's why 😿 

```
❯ rustc --version
rustc 1.69.0 (84c898d65 2023-04-16)
```

should we close this and create an issue to pin the rustc version?

**Comment by kariy** [comment]
> should we close this and create an issue to pin the rustc version?

we can just add a [`rust-toolchain`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) file and specify it to be 1.70.0

**Comment by ftupas** [comment]
Alright let me do that, thanks @kariy !
