### ISSUE TITLE
Sozo or Sozu

### ISSUE THREAD

**Issue by Starknet-China** [dojoengine/dojo#648]
Hello there,

There is a confusion on the naming of migration planner.

In the [main page](https://github.com/dojoengine/dojo/), it's Sozu.

In the [code](https://github.com/dojoengine/dojo/blob/main/crates/sozo/Cargo.toml), it's Sozo.

We are wondering which is right.

Thank you.

**Comment by kariy** [comment]
I have been thinking the same thing too lmao. @tarrencev

**Comment by tarrencev** [comment]
Oops it should be `sozo` haha, which means "creation" in japanese
