### ISSUE TITLE
Context origin in systems doesnt reflect caller_address

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#665]

**Comment by tarrencev** [comment]
Do you mind sharing more on this? Do you have a reproducible case? As far as I've seen, it correctly reflects the caller

**Comment by notV4l** [comment]
> Do you mind sharing more on this? Do you have a reproducible case? As far as I've seen, it correctly reflects the caller

I started to write the issue and noticed it was not, i opened it by mistake.
