### ISSUE TITLE
[Sozo] Updating component / sytem results in permissions error

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#678]
After migrating a world with `sozo migrate`, making a change to an existing component / system then running `sozo migrate` again results in the following permissions error:

```
[2023-07-26T02:26:35Z WARN  katana_core::backend] Transaction execution error: "Error in the called contract (0x03ee9e18edc71a6df30ac3aca2e0b02a198fbce19b7480a63a0d71cbd76652e0):
    Error at pc=0:81:
    Got an exception while executing a hint: Custom Hint Error: Execution failed. Failure reason: \"only owner can update\".
    Cairo traceback (most recent call last):
    Unknown location (pc=0:731)
    Unknown location (pc=0:677)
    Unknown location (pc=0:291)
    Unknown location (pc=0:314)
 ```
 
 In this flow, the deployer should be the owner of components / systems they creates and this error should not be thrown

**Comment by dpinones** [comment]
@tarrencev can I take this one?

**Comment by kariy** [comment]
> How should the flow be when making changes to an existing component/system?

to update World, just do `sozo migrate --world <WORLD_ADDRESS>`. 

this will compute the diffs of the local World against the remote one (as specified using `--world` option) and perform any updates if theres any
