### ISSUE TITLE
Landing Page Improvements

### ISSUE THREAD

**Issue by clicksave** [dojoengine/dojo#679]
Landing page is a little out of date. 

Have a few improvements in mind. 

- [ ] Add a link to the [Docs page](https://book.dojoengine.org/)
- [ ] Add feedback to the Terminal Command Line button

---

https://github.com/dojoengine/dojo/assets/3332646/c8909cf2-e381-4c83-8938-a73f9209488d

---

**Desktop**

<img width="1882" alt="image" src="https://github.com/dojoengine/dojo/assets/3332646/32ffdcc6-0427-486e-b645-933640768920">

**Mobile**

<img width="427" alt="image" src="https://github.com/dojoengine/dojo/assets/3332646/548978c2-5bd2-4375-b202-b53a11748547">

---

**Resources**

[Figma](https://www.figma.com/file/OK6ksIOFB32P2CquZkz6vT/dojoengine.org?type=design&node-id=1%3A8946&mode=design&t=dGTltvmHPk1wUUff-1)

^ You may need to request access ^

**Comment by notV4l** [comment]
i can make changes
