### ISSUE TITLE
How to connect testnet?

### ISSUE THREAD

**Issue by tgyf007** [dojoengine/dojo#681]
rpc_url = "http://localhost:5050/" how can I change to connect testnet?

I change the url to "https://starknet-goerli.infura.io/v3/", got the error:
Failed to migrate executor: Migrator(Provider(StarknetError(InvalidContractClass)))

I also try to use "katana --chain-id SN_GOERLI" , it not works.

**Comment by ponderingdemocritus** [comment]
katana is a local dev environment, it can be deployed remotely but not with that command.

jump into the discord to discuss https://discord.gg/KG9w9BmDrV 

closing this issue

**Comment by tgyf007** [comment]
What can I do if I want to migrate my contracts to testnet? No on answer me in discord.
