### ISSUE TITLE
feat(sozo): `events` improvement

### ISSUE THREAD

**Issue by lambda-0x** [dojoengine/dojo#684]
```[tasklist]
### Improvements in  `events` subcommand
- [x] take `continuation_token` as input and pass it to RPC request according to spec
- [ ] https://github.com/dojoengine/dojo/issues/742
- [x] ~~update `opt/events.rs` to use logging framwork similar to what `migrate` uses~~ see: https://github.com/dojoengine/dojo/issues/883
```

some of this improvements where suggested in #590.

should i keep this tasks in separate PRs so its easier to review or a single PR is fine?

CC: @kariy @tarrencev

**Comment by tarrencev** [comment]
this sounds great!

for human readable, we can use the abi / manifest to parse the events into human readable formats

i think smaller PR's would be ideal
