### ISSUE TITLE
[Sozo] Output block # after successful migration

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#687]
When migrating world, it would be useful to show the block number the world contract was deployed on. Useful to have when starting torii with `--start-block`. Currently using another cli to get this value prior to migration. 

Perhaps something like this?
`🎉 Successfully migrated World on block #1337 at address 0x788f5fd335d29ed5f8686982079cc3aa9c82aa41968f759b2c3d0be8d5fa0c4`

**Comment by ponderingdemocritus** [comment]
Great idea! @aymericdelab and I had the exact same thought yesterday

**Comment by broody** [comment]
Ugh commented on the wrong issue. Meant to say it here -

Ah just occurred to me, perhaps an enhancement to sozo migrate is updating the manifest to include block_height and rpc_url after migration, this way torii just needs the manifest param to start indexing.

manifest.json

  "rpc_url" : "https://rinnegan.madara.zone",
  "world": {
    "name": "world",
     "address": "0x123",
    "block_height": "1337"
    "class_hash": "0x7f07c1861ee2df73f81685cdda7e51978ef0f50154a6a8c11e4af6b55d08ebf"
  },

**Comment by lambda-0x** [comment]
i can give this a try

**Comment by lambda-0x** [comment]
@broody do you mean `manifest.json` generated by `sozo` inside `./target/dev` folder? I can see `world` object in that file but not `rpc_url`

**Comment by broody** [comment]
Thanks! I believe @tarrencev had some thoughts about manifest.json, could possibly address in another issue. Being able to output block height on just `sozo migrate` would be great for now.

> @broody do you mean `manifest.json` generated by `sozo` inside `./target/dev` folder? I can see `world` object in that file but not `rpc_url`.

Right, I had added that as an example to illustrate.

> Also is the `block_height` only needed for `world` contract or all contracts present in that file?

From torii perspective, we just need it for world contract, but perhaps good idea to include for all.

**Comment by lambda-0x** [comment]
> Thanks! I believe @tarrencev had some thoughts about manifest.json, could possibly address in another issue. Being able to output block height on just sozo migrate would be great for now.

Okay then i will clean up the linked PR and change from draft to ready for review tonight

**Comment by lambda-0x** [comment]
@tarrencev i am not really sure what kind of information would be useful, i can think of `block_number`  (as requested by @broody which already has a usecase),  `block_hash`, `transaction_hash` (in which particular contract was deployed). But not sure what other two would be used for.

Is there anything else that might be helpful?

**Comment by lambda-0x** [comment]
<details><summary>currently schema is somewhat like this (have remove nested parts):</summary>

```json
{
  "world": {
    "name": "$name",
    "address": "$ADDRESS",
    "class_hash": "$ADDRESS"
  },
  "executor": {
    "name": "$name",
    "address": "$ADDRESS",
    "class_hash": "$ADDRESS"
  },
  "systems": [
    {
      "name": "$name",
      "inputs": [],
      "outputs": [],
      "class_hash": "$ADDRESS",
      "dependencies": []
    }
  ],
  "contracts": [
    {
      "name": "$name",
      "class_hash": "$ADDRESS",
      "address": "$ADDRESS"
    }
  ],
  "components": [
    {
      "name": "$name",
      "members": [],
      "class_hash": "$ADDRESS"
    }
  ]
}
```


</details> 


but i think there was a PR on sozo allowing it to deploy multiple `world` contracts with `name` as seed but do we care about old world contract after new one is deployed? same question for `executor` can there be multiple executor deployed and do we need to store old one in manifest after new is deployed.

here is the struct that holds `Manifest` file currently: https://github.com/dojoengine/dojo/blob/778ca0453639ccbf293bb6a7b0f568fb4838fea1/crates/dojo-world/src/manifest.rs#L88-L94

**Comment by tarrencev** [comment]
> currently schema is somewhat like this (have remove nested parts):
> i think there was a PR on sozo allowing it to deploy multiple `world` contracts with `name` as seed but do we care about old world contract after new one is deployed? same question for `executor` can there be multiple executor deployed and do we need to store old one in manifest after new is deployed.
> 
> here is the struct that holds `Manifest` file currently:
> 
> https://github.com/dojoengine/dojo/blob/778ca0453639ccbf293bb6a7b0f568fb4838fea1/crates/dojo-world/src/manifest.rs#L88-L94

I think that is a good question. Should a manifest be per chain deployment? In that case, a manifest corresponds to a particular chain. That probably makes most sense? Then we can track a single deployment per manifest

**Comment by lambda-0x** [comment]
as discussed with @tarrencev `manifest` file related changes can be handled in a separate issue, will open one with more details. 

I have clean up the linked PR for this issue and marked it for review.
