### ISSUE TITLE
[Torii] Apply state diffs to update world state

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#690]
Currently, we are using event based indexing to reconstruct the worlds state in the torii indexer:

https://github.com/dojoengine/dojo/blob/dcd1dddbe92d33540eaf33963f2fa35a669a266d/crates/torii/src/processors/store_set_record.rs

We want to migrate to using a state diff approach, where given a set of entities and components an indexer cares about, it is able to directly apply the state diff generated through transaction execution to the world state. This approach will allow us to more easily support optimistic state updates in the future, since it is easier to reconcile state between local and remote when using a declarative approach.

Entity state in dojo is deterministically addressed. The storage base address for an entity's component is computed as the poseidon hash of `['dojo_storage', <component>, <id>]`, as seen here:

https://github.com/dojoengine/dojo/blob/6b3c9964298b7a91049199aff2e1438e99013e12/crates/dojo-core/src/database.cairo#L35

Computing and reading a components state for a given entity from a client here:

https://github.com/dojoengine/dojo/blob/dcd1dddbe92d33540eaf33963f2fa35a669a266d/crates/dojo-client/src/contract/component.rs#L142

For the torii indexer, we will still listen to `store_set_record`, since we want to sync the full world state. For other clients, the developer can explicitly provide a set of entities / components they are interested in syncing.

Here are a few slides that better visualize the approach: https://docs.google.com/presentation/d/101wBK--u50G6e_acd4HGFm8r-ZH6wbI6HqjHPaxG-4U/edit?usp=sharing

**Comment by rkdud007** [comment]
Can i try this one?  👀

**Comment by kariy** [comment]
> For the torii indexer, we will still listen to store_set_record, since we want to sync the full world state

is this to be implemented inside of `torii` or a new indexer implementation that relies on 
state diffs?

> For other clients, the developer can explicitly provide a set of entities / components they are interested in syncing.

would this part of the `dojo-client` sdk?

@tarrencev

**Comment by tarrencev** [comment]
@kariy the logic for applying state diffs to the current state should exist outside of torii and be able to be used in the client sdk too. listening to `store_set_record` is specific to torii, since torii wants to know the entire worlds state

> would this part of the dojo-client sdk?

yeah the client sdk would receive an explicit set of entity / components it is interested in syncing

**Comment by rkdud007** [comment]
`exist outside of torii` : could you explain a little bit of where should i put logic into? 

Because originally i thought implement state diff update logic into `store_set_record.rs` inside torii implemented by `statediffprocesser`
