### ISSUE TITLE
[KATANA] Implement `katana_setStorageAt` 

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#698]
Introduce a new endpoint under the `katana` namespace for modifying a contract storage slot directly.

The target state to be modified should be the [pending state](https://github.com/dojoengine/dojo/blob/309b76e0b929fc6d6edbb369fe26de70b56f23a0/crates/katana/core/src/backend/executor.rs#L32) as this is the state that the upcoming transactions will be executed on.

**Comment by shramee** [comment]
I'm grabbing this one.

**Comment by shramee** [comment]
Ready for a look.
Test for core added, but couldn't find a place for rpc tests.
