### ISSUE TITLE
Implement Component writer access control

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#7]
Components maintain a set of authorized writers who are allowed to update an entities component state.

**Comment by tarrencev** [comment]
@jobez do you still have time to contribute this? removing your assignment for now. let me know if you're able to tackle in the short term or otherwise would love to have you involved once you have bandwidth

**Comment by jobez** [comment]
> @jobez do you still have time to contribute this? removing your assignment for now. let me know if you're able to tackle in the short term or otherwise would love to have you involved once you have bandwidth

I should have time either the middle of this week and the next and will check in where I can best contribute!

**Comment by greged93** [comment]
hey @tarrencev, would love to contribute if the issue is free

**Comment by tarrencev** [comment]
> hey @tarrencev, would love to contribute if the issue is free

hey sure! would really appreciate a contribution here!
