### ISSUE TITLE
Derive `PrintTrait` for components

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#706]
Update the component derive to generate `PrintTrait` implementations for components.

The code should be extended here: https://github.com/dojoengine/dojo/blob/62e23911ef284daabdee727b0ae7ce89001c5fde/crates/dojo-lang/src/component.rs#L87

The implementation should log the component attribute names and values. It should be annotated with `#[cfg(test)]` so it is only included during testing.

**Comment by ftupas** [comment]
Hello may I take this?

**Comment by tarrencev** [comment]
> Hello may I take this?

Sure! Would you mind implementing it against the `inlinemacros` branch though. Since that contains the Cairo 2.1.0 migration
