### ISSUE TITLE
[BUG] sozo 2.1.0-rc4 catch comment as error

### ISSUE THREAD

**Issue by rkdud007** [dojoengine/dojo#719]
**Describe the bug**

newest sozo (latest commit with `2.1.0-rc4` is catching  comment (// update the position of the piece) for an inline macro, which is causing the error.

```
error: Plugin diagnostic: Unknown inline macro: // update the position of the piece
        set
 --> execute_move.cairo:37:9
        set !(ctx.world, (current_position));
```

**To Reproduce**

upgrade to newest sozo ( install using cargo ) and run `sozo build` at dojo project that using latest dojo as a dependency. 
create comment using `//` syntax on top of `set!` macro 

**Expected behavior**

Should not catch the comment

**Comment by ponderingdemocritus** [comment]
same as #798

**Comment by ponderingdemocritus** [comment]
closing as more reproduced code is in #798
