### ISSUE TITLE
[BUG] Unable to import library crates due to versioning issues

### ISSUE THREAD

**Issue by akirillo** [dojoengine/dojo#720]
**Describe the bug**
Importing library crates from `dojo` (in my case, `dojo-test-utils` and `katana-core`) results in failed builds due to versioning mismatches between patched and unpatched dependencies in `dojo`. For example, `dojo` patches `cairo-vm` and `blockifier`, but the patched version of `blockifier` indirectly depends on an unpatched version of `cairo-vm` (through, for example, `cairo-lang-runner`).

**To Reproduce**
Initialize a fresh library project using `cargo`.
Add the following dependencies to `Cargo.toml`:
```toml
katana-core = { git = "https://github.com/dojoengine/dojo.git" }
dojo-test-utils = { git = "https://github.com/dojoengine/dojo.git" }
```
Run `cargo build`.
In my case (building `dojo` rev `5861dae`), you see errors such as:
```shell
error[E0308]: mismatched types
   --> /Users/akirillo/.cargo/git/checkouts/dojo-10cac2e09298cf35/5861dae/crates/katana/core/src/utils/transaction.rs:241:85
    |
241 |         ExecutionTransaction::L1HandlerTransaction(tx) => ApiTransaction::L1Handler(tx.tx.clone()),
    |                                                           ------------------------- ^^^^^^^^^^^^^ expected `L1HandlerTransaction`, found a different `L1HandlerTransaction`
    |                                                           |
    |                                                           arguments to this enum variant are incorrect
    |
    = note: `L1HandlerTransaction` and `L1HandlerTransaction` have similar names, but are actually distinct types
note: `L1HandlerTransaction` is defined in crate `starknet_api`
   --> /Users/akirillo/.cargo/registry/src/github.com-1ecc6299db9ec823/starknet_api-0.3.0/src/transaction.rs:192:1
    |
192 | pub struct L1HandlerTransaction {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: `L1HandlerTransaction` is defined in crate `starknet_api`
   --> /Users/akirillo/.cargo/git/checkouts/starknet-api-d1972d803f00f841/ecc9b69/src/transaction.rs:212:1
    |
212 | pub struct L1HandlerTransaction {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `starknet_api` are being used?
note: tuple variant defined here
   --> /Users/akirillo/.cargo/git/checkouts/starknet-api-d1972d803f00f841/ecc9b69/src/transaction.rs:26:5
    |
26  |     L1Handler(L1HandlerTransaction),
    |     ^^^^^^^^^
```

I have tried also copying over the patches listed in the `dojo` `Cargo.toml`, which previously worked, but not after running a `cargo update`.

**Expected behavior**
Ideally, simply listing the library crates as dependencies in my project's `Cargo.toml` would suffice to use the amazing code you folks have written. Or, at least the latest release of the `dojo` crates should be importable.

**Comment by akirillo** [comment]
I understand that using the `main` branch isn't expected to be stable, but even if I pin the dependencies to rev `e305d4d` (the most recent commit after the `v0.1.0` release where the `scarb` dependency was fixed), I get similar errors:
```shell
error[E0599]: no method named `args` found for enum `WrappedExprList` in the current scope
  --> /Users/akirillo/.cargo/git/checkouts/dojo-10cac2e09298cf35/e305d4d/crates/dojo-lang/src/commands/execute.rs:21:48
   |
21 |         let elements = macro_ast.arguments(db).args(db).elements(db);
   |                                                ^^^^ method not found in `WrappedExprList`
```

**Comment by akirillo** [comment]
In fact, these same errors are present if you try to build the `dojo` project itself after deleting its `Cargo.lock` file (for example, with rev `e305d4d`, or the most recent, currently `44024c2`)

**Comment by kariy** [comment]
seems to be the same issue as https://github.com/dojoengine/dojo/issues/563 

does it still result in the same build issue even after deleting `Cargo.lock` ?

**Comment by akirillo** [comment]
Ah yup, it probably is. I think on the most recent `main`, it can build after deleting `Cargo.lock` - I was hoping to do this with all the Cairo crates pinned to their `2.0.1` versions so I ended up just doing a bunch of patches in my codebase & got it to work
