### ISSUE TITLE
[ERC20] Write test suite

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#743]
Write a comprehensive test suite for the erc20 implementation here: https://github.com/dojoengine/dojo/tree/main/crates/dojo-erc/src/erc20

Inspiration can be taken from the [Open Zeppelin teams](https://github.com/OpenZeppelin/cairo-contracts/tree/cairo-2) test suites

**Comment by ametel01** [comment]
i can take this

**Comment by ametel01** [comment]
@tarrencev @ponderingdemocritus testing functions that leverage `get_caller_address()` eg. `approve` causes the caller address to be the `executor` contract. Should we add an extra `caller: ContractAddress` argument to deal with this?
```  
 #[external(v0)]
    fn approve(ref self: ContractState, spender: ContractAddress, amount: u256) -> bool {
        assert(spender.is_non_zero(), 'ERC20: approve to 0');
        let token = get_contract_address();
        let owner = get_caller_address();
        let mut calldata = array![];
        calldata.append(token.into());
        calldata.append(owner.into());
        calldata.append(spender.into());
        calldata.append(u256_as_allowance(amount));
        self.world.read().execute('erc20_approve', calldata);

        self.emit(Approval { owner, spender, value: amount });

        true
    }
```
becomes this:
```
 #[external(v0)]
    fn approve(ref self: ContractState, owner: ContractAddress, spender: ContractAddress, amount: u256) -> bool {
        assert(spender.is_non_zero(), 'ERC20: approve to 0');
        let token = get_contract_address();
        let mut calldata = array![];
        calldata.append(token.into());
        calldata.append(owner.into());
        calldata.append(spender.into());
        calldata.append(u256_as_allowance(amount));
        self.world.read().execute('erc20_approve', calldata);

        self.emit(Approval { owner, spender, value: amount });

        true
    }
```

**Comment by ametel01** [comment]
@tarrencev @ponderingdemocritus seem that `starknet::testing::set_caller_address`  only change the caller address on the contract is called in, it doesn't work when invoking dispatchers, where the caller address is 0x0. Any workarounds specific to dojo?

**Comment by ametel01** [comment]
Proposed hacky solution:
Create mock test contract with added caller parameter and removed get_caller_address()

**Comment by notV4l** [comment]
> to mock caller address in tests, you have to use set_contract_address (the caller will be the test contract)

**Comment by ametel01** [comment]
> > to mock caller address in tests, you have to use set_contract_address (the caller will be the test contract)

this worked thank!
