### ISSUE TITLE
[ERC721] Write test suite

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#744]
Write a comprehensive test suite for the erc721 implementation here: https://github.com/dojoengine/dojo/tree/main/crates/dojo-erc/src/erc721

Inspiration can be taken from the [Open Zeppelin teams](https://github.com/OpenZeppelin/cairo-contracts/tree/cairo-2) test suites

**Comment by 0xChin** [comment]
hii, can I take this?

**Comment by notV4l** [comment]
i started to write some
