### ISSUE TITLE
[torii] Accept Scarb.toml env in cli commands

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#746]
**Is your feature request related to a problem? Please describe.**
LIke sozo, torii should accept the world address/manifest in the Scarb.toml if it exists

**Describe the solution you'd like**

**currently have to:**
`torii --manifest target/dev/manifest.json --world-address 0x789c94ef39aeebc7f8c4c4633030faefb8bee454e358ae53d06ced36136d7d6`

**wishing for:**

`torii`

The command should pick up manifest and world-address in the Scarb.toml

**Comment by rkdud007** [comment]
Hi, i can give it a try :)

**Comment by ponderingdemocritus** [comment]
please do!
