### ISSUE TITLE
[documentation] Update torii readme.md

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#753]
Torii documentation here needs updating to development documentation - https://github.com/dojoengine/dojo/blob/loaf/readme/crates/torii/README.md

User documentation will be moved to the Dojo book

**Comment by broody** [comment]
Yeah, long overdue, my bad!

**Comment by ponderingdemocritus** [comment]
My original thought was that we have developer documentation in this repo - but sleeping on it, I think we move the development documentation to the Book too, and we deprecate this doc.

**Comment by ponderingdemocritus** [comment]
closing superseded by book issue
