### ISSUE TITLE
[BUG] [Sozo] TestRunner run tests twice for dojo crates

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#759]
**Describe the bug**
Sozo TestRunner run tests twice for dojo crates

**To Reproduce**
run tests on https://github.com/notV4l/dojo/tree/test-erc721 from dojo-erc directory
`sozo test -f test_erc721`

**Expected behavior**
tests only run once

**Additional context**
with  dojoup -v nightly

**Comment by notV4l** [comment]
Looks like this issue is back

**Comment by tarrencev** [comment]
We need to adopt this https://github.com/starkware-libs/cairo/commit/2cd75d7146c0d58df07b0bf75c54b85fe1f80c3b
