### ISSUE TITLE
katana: ability to specify Cairo compiler version

### ISSUE THREAD

**Issue by akirillo** [dojoengine/dojo#768]
**Is your feature request related to a problem? Please describe.**
it would be great to be able to specify the desired Cairo compiler version when running Katana, to test contracts compiled across different versions with all the latest katana features.

**Describe the solution you'd like**
a CLI flag `--compiler-version <VERSION>` which takes in the version of the compiler that contracts are expected to be compiled with.

**Describe alternatives you've considered**
one could search back through katana git history to try to find the rev at which the desired compiler version was used, but this means you may lose out on katana stabilizations and features which have come since. alternatively, one could try to fork katana, patch all the `cairo-*` dependencies to the desired version, and pray it builds

**Comment by kariy** [comment]
Hmm this would be rather difficult to implement because `katana` is pretty much tied to the version of `blockifier` its using. 

The alternative you mentioned is probably the best bet for this, other than that, i don't think implementing this would be feasible at the moment, especially with all the other dependencies that we're maintaining.

Anyway, I'm curious why and in what situation would you ever need this feature?

**Comment by akirillo** [comment]
> Hmm this would be rather difficult to implement because `katana` is pretty much tied to the version of `blockifier` its using. 
> 
> 
> 
> The alternative you mentioned is probably the best bet for this, other than that, i don't think implementing this would be feasible at the moment, especially with all the other dependencies that we're maintaining.
> 
> 
> 
> Anyway, I'm curious why and in what situation would you ever need this feature?

I really like what y'all have been shipping! Especially e.g. state dumping/loading. But currently, our contracts target compiler version 2.0.1, so being able to just specify that and still get new katana features would be great. Not a huge priority, so no offense taken if y'all don't take on this issue.
