### ISSUE TITLE
[core] Ability to have custom Executor.cairo

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#770]
**Is your feature request related to a problem? Please describe.**
Each world will have custom business logic which the developers will want to implement. We should make it easy to add middleware for each world. 

The `executor.cairo` contract accepts all requests to the world, so we should allow it to be customised.

**Describe the solution you'd like**
We should allow developers to simply include an `Executor.cairo` in their repo, which will take precedence over the version of the core. This is a common pattern in development.

This will allow developers to build custom hooks in this contract, like recording usage of systems, or some fixed fee.

Also, we should include a sozo command to init the `Executor.cairo`

Something like:

`sozo add executor`

**Comment by Cheelax** [comment]
I guess I need to keep the existing world when adding a custom executor, or I can override it?

**Comment by ponderingdemocritus** [comment]
The default one - then you edit it to your preference.

**Comment by Cheelax** [comment]
Pasting here tarrence's comment: let's explore some other approaches a bit more. i think it would be ideal if we had a middleware interface that didn't require modifying the executor. it could use systems / components itself. perhaps all we need is a method on the world to register / unregister pre/post execution lifecycle methods

@ponderingdemocritus do you aggree that I don't need the sozo part anymore? or maybe a different one? Not very confident with that part
