### ISSUE TITLE
[sozo] Fetch `--name` from toml in migration

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#785]
**Is your feature request related to a problem? Please describe.**
To migrate users have to:

```
sozo migrate --name example
```

**Describe the solution you'd like**
Following the pattern of config in the Scarb.toml file, if a `name` exists in the Scarb.toml `sozo` should use it.

So it would pull the `name` from the .toml and allow:

```
sozo migrate
```

**Comment by lambda-0x** [comment]
blocked on discussion for other issues, so am working on this.
