### ISSUE TITLE
[BUG] Fix Dojoup printout in console

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#786]
```
dojoup: installing dojo (version v0.2.0, tag v0.2.0)
https://github.com/dojoengine/dojo/releases/download/v0.2.0/dojo_v0.2.0_linux_amd64.tar.gz
dojoup: downloading latest dojo
######################################################################## 100.0%
dojoup: installed - katana 0.1.0
dojoup: installed - sozo 0.1.0
dojoup: installed - torii 0.1.0
```

`dojoup: installed - katana 0.1.0` - should be based on tag

**Comment by lambda-0x** [comment]
i can take this up

**Comment by lambda-0x** [comment]
@ponderingdemocritus currently it prints the version of package as specified in `Cargo.toml`, i think with new releases we should update that as well not just rely on git tags.

**Comment by lambda-0x** [comment]
there is version miss match here because version in `Cargo.toml` was not updated during the release

**Comment by lambda-0x** [comment]
fix is to make a new release 
![image](https://github.com/dojoengine/dojo/assets/87354252/f0256def-12cb-4446-93bf-5959270e1746)
