### ISSUE TITLE
[BUG] Invalid params in the call: unknown variant `0x100000000000000000000000000000001` 

### ISSUE THREAD

**Issue by moodysalem** [dojoengine/dojo#792]
**Describe the bug**
I'm using starknet.js 5.19.0 to talk to katana and trying to deploy some contracts, constructing the provider with `{rpc: {nodeUrl: 'http://localhost:5050'}}`

When I try to deploy contracts, I get an error from katana, but not sure what field is causing issues

```
[2023-08-17T10:09:49Z ERROR katana_rpc::api::starknet] Failed to parse JSON-RPC params as object: Invalid params in the call: unknown variant `0x100000000000000000000000000000001`, expected `0x0` or `0x1` at line 1 column 731
```

**To Reproduce**

spin up katana
create a starknet.js provider and point it at the devnet
try to deploy a contract to it

```
  const provider = new DevnetProvider();
  const accounts = getAccounts(provider);

  console.log("Deploying tokens");
  const simpleTokenContractDeclare = await accounts[0].declare(
    {
      contract: SimpleERC20 as any,
      casm: SimpleERC20CASM as any,
    },
    MAX_FEE
  );
```

perhaps it's related to the account contract in starknet.js not having the expected implementation. i noticed the private keys are longer than with starknet-devnet

**Expected behavior**
no error

**Additional context**
i use the sequencer endpoint for starknet-devnet, but it says 405 method not allowed if i try on katana, so i switched to rpc and really i have no idea the historical context

**Comment by kariy** [comment]
i believe this issue is related to https://github.com/keep-starknet-strange/madara/issues/646, which is said to be resolved in `starknet-rs` in https://github.com/xJonathanLEI/starknet-rs/pull/439 (now included in v0.5.0)

we're still on `starknet-rs` v0.4.0, so need to update the version to resolve this

**Comment by moodysalem** [comment]
is that a difficult update? i'm using starknet-devnet and currently my 50 integration tests take >10 minutes to run, so this would be huge for me.

**Comment by kariy** [comment]
@moodysalem updated `starknet-rs` to v0.5.0. can you check if it is still an issue?

**Comment by moodysalem** [comment]
That fixes it for me
