### ISSUE TITLE
[BUG] Torii requires Scarb.toml to run 

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#794]
**Describe the bug**
Running torii requires scarb.toml to be in current directory

**To Reproduce**
Run torii with valid cli inputs in a directory without a scarb.toml file results in an error about not able to find scarb.toml 
`torii --manifest /path/to/manifest.json --world 0x123`

**Expected behavior**
Be able to run with valid manifest and world address cli input

**Additional context**
Related to this https://github.com/dojoengine/dojo/issues/746

**Comment by lambda-0x** [comment]
i can work on this
