### ISSUE TITLE
[Examples] Update Dojo-defi to new syntax

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#795]
Dojo defi is not up to date with the latest dojo release.

Specifically, it is missing the new #[key] indexing mechanism.

**Comment by ametel01** [comment]
Looks like this is held back by Cubit not implementing SerdeLen on Fixed type. I made a PR on their repo few days back but no reply yet. If someone has a direct communication channel with the author maybe we can speed this up.

**Comment by ponderingdemocritus** [comment]
ill reach out!
