### ISSUE TITLE
Implement entity query api

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#8]
Systems operate on entities in the world. In order to define the set of entities to operate on, dojo should expose a query api similar to the [bevy engine](https://docs.rs/bevy/latest/bevy/ecs/query/index.html).

The api should be expressive, allowing developers to easily construct complex queries, which are interpreted, optimized and inlined at compile time to reduce onchain compute.

The interface should follow the bevy interface:

```rust
fn move(query: Query<(Position, Health)>) {
    // @NOTE: Loops are not available in Cairo 1.0 yet.
    for (position, health) in query {
        let is_zero = position.is_zero();
    }
    return ();
}
```

Expansion:

```rust
#[contract]
mod MoveSystem {
    struct Storage {
        world_address: felt,
    }

    #[external]
    fn initialize(world_addr: felt) {
        let world = world_address::read();
        assert(world == 0, 'MoveSystem: Already initialized.');
        world_address::write(world_addr);
    }

    #[external]
    fn execute() {
        let world = world_address::read();
        assert(world != 0, 'MoveSystem: Not initialized.');

        let position_id = pedersen("PositionComponent");
        // We can compute the component addresses statically
        // during compilation.
        let position_address = compute_address(position_id);
        let position_entities = IWorld.lookup(world, position_id);

        let health_id = pedersen("HealthComponent");
        let health_address = compute_address(health_id);
        let health_entities = IWorld.lookup(world, health_id);

        let entities = intersect(position_entities, health_entities);

        for entity_id in entities {
            let is_zero = IPosition.is_zero(position_address, entity_id);
        }
    }
}
```

**Comment by ponderingdemocritus** [comment]
Similar to bevy at the beginning of each system.Cairo developers could add an array of the component IDs and systems that the current system will interact with.

Then with a macro, we expand this into a address and schema fetch. So then the developer then has a typed interface for each S,C, with only writing the IDs. 

The interface could be fetched from local system so no contract calls, but the address will need to be fetched.

**Comment by tarrencev** [comment]
Hm I'm not sure I follow exactly, do you mind sharing what the interface might look like? What is a component ID in this case? I don't think we need to have a string identifier like in the Cairo 0.10.0 implementation. We can use the struct name itself as the ID and compute the addresses of them deterministically since everything is deployed through the world. So basically we only need to know the worlds address and then can derive the address of everything else. We can also figure out what needs to be updated / deployed onchain and handle that as well
