### ISSUE TITLE
feat: Dojo SDK for Indexer and Contracts

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#82]
It makes sense for us to build a react SDK for Dojo first, before the completion of Dojoscan, as Dojoscan itself would use it killing two birds with one stone.

Dojo SDK is just a react hook library:

- Indexer address and options 
- `useDojo` hook to fetch the state/ query indexer
- State reconstruction functions

It could also wrap up `useStarknet` so developers only need to install Dojo and not both libraries. 

This should be a fairly straightforward lift and then gives an easy integration point into React-only games and websites. Eternum will probably use R3F for the foreseeable future. 

Should this exist in a standalone repo?

**Comment by tarrencev** [comment]
I think we should definitely provide a set of react hooks for accessing state.

As a first step, we should setup a base typescript library. Once we have the graphql server up and running we can use https://github.com/dotansimha/graphql-code-generator to generate a client.

Longer term, i would love to have the frontend library mirror the onchain world, using state diffs from an rpc to reactively update the client state, a step towards having client side verifiable state with beerus

**Comment by tarrencev** [comment]
As far as repo, I generally prefer a monorepo approach, since it will allow us to easily test modules against each other in the ci. We could setup a yarn workspace in the repo alongside the rust workspace
