### ISSUE TITLE
Sozo auth writer verify component and system names

### ISSUE THREAD

**Issue by broody** [dojoengine/dojo#823]
**Is your feature request related to a problem? Please describe.**
Currently, `sozo auth writer {ComponenName} {SystemName}` returns success for any component or system names. Results in `not writer` error due to a missing/capitalized letter

**Describe the solution you'd like**
We can just do a soft check locally against the manifest and warn user if mismatch OR perhaps enforce it onchain as well.

**Comment by shramee** [comment]
Guys, we can close this now perhaps?
