### ISSUE TITLE
[BUG] katana Starknet Options error

### ISSUE THREAD

**Issue by HouseGray** [dojoengine/dojo#845]
the command get error : katana --accounts 50

error:
thread 'main' panicked at 'able to create FieldElement from bytes: FromByteArrayError', crates/katana/core/src/accounts.rs:162:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lambda-0x** [comment]
its happening because with default seed, 15th randomly generated value for seed isn't valid.
