### ISSUE TITLE
Improve Test Coverage for `dojo-core`

### ISSUE THREAD

**Issue by visoftsolutions** [dojoengine/dojo#850]
### Issue Overview
The `dojo-core` crate could benefit from enhanced test coverage. Writing more tests will not only ensure stability and reliability but also provide contributors with a better understanding of the codebase.

### Affected Component
[dojo-core](https://github.com/dojoengine/dojo/tree/main/crates/dojo-core)

### Desired Outcome
- Boost the test coverage for the `dojo-core` crate.
- Improve understanding of the crate's functionalities and mechanics for contributors.

### Reference
For reference on integration testing, especially with Rust code, consider the following example from the `torii` client:
[system_test.rs#L13](https://github.com/dojoengine/dojo/blob/87736597c122d359c7b21e953bca134a9807a1e7/crates/torii/client/src/contract/system_test.rs#L13)

**Comment by neotheprogramist** [comment]
Fixed by https://github.com/dojoengine/dojo/pull/871
