### ISSUE TITLE
feat: improve error logging

### ISSUE THREAD

**Issue by greged93** [dojoengine/dojo#872]
**Is your feature request related to a problem? Please describe.**
The error logging in transaction execution fails to log errors if the `error_log` flag is false. The reason is unclear and makes the dev experience difficult. [Here](https://github.com/dojoengine/dojo/blob/main/crates/katana/core/src/execution.rs#L200) is the branching done.

**Describe the solution you'd like**
Remove the flag and allow for better transaction execution error logging.

**Comment by tarrencev** [comment]
Hm I think it probably makes sense to update this to use error logger verbosity. This could be a trace log

**Comment by greged93** [comment]
I'm curious about two points: why was this flag used and would using error log instead of trace log make sense?

**Comment by tarrencev** [comment]
It makes sense to handle this error, since it is an expected error from the starknet os perspective. If you are running a shared katana sequencer, you wouldn't want to know about every failed txn validation.

During development, it makes sense that a dev would want to know that info. In which case, trace logging can provide it

**Comment by kariy** [comment]
i assume this issue only exists if ur on instant mining mode, the `TransactionExecutor` isnt configured to display any logs which it should have.
https://github.com/dojoengine/dojo/blob/6e108dbe97bcc4fec8c133a2201911295421ebc7/crates/katana/core/src/service.rs#L401-L402

which is not the case for interval mining: https://github.com/dojoengine/dojo/blob/6e108dbe97bcc4fec8c133a2201911295421ebc7/crates/katana/core/src/service.rs#L276-L283
