### ISSUE TITLE
[BUG] max fee validation error

### ISSUE THREAD

**Issue by greged93** [dojoengine/dojo#873]
**Describe the bug**
The validation step will fail on with max fee error if the balance of the account is lower than the max fee, EVEN when the sequencer fee transfer is disabled.

**To Reproduce**
- Run Katana with sequencer fee disabled.
- Send a transaction with max fee > eoa balance.
Example of the exected error:
```
Transaction validation error: MaxFeeExceedsBalance { max_fee: Fee(100000000000000000), balance_low: StarkFelt("0x00000000000000000000000000000000000000000000000000000000000186a0"), balance_high: StarkFelt("0x0000000000000000000000000000000000000000000000000000000000000000") }
```

**Expected behavior**
Transaction should pass as fee will not be perceived by the sequencer.

**Comment by tarrencev** [comment]
Makes sense. Would you be interested in contributing a fix?

**Comment by kariy** [comment]
thanks for the find, apparently the `charge_fee` arg is hardcoded to `true` for instant mining mode. thats why balance check is still enforced.

https://github.com/dojoengine/dojo/blob/6e108dbe97bcc4fec8c133a2201911295421ebc7/crates/katana/core/src/service.rs#L401

**Comment by greged93** [comment]
I can grab this one, just might need a couple of days first to verify the latest commit on Katana is working for us on Kakarot.
