### ISSUE TITLE
refactor(sozo): make event parsing logic modular and reusable

### ISSUE THREAD

**Issue by lambda-0x** [dojoengine/dojo#882]
Currently event parsing logic using in `sozo events` is very declarative and not reusable, it should be refactored in such a way that it could be re-used by other components of dojo.

It can be done in few ways currently like implementing a method on `Manifest` or creating a new `struct` which contains manifest (and hence the abi) and events.

related: https://github.com/xJonathanLEI/starknet-rs/issues/286

---------------------

# EDIT

Now [cainome](https://github.com/cartridge-gg/cainome/blob/main/crates/rs-macro/README.md) has the [parser](https://github.com/cartridge-gg/cainome/tree/main/crates/parser) library which can be used to parse cairo types from string.

In `sozo`, the [event parsing](https://github.com/dojoengine/dojo/blob/68e81f65df92837cffcdd4f0b498a3b71edb55a9/bin/sozo/src/ops/events.rs#L67) may then be enhanced using cainome.

**Comment by lambda-0x** [comment]
https://github.com/glihm/starknet-abigen-rs this has ability to parse `EmittedEvents`, i will take a look if it works for us.

**Comment by ponderingdemocritus** [comment]
are you still actioning this @lambda-0x ?

**Comment by lambda-0x** [comment]
@glihm mentioned that the repo is not meant to be consumed directly, waiting for https://github.com/xJonathanLEI/starknet-rs/pull/475 to be merged.

**Comment by glihm** [comment]
> @glihm mentioned that the repo is not meant to be consumed directly, waiting for [xJonathanLEI/starknet-rs#475](https://github.com/xJonathanLEI/starknet-rs/pull/475) to be merged.

I've updated the README in the PR + changed the linked in the repo. If you need to test out something, you can try with this new syntax: https://github.com/glihm/starknet-rs/tree/abigen/starknet-macros.

But yes... until it's merged, it's still on the fork and not the official repo. And may be broken based on the feedback of Jonathan during the review.

**Comment by ponderingdemocritus** [comment]
Putting this on 0.5.0 release

**Comment by glihm** [comment]
Now `abigen!` macro lives into [cainome repository](https://github.com/cartridge-gg/cainome/blob/c8e818a747fcdeba0d4007db27e65e482ced9b13/crates/rs/README.md) which should be ready to do this kind of stuff.

**Comment by Matth26** [comment]
I've checked how cainome abigen works, can I try this one?

**Comment by glihm** [comment]
Nice to see you around @Matth26, do not hesitate if you have questions on this. :+1:

**Comment by Matth26** [comment]
Hi @glihm ! Thanks to the `!abigen` macro I'm able to deserialize `EmittedEvent`. However, I'm uncertain how this will address the specific need described in this issue. I can display events based on their types through the event enum, but this approach isn't generic. Each event must be individually formatted according to our requirements, and this method does not works with custom events.

I might be missing something. How do you envision resolving this?

**Comment by glihm** [comment]
> Hi @glihm ! Thanks to the `!abigen` macro I'm able to deserialize `EmittedEvent`. However, I'm uncertain how this will address the specific need described in this issue. I can display events based on their types through the event enum, but this approach isn't generic. Each event must be individually formatted according to our requirements, and this method does not works with custom events.
> 
> I might be missing something. How do you envision resolving this?

The idea is to avoid parsing string of types, which is already handled by the parser crate. You actually don't need to use `abigen!` in this one. :)

Take the lines here: https://github.com/dojoengine/dojo/blob/ca3b018048ddbeaa3a78c8287143ba526e0f89a0/bin/sozo/src/ops/events.rs#L92-L146.

Instead of parsing each possible type, we will prefer using the token parsing from Cainome, which already does that for us:
https://github.com/cartridge-gg/cainome/blob/54df2a4114c0c61359c2f1a70bc7e5fb57d9eaf2/crates/parser/src/tokens/mod.rs#L32

And instead, we use the cainome token to decide how print the values.
Doing so, the code will be more generic and will apply to any type supported by Cainome instead of manually registered types.

Hope it clarifies, if not don't hesitate to ask other questions. :+1:

**Comment by Matth26** [comment]
Yes, that makes sense! I thought we needed to use the `abigen` macro, which led me in the wrong direction. Thanks you the quick response. I'll reach out if I have any further questions :)
