### ISSUE TITLE
[BUG]: blockifier limits steps to 4M

### ISSUE THREAD

**Issue by greged93** [dojoengine/dojo#897]
**Describe the bug**
Katana provides a way to configure the maximum invoke steps.
https://github.com/dojoengine/dojo/blob/29da31939ba4248ba37a50bff04b69ed8646e9ce/crates/katana/core/src/backend/config.rs#L65
This value is however overwritten by blockifier when calling the function `max_invoke_steps` in the `run_or_revert` function.
https://github.com/dojoengine/blockifier/blob/f46101544c54e433adea39c56eeee63d0715e49d/crates/blockifier/src/transaction/account_transaction.rs#L655
https://github.com/dojoengine/blockifier/blob/f46101544c54e433adea39c56eeee63d0715e49d/crates/blockifier/src/execution/entry_point.rs#L123

**To Reproduce**
Set the `invoke_max_steps`to a high value such as 2**24, send a transaction which requires a lot of steps (more than 4M) and transaction should fail.

**Expected behavior**
Transaction should pass if `invoke_max_steps` is set to a high value.

**Comment by bajpai244** [comment]
Hello greg, I can take this.
