### ISSUE TITLE
[Katana] Expose panic reason to client side and not only to log

### ISSUE THREAD

**Issue by yoga-braavos** [dojoengine/dojo#904]
**Is your feature request related to a problem? Please describe.**
Contract errors cannot be consumed programmatically from client side. A generic error is returned for failed contract invocations without the panic reason:
`E            Input: 'Client failed with code 40: Contract error.'`

**Describe the solution you'd like**
Output the panic reason (felt) not only to the log but also as part of the API output. For example, this is printed out to the log but not returned to the client:
```
2023-09-18T13:09:31.874215Z  WARN executor: Transaction validation error: ContractConstructorExecutionFailed(ExecutionFailed { error_data: [StarkFelt("0x00000000000000000000494e56414c49445f4445504c4f594d454e545f534947")] })
```

**Comment by kariy** [comment]
is it part of the JSON-RPC spec to include the errors reason in the API response? or does it break the spec if it is included? ideally, we don't want to introduce anything that's not gonna be spec compatible.

**Comment by yoga-braavos** [comment]
You are correct, I opened an issue in the specs repo and also communicated Starkware regarding this

https://github.com/starkware-libs/starknet-specs/issues/137

**Comment by kariy** [comment]
seems like will be added in [`v0.5.0`](https://github.com/starkware-libs/starknet-specs/releases/tag/v0.5.0-rc1)

**Comment by kariy** [comment]
closing this as it will be included in [upcoming](https://github.com/starkware-libs/starknet-specs/releases/tag/v0.5.0-rc1) json-rpc ver. and implementing this now will break current rpc spec that `katana` is based on.
