### ISSUE TITLE
[KATANA] Improve `katana` tests

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#922]
The `katana` crate is quite lacking in terms of tests. If you find anything in the crate that is worth writing an unit/integration tests for, then don't hesitate to open a PR for that.

**Comment by ponderingdemocritus** [comment]
@kariy has anything changed on this? Should we set this for 0.5.0?

**Comment by ponderingdemocritus** [comment]
closing as will reopen with detailed tasklist with new Katana update
