### ISSUE TITLE
Dojo Semantic Improvements

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#924]
1. Implement Semantic tests for inline macros similar to the cairo repo
         Reference for loading corelib from scarb https://github.com/dojoengine/dojo/blob/main/crates/sozo/src/commands/test.rs#L89
         Reference for SemanitcTestDB https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-semantic/src/test_utils.rs#L30
         Expr testing in cairo https://github.com/starkware-libs/cairo/blob/88a34013e2fdc78488366082577eab0b5459ddff/crates/cairo-lang-semantic/src/expr/test.rs#L46
2. Update `Model` layout function to compute layout at compile time, similar to `consteval!` https://github.com/starkware-libs/cairo/blob/88a34013e2fdc78488366082577eab0b5459ddff/crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs#L60
3. Add `packed_size` method to `Model` with the computed backed felt length
4. Add semantic parsing to compiler to output component dependencies for contracts

**Comment by tarrencev** [comment]
@shramee I think we are focused on (4) now?

**Comment by shramee** [comment]
Aye, we are!
