### ISSUE TITLE
[sozo] naming conflicts between Components & Systems

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#930]
**Describe the bug**
A system & component using same name will create conflicts.
Generated artifacts are named [project_name]-[component_name].json or [project_name]-[system_name].json
Since only one artifact is created, the system will not be added to manifest.json

**To Reproduce**
Create a system & a component using same name.

**Additional context**
Using latest dojo version

**Comment by tarrencev** [comment]
what do you suggest?

**Comment by notV4l** [comment]
adding model/system prefix/suffix/middlefix(?)
[project_name]-model-[model_name].json
[project_name]-system-[system_name].json

**Comment by notV4l** [comment]
otherwise just raise an error when building and let users deal with naming limitation

**Comment by tarrencev** [comment]
ok lgtm except contract rather than system
