### ISSUE TITLE
[sozo] Systems name & artifact naming

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#931]
**Describe the bug**
I have a system named `game1`
Generatred artifact will be named [project_name]-game1.json

When migrating : 
`error: Problem preparing for migration.
Caused by:
    missing contract artifact for `game_1` contract`

**To Reproduce**
Create a system named `game1` or `gameA`
Try to `sozo migrate`

**Additional context**
Using latest dojo version

**Comment by wraitii** [comment]
This happens because `sozo` expects snake_cased contracts

**Comment by tarrencev** [comment]
Is this still an issue? If so, let's please address
