### ISSUE TITLE
[KATANA] Generalize pre-deployed contracts logic

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#952]

**Comment by tarrencev** [comment]
Did we decide not to do this?

**Comment by kariy** [comment]
> Did we decide not to do this?

Ah no, just want to tidy things up and only left issues that i want to focus/already have plans for.

I can open it again if prefer that way.

**Comment by tarrencev** [comment]
ah yeah i think it is worth keeping open to track. we can move it to a backlog
