### ISSUE TITLE
[sozo] Check versions before running

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#963]
**Is your feature request related to a problem? Please describe.**
Currently, if a user runs `sozo` and their is a version mismatch the compiler will throw an error, causing confusion. This is a common problem as dojo is evolving so fast.

**Describe the solution you'd like**
We should check the `dojo` installed version against the scarb version, if there is a mismatch - instead of compiling, suggest to the user that they need to change installed dojo versions to match the Scarb.

**Comment by 0xicosahedron** [comment]
can i try to tackle this please?
