### ISSUE TITLE
[BUG] cargo build/test fail when started at project root directory

### ISSUE THREAD

**Issue by azurwastaken** [dojoengine/dojo#980]
**Describe the bug**
the linker explode when using cargo build or cargo test at the repo's root. I should build each component that fail manually to fix this

**To Reproduce**
I have i7-9700k and 16 go RAM, building on WSL (Debian distro). just clone and cargo build or cargo test (in fact just follow [THIS](https://book.dojoengine.org/getting-started/setup.html))

**Expected behavior**
Build without any errors

**Screenshot**
Here is an example :
![image](https://github.com/dojoengine/dojo/assets/30268138/8e58cbe4-532a-44dc-b691-9c36eafd8244)

here is the full error : 
https://pastebin.com/UbKCPek1

**Comment by gianalarcon** [comment]
Just now I tried `cargo build`, `cargo test` and it is working. Make sure you installed the latest version
`dojoup --version v0.3.0-rc4`

**Comment by azurwastaken** [comment]
yeah i know its working on some computer, what's your config @gianalarcon (OS, Ram)? because i think that my combo WSL + 16go ram might be to weak for the global linking at the end.

I only manage to cargo build/test when i build some crates alone before

**Comment by gianalarcon** [comment]
I have i5-12450H x12 and 16 GiB RAM building on Linux (pop-os distro). Actually it takes time to complete `cargo test`

**Comment by azurwastaken** [comment]
Yeah i guess its because of windows subsystem that take a lot of ressources then...

**Comment by tarrencev** [comment]
closing for now since i don't think there is anything we can do here?
