### ISSUE TITLE
Change name of #[system] attribute

### ISSUE THREAD

**Issue by credence0x** [dojoengine/dojo#983]
**Is your feature request related to a problem? Please describe.**
Considering that in dojo v0.3.0,  systems are the individual functions and not the contracts, it might not be proper to leave the name of the attribute used on top  of contracts as `#[system]`. It might create the impression that the contracts are the systems
e.g 
```
#[system]
mod trade {
    fn buy(...){...}    
    fn sell(...){...}
}
```

**Describe the solution you'd like**
Rename the `#[system]` attribute to be something like `#[dojo::contract]`, `#[dojo::systems]` or `systems`

```
#[dojo::contract]
mod trade {
    fn buy(...){...}    
    fn sell(...){...}
}
```

**Comment by akhercha** [comment]
Hey, can I try this one?

**Comment by glihm** [comment]
This is the expansion of `#[system]`:

```rust
#[starknet::contract]
mod $name$ {
    use dojo::world;
    use dojo::world::IWorldDispatcher;
    use dojo::world::IWorldDispatcherTrait;

    #[storage]
    struct Storage {
        world_dispatcher: ContractAddress,
    }

    #[external(v0)]
    fn name(self: @ContractState) -> felt252 {
        '$name$'
    }

    $body$
}
```

As the contract new is just a `bundle` to have systems definitions, does the `name` function still relevant then? As from what you've said that the system name is now the function name itself.

Even if it's not the contract itself that is a system, my point of view (being a total beginner in ECS/Dojo contracts), it still very helpful to have this `system` term in a word somewhere. Having `dojo::contract` we may loose this coupling with `system`.

Could those suggestions also match @credence0x?
```rust
// Only pluralize the attribute name.
#[systems]

// Connotation with contract and system.
#[systems_contract]

// This one sounds very interesting to me.
#[system_group]
```

**Comment by ponderingdemocritus** [comment]
We need to start explaining that fns within contracts are systems, not the contracts themselves - yes it is a little confusing. 

So to me changing to `#[dojo::contract]` or something similar makes the most sense.

**Comment by credence0x** [comment]
> As the contract new is just a `bundle` to have systems definitions, does the `name` function still relevant then? As from what you've said that the system name is now the function name itself.

Hmm. yeah the `name` does seem irrelevant. 

> Even if it's not the contract itself that is a system, my point of view (being a total beginner in ECS/Dojo contracts), it still very helpful to have this `system` term in a word somewhere. Having `dojo::contract` we may loose this coupling with `system`.

i'll just add `dojo::systems` and `systems` (with an s making it plural) to the suggestions. i think those could be good names too

@tarrencev maybe you have comments to add

**Comment by tarrencev** [comment]
I think `#[dojo::contract]` is a good solution

**Comment by ponderingdemocritus** [comment]
lets land this is 0.3.0
