### ISSUE TITLE
[sozo] migrate do not update contracts/systems

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#996]
**Describe the bug**
`sozo migrate` is not updating contracts/systems

**Expected behavior**
`sozo migrate` should update contracts/systems

**Additional context**
latest versions

**Comment by tarrencev** [comment]
@kariy it looks like some changes @shramee made to the migration flow might have broken updates. Do you mind taking a quick look and providing some info on what is missing?

**Comment by kariy** [comment]
> @kariy it looks like some changes @shramee made to the migration flow might have broken updates. Do you mind taking a quick look and providing some info on what is missing?

no prob

**Comment by shramee** [comment]
Thanks Kariy!

**Comment by kariy** [comment]
Resolved in #1034
